Repository DataLinkDC/dinky, pull requests merged in 2022-11, with the labels that each got.

#1185 [Fix][web ] hotfix delete mfsu config
  dlink-web/config/config.ts
Labels: bug

#1183 [Optimize][Dinky]更新jackson & sa-token version
  pom.xml
Labels: optimization

#1186 [feature][GitHub workflow] add package size check
  .github/workflows/backend.yaml
  check_package_size.sh
Labels: new feature

#1188 [fix][udf]udf修复，未包含udf可直接跳过
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
Labels: bug

#1194 refactor: icon load from local
  dlink-web/public/icons/background_image.svg
  dlink-web/public/icons/notice_empty.svg
  dlink-web/public/icons/notice_not_found.svg
  dlink-web/public/icons/tenant_default.svg
  dlink-web/public/icons/user_avatar.png
  dlink-web/src/app.tsx
  dlink-web/src/components/NoticeIcon/NoticeIcon.tsx
  dlink-web/src/components/NoticeIcon/NoticeList.tsx
  dlink-web/src/components/Studio/StudioMenu/index.tsx
  dlink-web/src/pages/user/Login/index.less
  dlink-web/src/pages/user/Login/index.tsx
Labels: optimization

#1197 Fix application mode missing databsse param
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/db/DBUtil.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
Labels: bug

#1199 [fix][UDF]修复udf重构后，导致session模式无法使用udf
  dlink-admin/pom.xml
  dlink-admin/src/main/java/com/dlink/service/UDFService.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
  dlink-common/src/main/java/com/dlink/config/Dialect.java
  dlink-core/pom.xml
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-function/pom.xml
  dlink-function/src/main/java/com/dlink/function/FunctionFactory.java
  dlink-function/src/main/java/com/dlink/function/compiler/JVMPackage.java
  dlink-function/src/main/java/com/dlink/function/data/model/UDFPath.java
  dlink-function/src/main/java/com/dlink/function/util/UDFUtil.java
Labels: bug

#1204 fix: continuous click task item will open multiply tabs problem.
  dlink-web/src/components/Studio/StudioTree/index.tsx
Labels: bug

#1205 [Optimeze][pom] maven package Model optimeze
  .github/workflows/backend.yaml
  dlink-app/dlink-app-1.11/pom.xml
  dlink-app/dlink-app-1.12/pom.xml
  dlink-app/dlink-app-1.13/pom.xml
  dlink-app/dlink-app-1.14/pom.xml
  dlink-app/dlink-app-1.15/pom.xml
  dlink-app/pom.xml
  dlink-catalog/dlink-catalog-mysql/pom.xml
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.12/pom.xml
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/pom.xml
  dlink-connectors/dlink-connector-doris-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.11/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.12/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.14/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.13/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.14/pom.xml
  dlink-connectors/dlink-connector-pulsar-1.14/pom.xml
  dlink-connectors/pom.xml
  dlink-core/pom.xml
  dlink-executor/pom.xml
  dlink-extends/dependency-reduced-pom.xml
  dlink-extends/pom.xml
  dlink-flink/dlink-flink-1.11/pom.xml
  dlink-flink/dlink-flink-1.12/pom.xml
  dlink-flink/dlink-flink-1.13/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
  dlink-flink/dlink-flink-1.15/pom.xml
  dlink-flink/pom.xml
  dlink-gateway/pom.xml
  docs/docs/developer_guide/local_debug.md
  docs/docs/developer_guide/remote_debug.md
  pom.xml
Labels: optimization

#1193 [Feature][web] implement internationalization of registrationcenter
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_dml.sql
  dlink-web/src/components/Studio/StudioConsole/StudioHistory/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioCluster/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/components/SessionForm.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioDataBase/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioConfig/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioEnvSetting/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioSetting/index.tsx
  dlink-web/src/locales/en-US/global.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/global.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/AlertGroup/components/AlertGroupForm.tsx
  dlink-web/src/pages/AlertInstance/components/AlertInstanceChooseForm.tsx
  dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
  dlink-web/src/pages/AlertInstance/components/EmailForm.tsx
  dlink-web/src/pages/AlertInstance/components/FeiShuForm.tsx
  dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
  dlink-web/src/pages/Cluster/components/ClusterForm.tsx
  dlink-web/src/pages/Cluster/index.tsx
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/index.tsx
  dlink-web/src/pages/DataBase/Columns/index.tsx
  dlink-web/src/pages/DataBase/components/DBForm.tsx
  dlink-web/src/pages/DataBase/components/DataBaseForm.tsx
  dlink-web/src/pages/DataBase/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/FlinkClusterInfo/TaskManager/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Version/VersionTimeLineList/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/index.tsx
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/DevOps/OpsStatusModel/index.tsx
  dlink-web/src/pages/DevOps/StatusDetailedModel/index.tsx
  dlink-web/src/pages/Document/components/DocumentForm.tsx
  dlink-web/src/pages/Document/index.tsx
  dlink-web/src/pages/FragmentVariable/components/FragmentForm.tsx
  dlink-web/src/pages/FragmentVariable/index.tsx
  dlink-web/src/pages/Jar/components/JarForm.tsx
  dlink-web/src/pages/Jar/index.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/components/flinkConfig.tsx
  dlink-web/src/pages/Task/components/updateForm.tsx
  dlink-web/src/pages/Task/index.tsx
Labels: optimization

#1212 [Optimeze][pom]优化打包部分
  .github/workflows/backend.yaml
  .gitignore
  dlink-assembly/src/main/assembly/package.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/pom.xml
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.12/pom.xml
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/pom.xml
  dlink-connectors/dlink-connector-doris-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.11/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.12/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.14/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.13/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.14/pom.xml
  dlink-connectors/dlink-connector-pulsar-1.14/pom.xml
  dlink-core/pom.xml
  dlink-executor/pom.xml
  dlink-extends/dependency-reduced-pom.xml
  dlink-extends/pom.xml
  dlink-flink/dlink-flink-1.11/pom.xml
  dlink-flink/dlink-flink-1.12/pom.xml
  dlink-flink/dlink-flink-1.13/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
  dlink-flink/dlink-flink-1.15/pom.xml
  dlink-gateway/pom.xml
  docs/docs/developer_guide/local_debug.md
  docs/docs/developer_guide/remote_debug.md
  pom.xml
Labels: optimization

#1217 [Fix] [dlink-client] dlink-client-1.15 compilation exceptions caused by codeStyle
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/SinkBuilder.java
Labels: bug

#1218 [Optimeze][doc]Doc optimeze
  docs/docs/build_deploy/build.md
  docs/docs/developer_guide/local_debug.md
  docs/docs/udf_develop/how_to/Python.md
  pom.xml
Labels: optimization

#1219 [Optimeze][udf]udf添加空模板选择
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-web/src/components/Studio/StudioTree/components/SimpleTaskForm.tsx
Labels: optimization

#1220 feat: compatible java 11
  .github/workflows/backend.yaml
  dlink-alert/dlink-alert-base/pom.xml
  dlink-alert/dlink-alert-dingtalk/pom.xml
  dlink-alert/dlink-alert-email/pom.xml
  dlink-alert/dlink-alert-feishu/pom.xml
  dlink-alert/dlink-alert-wechat/pom.xml
  dlink-alert/pom.xml
  dlink-app/dlink-app-base/pom.xml
  dlink-app/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.16/pom.xml
  dlink-catalog/dlink-catalog-mysql/pom.xml
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/dlink-client-base/pom.xml
  dlink-daemon/pom.xml
  dlink-executor/pom.xml
  dlink-flink/pom.xml
  dlink-function/pom.xml
  dlink-metadata/dlink-metadata-doris/pom.xml
  dlink-metadata/dlink-metadata-hive/pom.xml
  dlink-metadata/dlink-metadata-phoenix/pom.xml
  dlink-metadata/dlink-metadata-presto/pom.xml
  dlink-metadata/dlink-metadata-sqlserver/pom.xml
  dlink-metadata/dlink-metadata-starrocks/pom.xml
  dlink-process/pom.xml
  pom.xml
Labels: new feature

#1224 separate npm build steps out
  .github/workflows/backend.yaml
Labels: optimization

#1227 fix: write function wrong operation.
  dlink-process/src/main/java/com/dlink/process/pool/ConsolePool.java
Labels: optimization

#1226 [Feature][web] implement internationalization
  dlink-web/src/components/Studio/StudioConsole/StudioProcess/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/index.tsx
  dlink-web/src/components/Studio/StudioMenu/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioJarSetting/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioKubernetesConfig/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioSetting/index.tsx
  dlink-web/src/components/Studio/StudioTabs/index.tsx
  dlink-web/src/components/Studio/StudioTree/components/UploadModal.tsx
  dlink-web/src/components/Studio/StudioTree/index.tsx
  dlink-web/src/locales/en-US/global.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/en-US/request.ts
  dlink-web/src/locales/zh-CN/global.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/locales/zh-CN/request.ts
  dlink-web/src/pages/API/TaskAPI/index.tsx
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/service.ts
  dlink-web/src/pages/DataBase/service.ts
  dlink-web/src/pages/DevOps/JobInfo/Alert/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/BaseInfo/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/CheckPoints/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/DataMap/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Exception/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Version/VersionList/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/index.tsx
  dlink-web/src/pages/DevOps/index.tsx
  dlink-web/src/pages/FragmentVariable/function.ts
  dlink-web/src/pages/Jar/index.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/function.ts
  dlink-web/src/pages/SettingCenter/ProcessList/index.tsx
  dlink-web/src/pages/SettingCenter/UDFTemplate/index.tsx
  dlink-web/src/pages/Task/index.tsx
  dlink-web/src/pages/Welcome.tsx
Labels: new feature

#1229 fix: npm cache error
  .github/workflows/backend.yaml
Labels: bug

#1228 [Optimeze][pom]模块优化
  dlink-admin/pom.xml
  dlink-admin/src/main/assembly/package.xml
  dlink-assembly/pom.xml
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-base/pom.xml
  dlink-core/pom.xml
  dlink-executor/pom.xml
  pom.xml
Labels: optimization

#1231 [Fix][admin,web]hotfix internationalization && optimization DirConstant.java
  dlink-admin/src/main/java/com/dlink/constant/DirConstant.java
  dlink-web/src/components/Studio/StudioEvent/DDL.ts
  dlink-web/src/global.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/en-US/request.ts
  dlink-web/src/locales/zh-CN/menu.ts
  dlink-web/src/locales/zh-CN/request.ts
  dlink-web/src/pages/AlertInstance/service.ts
  dlink-web/src/pages/ClusterConfiguration/service.ts
  dlink-web/src/pages/DataBase/index.tsx
  dlink-web/src/pages/DataBase/service.ts
  dlink-web/src/pages/SettingCenter/SystemInfo/index.tsx
Labels: bug

#1235 feat: add npm dist cache
  .github/workflows/backend.yaml
Labels: optimization

#1238 [Fix-1063][doc] fix dlink_task_statement table filed length
  dlink-doc/sql/dinky.sql
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_ddl.sql
Labels: optimization

#1234 [Optimize][pom]optimize pom module code
  dlink-admin/pom.xml
  dlink-app/dlink-app-1.11/pom.xml
  dlink-app/dlink-app-1.12/pom.xml
  dlink-app/dlink-app-1.13/pom.xml
  dlink-app/dlink-app-1.15/pom.xml
  dlink-app/dlink-app-1.16/pom.xml
  dlink-app/dlink-app-base/pom.xml
  dlink-app/pom.xml
  dlink-assembly/pom.xml
  dlink-assembly/src/main/assembly/package.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.16/pom.xml
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.11/src/main/java/org/apache/flink/client/python/PythonFunctionFactory.java
  dlink-client/dlink-client-1.11/src/main/java/org/apache/flink/configuration/Configuration.java
  dlink-client/dlink-client-1.11/src/main/java/org/apache/flink/configuration/ConfigurationUtils.java
  dlink-client/dlink-client-1.12/pom.xml
  dlink-client/dlink-client-1.12/src/main/java/org/apache/flink/client/python/PythonFunctionFactory.java
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/dlink-client-hadoop/pom.xml
  dlink-connectors/dlink-connector-doris-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.11/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.12/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.14/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.13/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.14/pom.xml
  dlink-connectors/dlink-connector-pulsar-1.14/pom.xml
  dlink-extends/pom.xml
  dlink-flink/dlink-flink-1.11/pom.xml
  dlink-flink/dlink-flink-1.12/pom.xml
  dlink-flink/dlink-flink-1.13/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
  dlink-function/pom.xml
  dlink-function/src/main/java/com/dlink/function/compiler/PythonFunction.java
  dlink-function/src/main/java/com/dlink/function/util/FlinkUtils.java
  dlink-gateway/pom.xml
  pom.xml
Labels: optimization

#1242 Add new sink connector 'datastream-doris-ext' for CDCSOURCE
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/AdditionalColumnEntry.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisExtendSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisExtendSinkOptions.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/doris/AdditionalColumnEntry.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/doris/DorisExtendSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/doris/DorisExtendSinkOptions.java
Labels: new feature

#1250 [Feature-1251][admin,web] Add backend internationalization
  dlink-admin/src/main/java/com/dlink/configure/AppConfiguration.java
  dlink-admin/src/main/java/com/dlink/configure/SaTokenConfigure.java
  dlink-admin/src/main/java/com/dlink/exception/WebExceptionHandler.java
  dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
  dlink-admin/src/main/java/com/dlink/utils/MessageResolverUtils.java
  dlink-admin/src/main/resources/application.properties
  dlink-admin/src/main/resources/i18n/messages.properties
  dlink-admin/src/main/resources/i18n/messages_en_US.properties
  dlink-admin/src/main/resources/i18n/messages_zh_CN.properties
  dlink-web/src/pages/user/Login/index.tsx
Labels: enhancement

#1253 DataStudio metadata add refesh button
  dlink-web/src/components/Studio/StudioLeftTool/StudioMetaData/index.tsx
Labels: new feature

#1260 [Fix][admin] Fix backend internationalization
  dlink-admin/src/main/java/com/dlink/configure/AppConfiguration.java
  dlink-admin/src/main/java/com/dlink/constant/BaseConstant.java
  dlink-admin/src/main/java/com/dlink/exception/WebExceptionHandler.java
  dlink-admin/src/main/java/com/dlink/interceptor/LocaleChangeInterceptor.java
  dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
  dlink-admin/src/main/java/com/dlink/utils/CopyrightUtil.java
  dlink-admin/src/main/resources/i18n/messages.properties
  dlink-admin/src/main/resources/i18n/messages_en_US.properties
  dlink-admin/src/main/resources/i18n/messages_zh_CN.properties
  dlink-web/src/pages/user/Login/index.tsx
Labels: bug

#1262 fix: cluster display nothing when alias is not set
  dlink-web/src/pages/Cluster/components/ClusterForm.tsx
Labels: bug

#1263 feat: move request head tenantId to cookie
  dlink-admin/src/main/java/com/dlink/interceptor/TenantInterceptor.java
Labels: new feature

#1264 [Optimize ][web] optimize the tenant selection logic when login
  dlink-admin/src/main/java/com/dlink/service/impl/TenantServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
  dlink-web/src/pages/user/Login/index.tsx
Labels: optimization

#1268 [Fix][pom]change connector ouput dir
  dlink-web/pom.xml
  pom.xml
Labels: bug

#1275 [fix] [dlink-admin] fix task_version qerry error
  dlink-admin/src/main/resources/mapper/TaskVersionMapper.xml
Labels: bug

#1272 scan partition support datetime
  dlink-connectors/dlink-connector-jdbc-1.14/src/main/java/org/apache/flink/connector/jdbc/internal/options/JdbcLookupOptions.java
  dlink-connectors/dlink-connector-jdbc-1.14/src/main/java/org/apache/flink/connector/jdbc/split/JdbcDatetimeBetweenParametersProvider.java
  dlink-connectors/dlink-connector-jdbc-1.14/src/main/java/org/apache/flink/connector/jdbc/table/JdbcConnectorOptions.java
  dlink-connectors/dlink-connector-jdbc-1.14/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactory.java
  dlink-connectors/dlink-connector-jdbc-1.14/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSource.java
Labels: new feature

#1282 [Fix][web] Fix that the backend cannot obtain the i18n value of the front-end
  dlink-web/src/pages/user/Login/index.tsx
Labels: bug

#1281 [Fix][metadata]Remove duplicated init of datasource
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
Labels: bug

#1283 Optimize k8s submission pages
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/AppConfig.java
  dlink-web/src/components/Studio/StudioKubernetes/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioKubernetesConfig/index.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/conf.ts
Labels: optimization

#1284 fix: jdk11_1.16 problem and auto compile
  .github/workflows/backend.yaml
  dlink-client/dlink-client-1.16/pom.xml
  dlink-function/pom.xml
  pom.xml
Labels: bug

#1291 [Optimize]Code optimize
  dlink-admin/src/main/java/com/dlink/Dlink.java
  dlink-admin/src/main/resources/log4j2.xml
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnGateway.java
  pom.xml
Labels: optimization

#1292 [optimization][metadata] Improve and clean up unused code in AbstractJdbcDriver and DriverConfig
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/DriverConfig.java
Labels: optimization

#1301 fix: replaceVariable, if replacement is regex, maybe wrong.
  dlink-executor/src/main/java/com/dlink/executor/SqlManager.java
Labels: bug

#1304 bug fix; when submit task, lost Parallelism
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/AppConfig.java
Labels: bug

#1306 bug fix, k8s savepoint failed
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Labels: bug

#1298 [Feature][admin,web] add database copying
  dlink-admin/src/main/java/com/dlink/controller/DataBaseController.java
  dlink-admin/src/main/java/com/dlink/service/DataBaseService.java
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/DataBase/index.tsx
  dlink-web/src/pages/DataBase/service.ts
Labels: new feature

#1307 feat: maven cache only root pom.xml
  .github/workflows/backend.yaml
Labels: optimization

#1313 [Optimize]Optimize github workflow pom
  .github/workflows/backend.yaml
  dlink-doc/sql/dinky.sql
  pom.xml
Labels: optimization

#1315 bug fix k8s sql application savepoint failed
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Labels: bug

#1323 Bug fix fragement
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
Labels: bug

#1319 [Feature][doc] added docs search && upgrade docusaurus version to 2.2.0
  docs/docusaurus.config.js
  docs/package.json
Labels: documentation

#1328 [Fix][doc] fix cannot search Chinese language
  docs/docusaurus.config.js
Labels: bug

#1342 Improve and clean up unused code in AbstractCDCBuilder
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/postgres/PostgresCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sqlserver/SqlServerCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
Labels: optimization

#1339 [Feature-1337]新增Yarn-Session模式，Kerberos环境票据认证
  dlink-executor/pom.xml
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
Labels: new feature

#1336 Fix/metadata pg
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/driver/PostgreSqlDriver.java
Labels: bug

#1320 [Feature] flinkSQL 添加内置日期变量
  dlink-executor/src/main/java/com/dlink/constant/FlinkSQLConstant.java
  dlink-executor/src/main/java/com/dlink/executor/SqlManager.java
Labels: new feature
