Repository DataLinkDC/dinky, pull requests merged in 2022-08, with the labels that each got.

#817 [Optimization-816][Common] Fix Chinese README link error and add English README.
  README.md
  README.zh-CN.md
  README_zh_CN.md
Labels: documentation

#829 remove sensitive info for more api.
  dlink-admin/src/main/java/com/dlink/security/SecurityAspect.java
Labels: optimization

#851 fix execute error by flink 1.14.4
  dlink-client/dlink-client-1.14/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
Labels: bug

#853 [Optimization][Style] Optimization code style import order.
  style/checkstyle.xml
Labels: optimization

#864 fix SQLSinkBuilder.buildRow in flink-client-1.11 and flink-client-1.12
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
Labels: bug

#845 修复字符乱码和时区不正确以及增加datastream实现
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/starrocks/StarrocksSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/utils/ObjectConvertUtil.java
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/starrocks/StarrocksSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/utils/ObjectConvertUtil.java
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/utils/ObjectConvertUtil.java
Labels: bug, new feature

#867 [Optimization][Git] Added `.DS_Store` git file ignore
  .gitignore
Labels: optimization

#871 修改 dlink-conector-pulsar-1.14 pom.xml 文件
  dlink-connectors/dlink-connector-pulsar-1.14/pom.xml
Labels: bug

#872 使用dlink链接Flink1.14.4，SavePoint停止任务时会出现，这个问题我jackjson进行了升级就解决了，Flink1.…
  pom.xml
Labels: bug

#863 [bug and doc] yarn per job
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnPerJobGateway.java
  docs/docs/build_deploy/deploy.md
  docs/docs/extend/practice_guide/cross_join.md
  docs/docs/extend/practice_guide/kafka_to_hive.md
  docs/docs/extend/practice_guide/lookup_join.md
  docs/docs/extend/practice_guide/temporal_join.md
  docs/versioned_docs/version-0.6/build_deploy/deploy.md
  docs/versioned_docs/version-0.6/extend/practice_guide/cross_join.md
  docs/versioned_docs/version-0.6/extend/practice_guide/kafka_to_hive.md
  docs/versioned_docs/version-0.6/extend/practice_guide/lookup_join.md
  docs/versioned_docs/version-0.6/extend/practice_guide/temporal_join.md
Labels: documentation

#891 [Optimization][Style]Added dlink-alert module code style.
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AbstractAlert.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/Alert.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertConfig.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertException.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertMsg.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertPool.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertResult.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertSendResponse.java
  dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/ShowType.java
  dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkAlert.java
  dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkConstants.java
  dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkSender.java
  dlink-alert/dlink-alert-dingtalk/src/test/java/com/dlink/alert/dingtalk/DingTalkTest.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/EmailAlert.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/EmailConstants.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/ExcelUtils.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/MailSender.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/template/AlertTemplate.java
  dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/template/DefaultHTMLTemplate.java
  dlink-alert/dlink-alert-email/src/test/java/com/dlink/alert/email/EmailSenderTest.java
  dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuAlert.java
  dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuConstants.java
  dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuSender.java
  dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/HttpRequestUtil.java
  dlink-alert/dlink-alert-feishu/src/test/java/com.dlink.alert.feishu/FeiShuSenderTest.java
  dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatAlert.java
  dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatConstants.java
  dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
  dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatType.java
  dlink-alert/dlink-alert-wechat/src/test/java/com/dlink/alert/wechat/WeChatSenderTest.java
Labels: optimization

#892 [Optimization][Style] Added dlink-common module code style.
  dlink-common/src/main/java/com/dlink/assertion/Asserts.java
  dlink-common/src/main/java/com/dlink/constant/CommonConstant.java
  dlink-common/src/main/java/com/dlink/constant/NetConstant.java
  dlink-common/src/main/java/com/dlink/exception/JobException.java
  dlink-common/src/main/java/com/dlink/exception/MetaDataException.java
  dlink-common/src/main/java/com/dlink/exception/RunTimeException.java
  dlink-common/src/main/java/com/dlink/exception/SqlException.java
  dlink-common/src/main/java/com/dlink/model/Catalog.java
  dlink-common/src/main/java/com/dlink/model/Column.java
  dlink-common/src/main/java/com/dlink/model/ColumnType.java
  dlink-common/src/main/java/com/dlink/model/FlinkColumn.java
  dlink-common/src/main/java/com/dlink/model/JobLifeCycle.java
  dlink-common/src/main/java/com/dlink/model/JobStatus.java
  dlink-common/src/main/java/com/dlink/model/Schema.java
  dlink-common/src/main/java/com/dlink/model/SystemConfiguration.java
  dlink-common/src/main/java/com/dlink/model/Table.java
  dlink-common/src/main/java/com/dlink/model/TaskOperatingSavepointSelect.java
  dlink-common/src/main/java/com/dlink/model/TaskOperatingStatus.java
  dlink-common/src/main/java/com/dlink/pool/AbstractPool.java
  dlink-common/src/main/java/com/dlink/pool/ClassEntity.java
  dlink-common/src/main/java/com/dlink/pool/ClassPool.java
  dlink-common/src/main/java/com/dlink/result/AbstractResult.java
  dlink-common/src/main/java/com/dlink/result/ExplainResult.java
  dlink-common/src/main/java/com/dlink/result/IResult.java
  dlink-common/src/main/java/com/dlink/result/SqlExplainResult.java
  dlink-common/src/main/java/com/dlink/utils/JSONUtil.java
  dlink-common/src/main/java/com/dlink/utils/LogUtil.java
  dlink-common/src/main/java/com/dlink/utils/RunTimeUtil.java
  dlink-common/src/main/java/com/dlink/utils/SqlUtil.java
Labels: optimization

#895 [Optimization][Style] Added dlink-catalog module code style.
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/src/main/java/com/dlink/flink/catalog/DlinkMysqlCatalog.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactory.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactoryOptions.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/src/main/java/com/dlink/flink/catalog/DlinkMysqlCatalog.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactory.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactoryOptions.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/src/test/java/com/dlink/flink/catalog/DlinkMysqlCatalogTest.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/src/test/java/com/dlink/flink/catalog/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactoryTest.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/src/main/java/com/dlink/flink/catalog/DlinkMysqlCatalog.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactory.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactoryOptions.java
Labels: optimization

#899 [Optimization][Style] Added dlink-app module code style.
  dlink-app/dlink-app-1.11/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.12/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.13/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.14/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.15/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/db/DBConfig.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/db/DBUtil.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/StatementParam.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
Labels: optimization

#900 [Optimization][metadata] Optimized connection pooling and connection creation
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
  dlink-metadata/dlink-metadata-clickhouse/src/main/java/com/dlink/metadata/driver/ClickHouseDriver.java
  dlink-metadata/dlink-metadata-hive/src/main/java/com/dlink/metadata/driver/HiveDriver.java
  dlink-metadata/dlink-metadata-phoenix/src/main/java/com/dlink/metadata/driver/PhoenixDriver.java
Labels: optimization

#919 [Optimization][Style] Added dlink-executor module code style.
  dlink-executor/src/main/java/com/dlink/catalog/function/FunctionManager.java
  dlink-executor/src/main/java/com/dlink/catalog/function/UDFunction.java
  dlink-executor/src/main/java/com/dlink/constant/FlinkConstant.java
  dlink-executor/src/main/java/com/dlink/constant/FlinkFunctionConstant.java
  dlink-executor/src/main/java/com/dlink/constant/FlinkSQLConstant.java
  dlink-executor/src/main/java/com/dlink/exception/FlinkException.java
  dlink-executor/src/main/java/com/dlink/executor/AppBatchExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/AppStreamExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/EnvironmentSetting.java
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-executor/src/main/java/com/dlink/executor/ExecutorSetting.java
  dlink-executor/src/main/java/com/dlink/executor/LocalBatchExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/LocalStreamExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/RemoteBatchExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/RemoteStreamExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/SqlManager.java
  dlink-executor/src/main/java/com/dlink/interceptor/FlinkInterceptor.java
  dlink-executor/src/main/java/com/dlink/interceptor/FlinkInterceptorResult.java
  dlink-executor/src/main/java/com/dlink/parser/BaseSingleSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/CreateAggTableSelectSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/CreateCDCSourceSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/DeleteSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/InsertSelectSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/InsertSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/SelectSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/SetSqlParser.java
  dlink-executor/src/main/java/com/dlink/parser/ShowFragmentParser.java
  dlink-executor/src/main/java/com/dlink/parser/SingleSqlParserFactory.java
  dlink-executor/src/main/java/com/dlink/parser/SqlSegment.java
  dlink-executor/src/main/java/com/dlink/parser/SqlType.java
  dlink-executor/src/main/java/com/dlink/parser/UpdateSqlParser.java
  dlink-executor/src/main/java/com/dlink/trans/AbstractOperation.java
  dlink-executor/src/main/java/com/dlink/trans/CreateOperation.java
  dlink-executor/src/main/java/com/dlink/trans/Operation.java
  dlink-executor/src/main/java/com/dlink/trans/Operations.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/AggTable.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateAggTableOperation.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/SetOperation.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/ShowFragmentOperation.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/ShowFragmentsOperation.java
  dlink-executor/src/test/java/com.dlink.executor/FlinkInterceptorTest.java
Labels: optimization

#920 [Optimization][Style] Added dlink-function and dlink-gateway module code style
  dlink-function/src/main/java/com/dlink/ud/udf/GetKey.java
  dlink-function/src/main/java/com/dlink/ud/udtaf/RowsToMap.java
  dlink-function/src/main/java/com/dlink/ud/udtaf/Top2.java
  dlink-function/src/main/java/com/dlink/ud/udtaf/Top2WithRetract.java
  dlink-gateway/src/main/java/com/dlink/gateway/AbstractGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/Gateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/GatewayType.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/ActionType.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/AppConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/ClusterConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/ConfigPara.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/FlinkConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/GatewayConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/SavePointStrategy.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/SavePointType.java
  dlink-gateway/src/main/java/com/dlink/gateway/exception/GatewayException.java
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/model/JobInfo.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/AbstractGatewayResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/GatewayResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/KubernetesResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/SavePointResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/TestResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/result/YarnResult.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnPerJobGateway.java
  dlink-gateway/src/test/java/com/dlink/gateway/GatewayTest.java
Labels: optimization

#922 [Optimization][License] Add a license description to the pom file.
  dlink-admin/pom.xml
  dlink-alert/dlink-alert-base/pom.xml
  dlink-alert/dlink-alert-dingtalk/pom.xml
  dlink-alert/dlink-alert-email/pom.xml
  dlink-alert/dlink-alert-feishu/pom.xml
  dlink-alert/dlink-alert-wechat/pom.xml
  dlink-alert/pom.xml
  dlink-app/dlink-app-1.11/pom.xml
  dlink-app/dlink-app-1.12/pom.xml
  dlink-app/dlink-app-1.13/pom.xml
  dlink-app/dlink-app-1.14/pom.xml
  dlink-app/dlink-app-1.15/pom.xml
  dlink-app/dlink-app-base/pom.xml
  dlink-assembly/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.13/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.14/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.15/pom.xml
  dlink-catalog/dlink-catalog-mysql/pom.xml
  dlink-catalog/pom.xml
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.12/pom.xml
  dlink-client/dlink-client-1.13/pom.xml
  dlink-client/dlink-client-1.14/pom.xml
  dlink-client/dlink-client-1.15/pom.xml
  dlink-client/dlink-client-base/pom.xml
  dlink-client/dlink-client-hadoop/pom.xml
  dlink-client/pom.xml
  dlink-common/pom.xml
  dlink-connectors/dlink-connector-doris-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.11/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.12/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.13/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.14/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.13/pom.xml
  dlink-connectors/dlink-connector-phoenix-1.14/pom.xml
  dlink-connectors/dlink-connector-pulsar-1.14/pom.xml
  dlink-connectors/pom.xml
  dlink-core/pom.xml
  dlink-daemon/pom.xml
  dlink-executor/pom.xml
  dlink-extends/pom.xml
  dlink-flink/dlink-flink-1.11/pom.xml
  dlink-flink/dlink-flink-1.12/pom.xml
  dlink-flink/dlink-flink-1.13/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
  dlink-flink/dlink-flink-1.15/pom.xml
  dlink-flink/pom.xml
  dlink-function/pom.xml
  dlink-gateway/pom.xml
  dlink-metadata/dlink-metadata-base/pom.xml
  dlink-metadata/dlink-metadata-clickhouse/pom.xml
  dlink-metadata/dlink-metadata-doris/pom.xml
  dlink-metadata/dlink-metadata-hive/pom.xml
  dlink-metadata/dlink-metadata-mysql/pom.xml
  dlink-metadata/dlink-metadata-oracle/pom.xml
  dlink-metadata/dlink-metadata-phoenix/pom.xml
  dlink-metadata/dlink-metadata-postgresql/pom.xml
  dlink-metadata/dlink-metadata-sqlserver/pom.xml
  dlink-metadata/pom.xml
  pom.xml
Labels: optimization

#935 'dlink-client-hadoop打包增加ServicesResourceTransformer'
  dlink-client/dlink-client-hadoop/pom.xml
Labels: optimization

#862 Fix cluster submission taskId is empty
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
Labels: optimization, fixing

#953 [Optimization][Style] Configure global checkstyle validation.
  .github/workflows/backend.yaml
  dlink-admin/src/main/java/com/dlink/controller/FragmentVariableController.java
  dlink-admin/src/main/java/com/dlink/dto/StudioExecuteDTO.java
  dlink-admin/src/main/java/com/dlink/mapper/FragmentVariableMapper.java
  dlink-admin/src/main/java/com/dlink/model/FragmentVariable.java
  dlink-admin/src/main/java/com/dlink/service/FragmentVariableService.java
  dlink-admin/src/main/java/com/dlink/service/impl/FragmentVariableServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/JobInstanceServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-app/dlink-app-1.15/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/CDCBuilderFactory.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/postgres/PostgresCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sqlserver/SqlServerCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sqlserver/SqlServerJsonDebeziumDeserializationSchema.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/kafka/KafkaSinkJsonBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/model/LineageRel.java
  dlink-common/src/main/java/com/dlink/model/SystemConfiguration.java
  dlink-common/src/main/java/com/dlink/utils/JSONUtil.java
  dlink-connectors/dlink-connector-phoenix-1.13/src/main/java/org/apache/flink/connector/phoenix/internal/JdbcBatchingOutputFormat.java
  dlink-connectors/dlink-connector-phoenix-1.14/src/main/java/org/apache/flink/connector/phoenix/internal/JdbcBatchingOutputFormat.java
  dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
  dlink-core/src/main/java/com/dlink/explainer/lineage/LineageBuilder.java
  dlink-core/src/main/java/com/dlink/explainer/lineage/LineageRelation.java
  dlink-core/src/main/java/com/dlink/explainer/lineage/LineageTable.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/LineageBuilder.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/LineageColumn.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/LineageUtils.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/TreeNode.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/TreeNodeIterator.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-core/src/main/java/com/dlink/result/ResultRunnable.java
  dlink-executor/src/main/java/com/dlink/parser/SingleSqlParserFactory.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/SetOperation.java
  dlink-extends/dependency-reduced-pom.xml
  dlink-gateway/src/main/java/com/dlink/gateway/config/FlinkConfig.java
  dlink-metadata/dlink-metadata-clickhouse/src/test/java/com/dlink/metadata/ClickHouseTest.java
  pom.xml
  style/checkstyle.xml
Labels: optimization

#954 [Feature] Add swagger api doc
  dlink-admin/pom.xml
  dlink-admin/src/main/java/com/dlink/configure/Knife4jConfiguration.java
  dlink-admin/src/main/resources/application.yml
  pom.xml
Labels: new feature

#958 Sqlserver增加date类型数据转换规则
  dlink-metadata/dlink-metadata-sqlserver/src/main/java/com/dlink/metadata/convert/SqlServerTypeConvert.java
Labels: optimization

#970 [Fix][dlink-gateway]修复k8s Application、Yarn Application、Yarn PerJob提交任务时未指定集群配置MasterMemoryMB、TaskManagerMemoryMB、SlotsPerTaskManager
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnPerJobGateway.java
Labels: bug

#969 cdcsource增加多目标库同步功能
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
Labels: new feature

#949 【Fix】the full database sync kafkasinkbuilder does not implement serialization and cause an error
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
Labels: bug

#971 优化PG数据库schema_name查询sql
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/query/PostgreSqlQuery.java
Labels: bug
