Repository DataLinkDC/dinky, pull requests merged in 2022-10, with the labels that each got.

#1064 fix(sec): upgrade mysql-connector-java to 8.0.28
  dlink-extends/dependency-reduced-pom.xml
  pom.xml
Labels: optimization

#1069 Fix [*] Replace System.out.println with logger.info
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/executor/CustomTableResultImpl.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/executor/CustomTableResultImpl.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/executor/CustomTableResultImpl.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/executor/CustomTableResultImpl.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/LineageBuilder.java
  dlink-core/src/main/java/com/dlink/explainer/sqllineage/LineageUtils.java
  dlink-core/src/main/java/com/dlink/utils/UDFUtil.java
Labels: optimization

#1068 [Fix] Add uuid after doris label prefix.
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
Labels: optimization

#1079 System Setting Page International Development
  dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
  dlink-web/config/defaultSettings.ts
  dlink-web/src/app.tsx
  dlink-web/src/locales/en-US/menu.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/menu.ts
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/DevOps/index.tsx
  dlink-web/src/pages/Settings/components/flinkConfig.tsx
  dlink-web/src/pages/Settings/index.tsx
  dlink-web/src/pages/user/components/PasswordForm.tsx
  dlink-web/src/pages/user/components/UserForm.tsx
  dlink-web/src/pages/user/index.tsx
Labels: optimization

#1090 add support session run udf.jar
  dlink-admin/src/main/java/com/dlink/controller/JarController.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-core/src/main/java/com/dlink/constant/PathConstant.java
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-core/src/main/java/com/dlink/utils/UDFUtil.java
  dlink-core/src/main/java/com/dlink/utils/ZipUtils.java
  dlink-executor/src/main/java/com/dlink/executor/EnvironmentSetting.java
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-executor/src/main/java/com/dlink/executor/RemoteStreamExecutor.java
Labels: new feature

#1097 Devops page internationalization
  dlink-web/src/components/Studio/StudioConsole/index.tsx
  dlink-web/src/components/Studio/StudioHome/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioConfig/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioGuide/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioSqlConfig/index.tsx
  dlink-web/src/locales/en-US/globalHeader.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/pages/Cluster/index.tsx
  dlink-web/src/pages/DataBase/Columns/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/TableData/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
  dlink-web/src/pages/DataStudio/model.ts
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/DevOps/index.tsx
Labels: optimization

#1102 [optimization][web] Frontend code optimization
  dlink-web/src/pages/AlertGroup/index.tsx
  dlink-web/src/pages/AlertInstance/components/AlertInstanceChooseForm.tsx
  dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
  dlink-web/src/pages/AlertInstance/components/EmailForm.tsx
  dlink-web/src/pages/AlertInstance/components/FeiShuForm.tsx
  dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
  dlink-web/src/pages/AlertInstance/index.tsx
  dlink-web/src/pages/AuthenticationCenter/NamespaceManager/components/NameSpaceForm.tsx
  dlink-web/src/pages/AuthenticationCenter/RoleManager/components/RoleForm.tsx
  dlink-web/src/pages/AuthenticationCenter/TenantManager/components/TenantForm.tsx
  dlink-web/src/pages/AuthenticationCenter/TenantManager/index.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/components/PasswordForm.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/components/UserForm.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/index.tsx
  dlink-web/src/pages/Cluster/components/ClusterForm.tsx
  dlink-web/src/pages/Cluster/index.tsx
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/index.tsx
  dlink-web/src/pages/DataBase/components/DBForm.tsx
  dlink-web/src/pages/DataBase/index.tsx
  dlink-web/src/pages/Document/components/DocumentForm.tsx
  dlink-web/src/pages/Document/index.tsx
  dlink-web/src/pages/FragmentVariable/components/FragmentForm.tsx
  dlink-web/src/pages/FragmentVariable/index.tsx
  dlink-web/src/pages/Jar/components/JarForm.tsx
  dlink-web/src/pages/Jar/index.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/index.tsx
  dlink-web/src/pages/user/Login/index.tsx
Labels: optimization

#1107 [doc] [docs] Optimize deploy doc.
  docs/docs/build_deploy/deploy.md
  docs/versioned_docs/version-0.6/build_deploy/deploy.md
Labels: documentation

#1114 [Document] [docs] Add flink metrics monitor and optimize deploy document
  docs/docs/build_deploy/deploy.md
  docs/docs/extend/function_expansion/flinktaskmonitor.md
  docs/docs/extend/function_expansion/flinkversion.md
  docs/versioned_docs/version-0.6/build_deploy/deploy.md
  docs/versioned_docs/version-0.6/extend/function_expansion/flinktaskmonitor.md
  docs/versioned_docs/version-0.6/extend/function_expansion/flinkversion.md
  docs/versioned_docs/version-0.6/extend/practice_guide/cross_join.md
  docs/versioned_docs/version-0.6/extend/practice_guide/dataspherestudio.md
  docs/versioned_docs/version-0.6/extend/practice_guide/dolphinscheduler.md
  docs/versioned_docs/version-0.6/extend/practice_guide/hudi.md
  docs/versioned_docs/version-0.6/extend/practice_guide/iceberg.md
  docs/versioned_docs/version-0.6/extend/practice_guide/kafka_to_hive.md
  docs/versioned_docs/version-0.6/extend/practice_guide/kudu.md
  docs/versioned_docs/version-0.6/extend/practice_guide/lookup_join.md
  docs/versioned_docs/version-0.6/extend/practice_guide/redis.md
  docs/versioned_docs/version-0.6/extend/practice_guide/temporal_join.md
  docs/versioned_docs/version-0.6/extend/practice_guide/udf.md
Labels: documentation

#1121 add Flink UDF Template
  dlink-admin/src/main/java/com/dlink/controller/UDFController.java
  dlink-admin/src/main/java/com/dlink/mapper/UDFTemplateMapper.java
  dlink-admin/src/main/java/com/dlink/model/UDFTemplate.java
  dlink-admin/src/main/java/com/dlink/service/UDFTemplateService.java
  dlink-admin/src/main/java/com/dlink/service/impl/UDFTemplateServiceImpl.java
  dlink-doc/sql/dlink_udf.sql
  dlink-web/config/routes.ts
  dlink-web/src/locales/en-US/menu.ts
  dlink-web/src/locales/zh-CN/menu.ts
  dlink-web/src/pages/SettingCenter/UDFTemplate/data.d.ts
  dlink-web/src/pages/SettingCenter/UDFTemplate/index.css
  dlink-web/src/pages/SettingCenter/UDFTemplate/index.tsx
  dlink-web/src/pages/SettingCenter/UDFTemplate/service.tsx
Labels: new feature

#1122 Uniform internationalization code format
  dlink-web/src/components/Footer/index.tsx
  dlink-web/src/components/Studio/StudioConsole/index.tsx
  dlink-web/src/components/Studio/StudioHome/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioGuide/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioSqlConfig/index.tsx
  dlink-web/src/locales/en-US/menu.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/pages/Admin.tsx
  dlink-web/src/pages/Cluster/index.tsx
  dlink-web/src/pages/DataBase/Columns/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/TableData/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/DevOps/index.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/components/flinkConfig.tsx
  dlink-web/src/pages/Welcome.tsx
Labels: optimization

#1128 [Feature][admin,core] add flink pre-job udf;
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
Labels: new feature

#1131 [Feature][admin,core,gateway]add udf yarn-application
  dlink-admin/src/main/java/com/dlink/service/UDFService.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-gateway/src/main/java/com/dlink/gateway/config/GatewayConfig.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnPerJobGateway.java
Labels: new feature

#1132 [Feature][sql,docs] Optimize SQL files and differentiate versions by directory
  README.md
  README_zh_CN.md
  dlink-assembly/src/main/assembly/package.xml
  dlink-doc/doc/Dlink-0.3.2更新说明.md
  dlink-doc/doc/Dlink0.3.0重磅来袭.md
  dlink-doc/doc/DlinkOnYarn三种Flink执行方式的实践.md
  dlink-doc/doc/Dlink实时计算平台——部署篇.md
  dlink-doc/doc/Dlink核心概念与实现原理详解.md
  dlink-doc/doc/FlinkAggTable在Dlink的应用.md
  dlink-doc/sql/dinky.sql
  dlink-doc/sql/dlink.sql
  dlink-doc/sql/dlink_udf.sql
  dlink-doc/sql/dlinkmysqlcatalog.sql
  dlink-doc/sql/upgrade/0.6.0_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.0_schema/mysql/dinky_dml.sql
  dlink-doc/sql/upgrade/0.6.2_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.5_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.6_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.7_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_dml.sql
  docs/docs/build_deploy/deploy.md
  docs/docs/developer_guide/local_debug.md
  docs/docs/developer_guide/remote_debug.md
  docs/download/dinky-0.6.6.md
  docs/download/dinky-0.6.7.md
  docs/versioned_docs/version-0.6/build_deploy/deploy.md
Labels: optimization

#1125 [Fix-1130][metadata]AWS RDS PostGreSQL can't get schema
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/query/PostgreSqlQuery.java
Labels: bug

#1135 refactor: some trick modification
  dlink-common/src/main/java/com/dlink/assertion/Asserts.java
  dlink-common/src/main/java/com/dlink/utils/SqlUtil.java
  dlink-executor/src/main/java/com/dlink/parser/SqlType.java
  dlink-executor/src/main/java/com/dlink/trans/Operations.java
  dlink-gateway/src/main/java/com/dlink/gateway/GatewayType.java
Labels: optimization

#1136 [Fix][web,sql] hotfix some problems
  dlink-doc/sql/dinky.sql
  dlink-doc/sql/upgrade/0.6.0_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.0_schema/mysql/dinky_dml.sql
  dlink-doc/sql/upgrade/0.6.2_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.5_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.6_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.7_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_ddl.sql
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_dml.sql
  dlink-web/src/locales/en-US.ts
  dlink-web/src/locales/en-US/button.ts
  dlink-web/src/locales/en-US/global.ts
  dlink-web/src/locales/en-US/menu.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/en-US/settingDrawer.ts
  dlink-web/src/locales/en-US/settings.ts
  dlink-web/src/locales/zh-CN.ts
  dlink-web/src/locales/zh-CN/button.ts
  dlink-web/src/locales/zh-CN/global.ts
  dlink-web/src/locales/zh-CN/menu.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/locales/zh-CN/settingDrawer.ts
  dlink-web/src/locales/zh-CN/settings.ts
  dlink-web/src/pages/Cluster/index.tsx
Labels: bug

#1147 fix: ResultPool concurrence hidden danger
  dlink-core/src/main/java/com/dlink/result/ResultPool.java
Labels: bug

#1142 fix: fix initPythonUDF function not check udfList paramepter is empty.
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
Labels: optimization

#1146 fix: JobConfig constructor useAutoCancel parameter pass wrong value.
  dlink-admin/src/main/java/com/dlink/dto/APIExecuteSqlDTO.java
Labels: bug

#1148 refactor: improve readability, add log, fix iterator exception after miniCluster close
  dlink-core/src/main/java/com/dlink/result/ResultRunnable.java
Labels: optimization

#1149 chore: update spotless version
  pom.xml
Labels: optimization

#1152 fix: fixPackageError
  dlink-executor/src/main/java/com/dlink/interceptor/FlinkInterceptor.java
  dlink-executor/src/test/java/com/dlink/interceptor/FlinkInterceptorTest.java
Labels: optimization

#1156 [Feature][web] Improve internationalization
  .gitignore
  dlink-web/config/config.ts
  dlink-web/src/components/Chart/BarChartSetting/index.tsx
  dlink-web/src/components/Chart/LineChartSetting/index.tsx
  dlink-web/src/components/Chart/PieChartSetting/index.tsx
  dlink-web/src/components/Chart/index.tsx
  dlink-web/src/components/Common/JobLifeCycle.tsx
  dlink-web/src/components/Common/JobStatus.tsx
  dlink-web/src/components/Common/function.ts
  dlink-web/src/components/Lineage/LineageOps.tsx
  dlink-web/src/components/Studio/StudioConsole/StudioFX/index.tsx
  dlink-web/src/components/Studio/StudioEvent/DDL.ts
  dlink-web/src/components/Studio/StudioLeftTool/StudioCluster/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioDataBase/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioFragment/index.tsx
  dlink-web/src/components/Studio/StudioTabs/index.tsx
  dlink-web/src/components/Studio/StudioTree/components/SimpleTaskForm.tsx
  dlink-web/src/components/Studio/StudioTree/components/UpdateCatalogueForm.tsx
  dlink-web/src/components/Studio/StudioTree/index.tsx
  dlink-web/src/components/Studio/conf.ts
  dlink-web/src/locales/en-US.ts
  dlink-web/src/locales/en-US/chart.ts
  dlink-web/src/locales/en-US/global.ts
  dlink-web/src/locales/en-US/menu.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN.ts
  dlink-web/src/locales/zh-CN/chart.ts
  dlink-web/src/locales/zh-CN/global.ts
  dlink-web/src/locales/zh-CN/menu.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/AlertGroup/components/AlertGroupForm.tsx
  dlink-web/src/pages/AlertGroup/index.tsx
  dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
  dlink-web/src/pages/AlertInstance/components/EmailForm.tsx
  dlink-web/src/pages/AlertInstance/components/FeiShuForm.tsx
  dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
  dlink-web/src/pages/AlertInstance/index.tsx
  dlink-web/src/pages/AuthenticationCenter/NamespaceManager/components/NameSpaceForm.tsx
  dlink-web/src/pages/AuthenticationCenter/NamespaceManager/index.tsx
  dlink-web/src/pages/AuthenticationCenter/RoleManager/components/RoleForm.tsx
  dlink-web/src/pages/AuthenticationCenter/RoleManager/index.tsx
  dlink-web/src/pages/AuthenticationCenter/TenantManager/components/TenantForm.tsx
  dlink-web/src/pages/AuthenticationCenter/TenantManager/index.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/components/TableTransfer.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/components/UserForm.tsx
  dlink-web/src/pages/AuthenticationCenter/UserManager/index.tsx
  dlink-web/src/pages/Cluster/components/ClusterForm.tsx
  dlink-web/src/pages/Cluster/index.tsx
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/index.tsx
  dlink-web/src/pages/DataBase/components/DataBaseForm.tsx
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/Document/components/DocumentForm.tsx
  dlink-web/src/pages/Document/index.tsx
  dlink-web/src/pages/FragmentVariable/components/FragmentForm.tsx
  dlink-web/src/pages/FragmentVariable/index.tsx
  dlink-web/src/pages/Jar/components/JarForm.tsx
  dlink-web/src/pages/Jar/index.tsx
  dlink-web/src/pages/Task/components/updateForm.tsx
  pom.xml
Labels: new feature

#1162 [Fix][udf,core] fix udf can not use 3 languages at the same time
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-core/src/main/java/com/dlink/udf/UDF.java
  dlink-core/src/main/java/com/dlink/utils/UDFUtil.java
Labels: bug

#1161 chore: add result type strict and format code
  dlink-admin/src/main/java/com/dlink/controller/StudioController.java
Labels: optimization

#1165 refactor: simplify sqlManager code.
  dlink-executor/src/main/java/com/dlink/executor/SqlManager.java
Labels: optimization

#1171 refactor: simple Job2MysqlHandler
  dlink-admin/src/main/java/com/dlink/job/Job2MysqlHandler.java
  dlink-core/src/main/java/com/dlink/config/Dialect.java
Labels: optimization

#1166 refactor: simplify Executor code, and log and extract common code fragment
  dlink-core/src/main/java/com/dlink/result/SelectResultBuilder.java
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-executor/src/main/java/com/dlink/executor/ExecutorSetting.java
Labels: optimization

#1172 [fix][udf]修复前端切换udf对应代码时，默认选中值无法切换的问题
  dlink-web/src/components/Studio/StudioTree/components/SimpleTaskForm.tsx
Labels: bug

#1155 refactor: improve code readability. eliminate hide problem, wait for 0.7
  dlink-admin/src/main/java/com/dlink/dto/StudioExecuteDTO.java
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/FragmentVariableServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-common/src/main/java/com/dlink/assertion/Asserts.java
  dlink-core/src/main/java/com/dlink/job/JobResult.java
  dlink-core/src/main/java/com/dlink/utils/UDFUtil.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
  dlink-process/src/main/java/com/dlink/process/model/ProcessEntity.java
  dlink-process/src/main/java/com/dlink/process/model/ProcessStep.java
  dlink-process/src/main/java/com/dlink/process/pool/ConsolePool.java
  dlink-process/src/main/java/com/dlink/process/pool/ProcessPool.java
Labels: optimization

#1174 [fix][udf]修复udf逻辑遗留问题
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
  dlink-doc/sql/upgrade/0.6.8_schema/mysql/dinky_dml.sql
Labels: bug

#1177 [feature][udf]添加udf 使用文档
  docs/docs/udf_develop/_category_.json
  docs/docs/udf_develop/how_to/Java&Scala.md
  docs/docs/udf_develop/how_to/Python.md
  docs/docs/udf_develop/how_to/_category_.json
  docs/docs/udf_develop/intro.md
  docs/docs/udf_develop/template_intro.md
Labels: documentation

#1151 feat: update Guava and Lombok Version
  pom.xml
Labels: optimization
