Repository DataLinkDC/dinky, pull requests merged in 2022-09, with the labels that each got.

#972 [Fix][dlink-gateway]修复k8s application模式提交失败，优化增加获取JobId等待时间
  dlink-common/src/main/java/com/dlink/model/SystemConfiguration.java
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnApplicationGateway.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnPerJobGateway.java
  dlink-web/src/pages/Settings/components/flinkConfig.tsx
  dlink-web/src/pages/Settings/model.ts
Labels: new feature

#980 [document] [docs] Optimizing Deployment Documents
  docs/docs/build_deploy/deploy.md
  docs/versioned_docs/version-0.6/build_deploy/deploy.md
Labels: documentation

#986 [optimization][web]optimization Some problems in front-end and some tips
  dlink-web/src/components/Studio/StudioTree/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Exception/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/index.tsx
Labels: optimization

#1007 [Fix][admin,web,app,core] Fix rc1 bugs
  dlink-admin/src/main/java/com/dlink/controller/FileUploadController.java
  dlink-admin/src/main/java/com/dlink/service/FileUploadService.java
  dlink-admin/src/main/java/com/dlink/service/impl/FileUploadServiceImpl.java
  dlink-admin/src/main/java/com/dlink/utils/HdfsUtil.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
  dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
Labels: bug

#1016 Fix the AbstractSinkBuilder and SQLSinkBuilder logger problem
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
Labels: bug

#1048 Fix [Web] Fix StarRocks databases display
  dlink-web/src/pages/DataBase/components/DBForm.tsx
Labels: bug

#1050 [Fix][web] Fix query exceptions caused by the system's failure to automatically clean up the selected table information when switching data sources
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
Labels: bug

#1054 [Fix][metadata] Fix Exception in obtaining SQLDDL of view
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/query/AbstractDBQuery.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/query/IDBQuery.java
Labels: bug

#1055 [Optimization][web] optimization sqlGeneration Display mode
  dlink-web/src/pages/DataBase/Generation/index.tsx
Labels: optimization

#1056 [Feature-1053][admin] Configured integration DolphinScheduler
  dlink-admin/src/main/java/com/dlink/controller/SchedulerController.java
  dlink-admin/src/main/java/com/dlink/init/SystemInit.java
  dlink-admin/src/main/resources/application.yml
  dlink-scheduler/src/main/java/com/dlink/scheduler/client/ProcessClient.java
  dlink-scheduler/src/main/java/com/dlink/scheduler/client/ProjectClient.java
  dlink-scheduler/src/main/java/com/dlink/scheduler/client/TaskClient.java
  dlink-scheduler/src/main/java/com/dlink/scheduler/config/DolphinSchedulerProperties.java
Labels: new feature
