Repository DataLinkDC/dinky, pull requests merged in 2022-12, with the labels that each got.

#1358 修改注释
  dlink-admin/src/main/java/com/dlink/controller/DataBaseController.java
Labels: optimization

#1353 [feature][k8s application]K8s auto deploy
  dlink-admin/pom.xml
  dlink-admin/src/main/java/com/dlink/controller/DownloadController.java
  dlink-admin/src/main/java/com/dlink/controller/UDFController.java
  dlink-admin/src/main/java/com/dlink/service/impl/ClusterConfigurationServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/resources/DinkyFlinkDockerfile
  dlink-admin/src/main/resources/banner.txt
  dlink-admin/src/main/resources/log4j2.xml
  dlink-app/dlink-app-1.11/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.12/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.13/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.14/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.15/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-1.16/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
  dlink-assembly/src/main/assembly/package.xml
  dlink-client/dlink-client-base/src/main/java/com/dlink/constant/FlinkParamConstant.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/utils/FlinkBaseUtil.java
  dlink-common/pom.xml
  dlink-common/src/main/java/com/dlink/config/Docker.java
  dlink-common/src/main/java/com/dlink/docker/DockerClientBuilder.java
  dlink-common/src/main/java/com/dlink/utils/DockerClientUtils.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesApplicationGateway.java
  dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/ClusterConfiguration/conf.ts
  dlink-web/src/pages/ClusterConfiguration/function.ts
  pom.xml
Labels: new feature

#1359 [fix ][admin] fix Send msg bug by alert Instance disable 补充#1191
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuSender.java
Labels: bug

#1363 [fix][udf]fix save udftemplate
  dlink-admin/src/main/java/com/dlink/service/impl/UDFTemplateServiceImpl.java
  dlink-web/src/pages/SettingCenter/UDFTemplate/index.tsx
Labels: bug

#1346 Fix/metadata sql dialect
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
  dlink-common/src/main/java/com/dlink/model/Table.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractDriver.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
  dlink-metadata/dlink-metadata-oracle/src/main/java/com/dlink/metadata/driver/OracleDriver.java
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/driver/PostgreSqlDriver.java
  dlink-metadata/dlink-metadata-sqlserver/src/main/java/com/dlink/metadata/driver/SqlServerDriver.java
Labels: bug

#1365 [Feature-1364][admin,flink] Add local environment with web UI
  dlink-admin/src/main/java/com/dlink/job/Job2MysqlHandler.java
  dlink-admin/src/main/java/com/dlink/service/impl/ClusterServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/JobHistoryServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-common/src/main/java/com/dlink/assertion/Asserts.java
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-executor/src/main/java/com/dlink/executor/EnvironmentSetting.java
  dlink-executor/src/main/java/com/dlink/executor/LocalBatchExecutor.java
  dlink-executor/src/main/java/com/dlink/executor/LocalStreamExecutor.java
  dlink-flink/dlink-flink-1.11/pom.xml
  dlink-flink/dlink-flink-1.12/pom.xml
  dlink-flink/dlink-flink-1.13/pom.xml
  dlink-flink/dlink-flink-1.14/pom.xml
  dlink-flink/dlink-flink-1.15/pom.xml
  dlink-flink/dlink-flink-1.16/pom.xml
Labels: new feature

#1366 [Fix][k8s]k8s_fix
  dlink-admin/pom.xml
  dlink-admin/src/main/java/com/dlink/service/impl/ClusterConfigurationServiceImpl.java
  dlink-admin/src/main/resources/DinkyFlinkDockerfile
Labels: bug

#1368 [Fix-1367] [admin] Open API does not have tenant
  dlink-admin/src/main/java/com/dlink/assertion/Tips.java
  dlink-admin/src/main/java/com/dlink/controller/APIController.java
  dlink-admin/src/main/java/com/dlink/mapper/JobInstanceMapper.java
  dlink-admin/src/main/java/com/dlink/mapper/TaskMapper.java
  dlink-admin/src/main/java/com/dlink/service/JobInstanceService.java
  dlink-admin/src/main/java/com/dlink/service/TaskService.java
  dlink-admin/src/main/java/com/dlink/service/impl/JobInstanceServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dlink-admin/src/main/resources/mapper/TaskMapper.xml
Labels: bug

#1373 add sql console
  dlink-admin/src/main/java/com/dlink/controller/DataBaseController.java
  dlink-admin/src/main/java/com/dlink/service/DataBaseService.java
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
  dlink-common/src/main/java/com/dlink/model/QueryData.java
  dlink-web/src/components/Studio/StudioEvent/DDL.ts
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/DataCenter/MetaData/Console/function.ts
  dlink-web/src/pages/DataCenter/MetaData/Console/index.tsx
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
Labels: new feature

#1374 [Optimize][pom] optimize udf pom, Clear freeMaker engine
  dlink-admin/src/main/resources/application.yml
  dlink-core/pom.xml
  dlink-function/pom.xml
  dlink-function/src/main/java/com/dlink/function/util/UDFUtil.java
Labels: optimization

#1375 [Optimize][Doc]Doc optimize
  dlink-doc/Dockerfile
  dlink-doc/DockerfileMysql
  docs/docusaurus.config.js
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/i18n/zh/docusaurus-theme-classic/navbar.json
  docs/versioned_docs/version-0.7/build_deploy/_category_.json
  docs/versioned_docs/version-0.7/concept_architecture/_category_.json
  docs/versioned_docs/version-0.7/concept_architecture/architecture.md
  docs/versioned_docs/version-0.7/concept_architecture/concept.md
  docs/versioned_docs/version-0.7/deploy_guide/_category_.json
  docs/versioned_docs/version-0.7/deploy_guide/build.md
  docs/versioned_docs/version-0.7/deploy_guide/deploy.md
  docs/versioned_docs/version-0.7/deploy_guide/quick_start.md
  docs/versioned_docs/version-0.7/get_started/_category_.json
  docs/versioned_docs/version-0.7/get_started/docker_deploy.md
  docs/versioned_docs/version-0.7/get_started/quick_start/_category_.json
  docs/versioned_docs/version-0.7/get_started/quick_start/dbql_quick_start.md
  docs/versioned_docs/version-0.7/get_started/quick_start/flinksql_quick_start.md
  docs/versioned_docs/version-0.7/intro.md
  docs/versioned_docs/version-0.7/platform_intro/_category_.json
  docs/versioned_docs/version-0.7/platform_intro/feature.md
  docs/versioned_docs/version-0.7/platform_intro/intro.md
  docs/versioned_docs/version-0.7/platform_intro/overview.md
  docs/versioned_docs/version-0.7/platform_intro/roadmap.md
  docs/versioned_docs/version-0.7/quick_start/_category_.json
Labels: documentation

#1387 Fix/metadata mysql
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/driver/MySqlDriver.java
Labels: bug

#1379 [Add][doc]add doc migration desc
  dlink-admin/src/main/resources/application.yml
  docs/docusaurus.config.js
  docs/versioned_docs/version-0.7/get_started/docker_deploy.md
Labels: optimization

#1389 fix: compile error w/ scala.function1
  dlink-function/src/main/java/com/dlink/function/compiler/CustomStringScalaCompiler.java
Labels: bug

#1403 [fix][admin]fix database copy error
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
Labels: bug

#1400 [Fix][UDF] fix udf in windows used. And JDK Classloader
  dlink-admin/src/main/java/com/dlink/aop/UdfClassLoaderAspect.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/java/com/dlink/utils/UDFUtils.java
  dlink-client/dlink-client-1.14/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-function/src/main/java/com/dlink/function/context/UDFPathContextHolder.java
  dlink-function/src/main/java/com/dlink/function/util/UDFUtil.java
Labels: bug

#1410 [Feature][UDF] session model support dynamic classLoader external jar
  dlink-admin/src/main/java/com/dlink/aop/UdfClassLoaderAspect.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/UDFServiceImpl.java
  dlink-admin/src/main/java/com/dlink/utils/UDFUtils.java
  dlink-common/src/main/java/com/dlink/classloader/DinkyClassLoader.java
  dlink-common/src/main/java/com/dlink/context/DinkyClassLoaderContextHolder.java
  dlink-common/src/main/java/com/dlink/utils/LogUtil.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-function/src/main/java/com/dlink/function/constant/PathConstant.java
  dlink-function/src/main/java/com/dlink/function/context/UDFPathContextHolder.java
  dlink-process/src/main/java/com/dlink/process/exception/DinkyException.java
Labels: new feature

#1416 [Optimization-1288][web] Give a default page for some modules instead of white blank page
  dlink-web/config/routes.ts
Labels: optimization

#1422 [Optimization][web] The authentication center is not visible under non-admin users
  dlink-web/config/routes.ts
  dlink-web/src/access.ts
Labels: optimization

#1429 [Feature][docs] Added filing information
  docs/docusaurus.config.js
  docs/i18n/en/docusaurus-theme-classic/footer.json
  docs/i18n/zh/docusaurus-theme-classic/footer.json
Labels: optimization

#1430 [Fix][admin] fix delete task bug
  dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
Labels: bug

#1431 [FIX: #1417]: result not have column.
  dlink-core/src/main/java/com/dlink/result/ResultRunnable.java
Labels: bug

#1452 feat: add rest.target-directory to task other configure
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
  dlink-core/src/main/java/com/dlink/job/JobConfig.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-core/src/test/java/com/dlink/core/FlinkRestAPITest.java
Labels: new feature

#1462 fix metadata center query page overflow
  dlink-web/src/pages/DataCenter/MetaData/index.less
Labels: bug

#1459 feat: github unused checkstyle
  .github/workflows/backend.yaml
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-web/src/components/Studio/StudioEdit/index.tsx
Labels: optimization

#1461 The auto-sh script of dinky solves the problem of hosting datasophon …
  dlink-doc/bin/auto.sh
Labels: optimization

#1468 [Optimize][POM] optimize package
  dlink-app/dlink-app-base/pom.xml
  dlink-app/pom.xml
  dlink-assembly/src/main/assembly/package.xml
  dlink-catalog/dlink-catalog-mysql/pom.xml
  dlink-client/dlink-client-base/pom.xml
  dlink-client/pom.xml
  dlink-core/pom.xml
  dlink-doc/bin/auto.sh
  dlink-executor/pom.xml
  dlink-flink/pom.xml
  dlink-function/pom.xml
  dlink-gateway/pom.xml
  pom.xml
Labels: new feature

#1475 Add jmx monitoring
  dlink-admin/pom.xml
  dlink-admin/src/main/resources/jmx/jmx_exporter_config.yaml
  dlink-doc/bin/auto.sh
Labels: new feature

#1477 refactor: add get all inner operations by reflactions
  dlink-executor/pom.xml
  dlink-executor/src/main/java/com/dlink/trans/Operations.java
  pom.xml
Labels: optimization

#1480 [Feature][Auto Build] support docs&docker CI
  .github/workflows/docker_build.yaml
  .github/workflows/docs.yml
  Dockerfile
  DockerfileDinkyFlink
  DockerfileMysql
  check_package_size.sh
Labels: optimization

#1483 [optimize][Action]optimize docs ci remote Path
  .github/workflows/backend.yaml
  .github/workflows/docs.yml
Labels: optimization

#1482 [Optimize-795][admin] Optimize the global configuration of Jackson serialization time zone
  dlink-admin/src/main/resources/application.yml
Labels: optimization

#1484 feat: add get all inner operations by reflactions
  dlink-executor/src/main/java/com/dlink/trans/Operations.java
Labels: optimization

#1486 [Fix][UDF]fix udf sql can not parse and lineage parse
  dlink-core/src/main/java/com/dlink/explainer/Explainer.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
Labels: fixing
