Repository DataLinkDC/dinky, pull requests merged in 2022-03, with the labels that each got.

#247 [Feature-226][docs] add openAPI and integration documment
  docs/zh-CN/_sidebar.md
  docs/zh-CN/api/openapi.md
  docs/zh-CN/extend/integrate.md
  docs/zh-CN/quick_start/build.md
Labels: documentation

#249 [Bug-248] [docs] add dinky_overview and Modifty _sidebar document
  docs/zh-CN/_sidebar.md
  docs/zh-CN/dinky_overview.md
Labels: documentation

#258 [Feature-256][docs] Modify the left menu and add job management
  docs/zh-CN/_sidebar.md
  docs/zh-CN/administrator-guide/Studio/development_control/component_introduce.md
  docs/zh-CN/administrator-guide/Studio/development_control/function_introduce.md
  docs/zh-CN/administrator-guide/Studio/job_manage.md
Labels: documentation

#260 [Fix-257] [docs] Modify data source extension
  docs/zh-CN/administrator-guide/Studio/job_manage.md
  docs/zh-CN/extend/datasource.md
Labels: bug, documentation

#281 [Fix-273] [docs] Modifty datasource document
  docs/zh-CN/extend/datasource.md
Labels: bug, documentation

#286 [Optimization-285][web] optimization document manager
  dlink-web/src/pages/AlertGroup/index.tsx
  dlink-web/src/pages/Document/components/CreateForm.tsx
  dlink-web/src/pages/Document/components/DocumentForm.tsx
  dlink-web/src/pages/Document/components/UpdateForm.tsx
  dlink-web/src/pages/Document/function.ts
  dlink-web/src/pages/Document/index.tsx
Labels: optimization
