Repository DataLinkDC/dinky, pull requests merged in 2023-11, with the labels that each got.

#2472 [Optimization-1682][metadata] Optimize setting named tinyInt1isBit for mysql metadata
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/convert/MySqlTypeConvert.java
Labels: Optimization

#2471 [Fix-1672] [cdc] Fix failed to get metadata due to jdbc session timeout in CDCSOURCE
  dinky-executor/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
Labels: bug

#2470 [Fix-1662] [admin] OpenApi notLoginException
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
Labels: bug

#2469 [Fix-1615] [api] Fix submit task error but return succeed when using dolphinscheduler
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobResult.java
Labels: bug

#2474 [Fix]fix_version
  dinky-admin/src/main/java/org/dinky/configure/Knife4jConfig.java
  dinky-admin/src/main/resources/application.yml
  dinky-common/pom.xml
  dinky-common/src/main/java/org/dinky/DinkyVersion.java
  dinky-common/src/main/resources/common.properties
Labels: bug

#2473 [Refactor][admin] delete un use code
  dinky-admin/src/main/java/org/dinky/assertion/Assert.java
  dinky-admin/src/main/java/org/dinky/controller/FileUploadController.java
  dinky-admin/src/main/java/org/dinky/controller/JarController.java
  dinky-admin/src/main/java/org/dinky/controller/UploadFileRecordController.java
  dinky-admin/src/main/java/org/dinky/data/constant/UploadFileConstant.java
  dinky-admin/src/main/java/org/dinky/data/dto/APIExecuteJarDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/JobDataDto.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskVersionConfigureDTO.java
  dinky-admin/src/main/java/org/dinky/data/model/Jar.java
  dinky-admin/src/main/java/org/dinky/data/model/JobHistory.java
  dinky-admin/src/main/java/org/dinky/data/model/Task.java
  dinky-admin/src/main/java/org/dinky/data/model/UploadFileRecord.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/mapper/JarMapper.java
  dinky-admin/src/main/java/org/dinky/mapper/UploadFileRecordMapper.java
  dinky-admin/src/main/java/org/dinky/service/FileUploadService.java
  dinky-admin/src/main/java/org/dinky/service/JarService.java
  dinky-admin/src/main/java/org/dinky/service/UploadFileRecordService.java
  dinky-admin/src/main/java/org/dinky/service/impl/FileUploadServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JarServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UploadFileRecordServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/FilePathUtil.java
  dinky-admin/src/main/java/org/dinky/utils/HdfsUtil.java
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-admin/src/main/resources/mapper/JarMapper.xml
  dinky-admin/src/main/resources/mapper/UploadFileRecordMapper.xml
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  pom.xml
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Refactor

#2477 [Optimize]spotless license
  dinky-web/src/app.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/JobTags/JobLifeCycleTag.tsx
  dinky-web/src/hooks/useService.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantModalTransfer/TenantTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/RoleModalTransfer/RoleTransfer/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/service.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/service.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/PreViewConfig/CommonSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/PreViewConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/PreViewConfig/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/JobChart/JobChart.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/service.tsx
  dinky-web/src/pages/DevOps/constants.tsx
  dinky-web/src/pages/Home/JobOverView/JobStatusPie/index.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/pages/Other/Login/LoginForm/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/model.ts
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SQLQuery/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/compontents/LoadUser.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
  dinky-web/src/requestErrorConfig.ts
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/services/data.d.ts
  dinky-web/src/types/Studio/state.d.ts
Labels: Optimization

#2479 fix modify cluster instance bug && fix some sql bug
  dinky-admin/src/main/java/org/dinky/data/dto/ClusterInstanceDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/UDFTemplateServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/InstanceForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentProTable/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2482 [Feature-1709][core] Support use FlinkSQL CTE to preview data
  dinky-core/src/main/java/org/dinky/data/result/ResultBuilder.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
Labels: New Feature

#2485 fix some bug
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/data/dto/MenuDTO.java
Labels: bug

#2484 Optimized the Kubernetes submission logic
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/sse/LogSseAppender.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/AbstractGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/GatewayResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/KubernetesResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/SavePointResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/YarnResult.java
Labels: Optimization

#2486 [Feature-1608][admin] Support get task lineage by taskid with openapi
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/data/dto/StudioLineageDTO.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/explainer/sqllineage/SQLLineageBuilder.java
Labels: New Feature

#2488 [Feature-1842][client] Analyze lineage from the original relNode, not the optimized relNode, and add unit tests
  dinky-client/dinky-client-1.14/pom.xml
  dinky-client/dinky-client-1.14/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.14/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.14/src/test/java/org/dinky/utils/LineageContextTest.java
  dinky-client/dinky-client-1.15/pom.xml
  dinky-client/dinky-client-1.15/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.15/src/test/java/org/dinky/utils/LineageContextTest.java
  dinky-client/dinky-client-1.16/pom.xml
  dinky-client/dinky-client-1.16/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.16/src/test/java/org/dinky/utils/LineageContextTest.java
  dinky-client/dinky-client-1.17/pom.xml
  dinky-client/dinky-client-1.17/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.17/src/test/java/org/dinky/utils/LineageContextTest.java
  dinky-client/dinky-client-1.18/pom.xml
  dinky-client/dinky-client-1.18/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.18/src/test/java/org/dinky/utils/LineageContextTest.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/data/model/LineageRel.java
  pom.xml
Labels: New Feature

#2487 Bug fixs
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskSaveDTO.java
  dinky-admin/src/main/java/org/dinky/data/model/mapping/ClusterConfigurationMapping.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-common/src/main/java/org/dinky/data/enums/JobLifeCycle.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/constants.tsx
  dinky-web/src/pages/DataStudio/model.ts
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2492 [Fix-1847][metadata] Fix postgreSql get DDL script error
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/convert/ITypeConvert.java
Labels: bug

#2493 [Fix-1887] [admin] Fix DolphinScheduler can not generate task code in createTaskDefinition
  dinky-admin/src/main/java/org/dinky/controller/SchedulerController.java
Labels: bug

#2490 [Fix-1849][client] Fix CDCSOURCE kafkaSink transactionalIdPrefix NullPointerException
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/SinkBuilderFactory.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
Labels: bug

#2491 support filter empty dir
  dinky-web/src/components/Icons/CodeLanguageIcon.tsx
  dinky-web/src/components/TableTransfer/index.tsx
  dinky-web/src/components/Transfer/TreeTransfer/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/constants.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/function.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/UDFRegisterModal/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/service.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFTemplate/TemplateTable/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFTemplate/UDFTemplateDrawer/index.tsx
  dinky-web/src/pages/RegCenter/UDF/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/RegCenter/data.d.ts
  dinky-web/src/utils/function.tsx
Labels: New Feature

#2494 Add job done hook, Solve the problem of getting "UNKNOWN" after job completion in application mode
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/java/org/dinky/service/JobInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskQueue.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/DefaultThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/ThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonTask.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonTaskConfig.java
  dinky-executor/src/main/java/org/dinky/constant/FlinkConstant.java
Labels: Optimization

#2495 Fill lost other flink version
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.18/src/main/java/org/dinky/app/MainApp.java
Labels: Optimization

#2496 Fix task version bug
  dinky-admin/src/main/java/org/dinky/data/dto/TaskRollbackVersionDTO.java
  dinky-admin/src/main/java/org/dinky/data/model/TaskVersion.java
  dinky-admin/src/main/java/org/dinky/service/TaskVersionService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskVersionServiceImpl.java
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
Labels: bug

#2497 fix: h2 initialize db.sql multiple times
  dinky-admin/src/main/resources/application-h2.yml
Labels: bug

#2500 [Fix][Web]Fix resources manage
  dinky-admin/src/main/java/org/dinky/controller/UDFController.java
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
Labels: bug

#2499 fix some bug about tenantId
  dlink-admin/src/main/java/com/dlink/configure/AppConfiguration.java
  dlink-admin/src/main/java/com/dlink/interceptor/TenantInterceptor.java
Labels: bug

#2503 [Fix-2125][metadata] Fix clickhouse Nullable columns
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/driver/ClickHouseDriver.java
Labels: bug

#2504 [Fix][UDF]Fix udf python
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-function/src/main/resources/getPyFuncList.py
Labels: bug

#2506 [Optimize][h2]optimize h2
  dinky-admin/src/main/resources/application-h2.yml
  dinky-admin/src/main/resources/application.yml
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-admin/src/main/resources/db/db-h2.sql
Labels: Optimization

#2501 Fix udf bug
  dinky-admin/src/main/java/org/dinky/data/model/GitProject.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-admin/src/main/java/org/dinky/utils/RuntimeUtils.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/ColumnInfo/Index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectProTable/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/constans.tsx
  dinky-web/src/pages/RegCenter/GitProject/data.d.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
Labels: bug

#2511 [Fix]fix h2 init
  dinky-admin/src/main/java/org/dinky/aop/WebExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/springframework/jdbc/datasource/init/DatabasePopulatorUtils.java
  dinky-admin/src/main/resources/application-h2.yml
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-admin/src/main/resources/mapper/UDFManageMapper.xml
  dinky-common/src/main/java/org/dinky/data/constant/DirConstant.java
  dinky-executor/src/main/java/org/dinky/executor/VariableManager.java
  pom.xml
Labels: bug

#2512 [Feature][token]Add token persistent
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/CacheConfig.java
  dinky-admin/src/main/java/org/dinky/configure/SaTokenConfigure.java
  dinky-admin/src/main/java/org/dinky/controller/TokenController.java
  dinky-admin/src/main/java/org/dinky/data/model/SysToken.java
  dinky-admin/src/main/java/org/dinky/service/impl/TokenService.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-admin/src/main/resources/mapper/TokenMapper.xml
  dinky-web/src/models/Sse.tsx
  pom.xml
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
Labels: New Feature

#2513 [Feature]Add paimon cache
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/cache/CacheConfiguration.java
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCache.java
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCacheManager.java
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/TokenController.java
  dinky-admin/src/main/java/org/dinky/data/vo/MetricsVO.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonTypeUtil.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
  dinky-common/src/main/java/org/dinky/data/annotations/paimon/Option.java
  dinky-common/src/main/java/org/dinky/data/annotations/paimon/Options.java
  dinky-common/src/main/java/org/dinky/data/annotations/paimon/PartitionKey.java
  dinky-common/src/main/java/org/dinky/data/annotations/paimon/PrimaryKey.java
  dinky-common/src/main/java/org/dinky/data/constant/PaimonTableConstant.java
  dinky-common/src/main/java/org/dinky/data/paimon/CacheData.java
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: New Feature

#2516 refactor some list search
  dinky-admin/src/main/java/org/dinky/controller/AlertGroupController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterConfigurationController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-admin/src/main/java/org/dinky/service/AlertGroupService.java
  dinky-admin/src/main/java/org/dinky/service/AlertInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/ClusterConfigurationService.java
  dinky-admin/src/main/java/org/dinky/service/ClusterInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertGroupServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertInstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/service.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Refactor

#2517 delete some router
  dinky-web/src/pages/DataStudio/route.tsx
Labels: Refactor

#2519 [optimization][docs] add udfdemo
  docs/docs/administrator_guide/udf_develop/how_to/Java&Scala.md
Labels: Doc

#2522 fix some bug about tenantId
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/interceptor/TenantInterceptor.java
Labels: bug

#2523 [Feature][Admin] Git compilation package and Resource integration
  dinky-admin/src/main/java/org/dinky/interceptor/TenantInterceptor.java
  dinky-admin/src/main/java/org/dinky/service/impl/TokenService.java
  dinky-admin/src/main/java/org/dinky/service/resource/BaseResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/ResourcesService.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/HdfsResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/OssResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/sse/git/AnalysisUdfClassStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/AnalysisUdfPythonStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/GetJarsStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/PythonZipStepSse.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-admin/src/main/java/org/dinky/utils/RuntimeUtils.java
Labels: New Feature

#2524 [Bug]fix_web_some_bug
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/DiffModal.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2525 Fix gitbuild cannot close
  dinky-admin/src/main/java/org/dinky/sse/git/GetJarsStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/PythonZipStepSse.java
  dinky-web/src/components/CustomEditor/CodeEdit/function.tsx
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/DiffModal.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
Labels: bug

#2527 hotfix datasource cannot save bug
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-web/src/components/Transfer/TreeTransfer/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/service.tsx
  dinky-web/src/services/endpoints.tsx
Labels: bug

#2529 Fix some bug
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskWorker.java
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList.tsx
Labels: bug, Optimization

#2532 Fix damemon, Paimon , Metrics some bug
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskQueue.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskWorker.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/DefaultThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/ThreadPool.java
Labels: bug

#2533 improve some feature & added `flinksql` language for editor
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/log4j2.xml
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-web/package.json
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/languages/flinksql/constants.ts
  dinky-web/src/components/CustomEditor/languages/flinksql/index.tsx
  dinky-web/src/components/CustomEditor/languages/flinksql/keyword.ts
  dinky-web/src/components/CustomEditor/languages/index.tsx
  dinky-web/src/components/CustomEditor/languages/javalog/index.tsx
  dinky-web/src/components/LineageGraph/lineage-dag-ext.tsx
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/User/components/PasswordModal/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/UserProTable/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/DiffModal.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/components/AlertGroupForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/service.ts
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/model.ts
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/GenSQL/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileShow/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/DevOps/data.d.ts
  dinky-web/src/utils/function.tsx
Labels: bug, Optimization

#2531 docs about global_settings and system_log
  docs/docs/administrator_guide/system_setting/_category_.json
  docs/docs/administrator_guide/system_setting/flink_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/_category_.json
  docs/docs/administrator_guide/system_setting/global_settings/dinky_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/dolphinscheduler_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/flink_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/ldap.md
  docs/docs/administrator_guide/system_setting/global_settings/maven_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/metrics_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/resource_setting.md
  docs/docs/administrator_guide/system_setting/system_log/_category_.json
  docs/docs/administrator_guide/system_setting/system_log/system_log.md
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: Doc

#2534 fix sql bug of h2
  dinky-admin/src/main/java/org/dinky/controller/GitController.java
  dinky-admin/src/main/java/org/dinky/controller/TenantController.java
  dinky-admin/src/main/java/org/dinky/controller/UserController.java
  dinky-admin/src/main/java/org/dinky/data/dto/AssignRoleDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/AssignUserToTenantDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/GitProjectSortJarDTO.java
  dinky-admin/src/main/java/org/dinky/service/GitProjectService.java
  dinky-admin/src/main/java/org/dinky/service/TenantService.java
  dinky-admin/src/main/java/org/dinky/service/UserService.java
  dinky-admin/src/main/java/org/dinky/service/impl/GitProjectServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TenantServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-admin/src/main/resources/db/db-h2-dml.sql
Labels: bug

#2537 Fix datastudio tabs switch bug
  dinky-admin/src/main/resources/log4j2.xml
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
Labels: bug

#2536 [Fix-2535] [studio] Fix the variable of sql dockermysql does not exist when checking task
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/APIExecuteSqlDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/APIExplainSqlDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/AbstractStatementDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/StudioMetaStoreDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: bug

#2540 Fixed the issue that jobs could still be edited after they went online
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
Labels: bug

#2542 fix float btn bug and improve some code
  dinky-web/package.json
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/Icons/CodeLanguageIcon.tsx
  dinky-web/src/global.less
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/JobLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/ExceptionTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/TaskManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/FlinkTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/CodeTreeShow/CodeContent/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/CodeTreeShow/SiderTree/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/CodeTreeShow/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/SettingCenter/SystemLogs/TagInfo/LogList/LogsShow/index.tsx
  dinky-web/src/pages/SettingCenter/SystemLogs/TagInfo/LogList/index.tsx
Labels: bug, Optimization

#2541 [Optimize] You can submit Yarn-Application (Linux) on Windows
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/OssResourceManager.java
  dinky-app/dinky-app-1.14/pom.xml
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/pom.xml
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.16/pom.xml
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.17/pom.xml
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.18/pom.xml
  dinky-app/dinky-app-1.18/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/pom.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/db/DBUtil.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/model/SysConfig.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/resource/BaseResourceManager.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/resource/impl/HdfsResourceManager.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/resource/impl/OssResourceManager.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/url/RsURLConnection.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/url/RsURLStreamHandler.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/url/RsURLStreamHandlerFactory.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
  dinky-client/dinky-client-1.14/pom.xml
  dinky-client/dinky-client-1.14/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.14/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/pom.xml
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-common/pom.xml
  dinky-common/src/main/java/org/dinky/data/app/AppTask.java
  dinky-common/src/main/java/org/dinky/data/properties/OssProperties.java
  dinky-common/src/main/java/org/dinky/oss/OssTemplate.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-gateway/src/main/java/org/dinky/gateway/config/ClusterConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/YarnConfig/index.tsx
Labels: Optimization

#2539 [Doc] modify docs about dolphinscheduler_setting and resource_setting to make it clear
  docs/docs/administrator_guide/system_setting/global_settings/dolphinscheduler_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/resource_setting.md
Labels: Doc

#2543 improve some feature
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/Icons/DBIcons.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Lineage/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/constants.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/constants.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/constans.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/YarnConfig/index.tsx
  dinky-web/src/services/constants.tsx
Labels: Optimization

#2544 Add varibles params in APIController and Web
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskSubmitDto.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-web/src/pages/DataStudio/LeftContainer/GlobaleVar/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: New Feature

#2546 fix: defaultRunModel
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
Labels: bug

#2551 Hide download
  docs/docusaurus.config.js
  docs/src/pages/index.js
Labels: Doc

#2550 [Fix-2549] [studio] Fix editor automatically prompting for duplicate loading
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/languages/flinksql/index.tsx
  dinky-web/src/components/CustomEditor/languages/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2548 Optimize Daemon Schedule, and add delete jobhistory Task
  dinky-admin/src/main/java/org/dinky/configure/ScheduledConfig.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/data/model/job/History.java
  dinky-admin/src/main/java/org/dinky/data/model/job/JobInstance.java
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/job/ClearJobHistoryTask.java
  dinky-admin/src/main/java/org/dinky/job/DynamicResizeFlinkJobPoolTask.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/SystemMetricsTask.java
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/SystemMetricsHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/BuildConfiguration.java
  dinky-admin/src/main/resources/META-INF/services/org.dinky.daemon.task.DaemonTask
  dinky-admin/src/main/resources/META-INF/services/org.dinky.job.JobHandler
  dinky-daemon/src/main/java/org/dinky/daemon/constant/FlinkTaskConstant.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/FlinkJobThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/ScheduleThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonFactory.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonTaskConfig.java
Labels: Refactor

#2552 improve header's button show logical
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/languages/flinksql/index.tsx
  dinky-web/src/components/LineageGraph/lineage-dag-ext.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/constants.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/Home/DevOverView/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
  dinky-web/src/pages/Home/index.tsx
Labels: Optimization

#2555 Fix varible bugs，restore sse log level
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/log4j2.xml
Labels: bug

#2554 Added module certification center
  docs/docs/administrator_guide/authentication_center/menu.md
  docs/docs/administrator_guide/authentication_center/role.md
  docs/docs/administrator_guide/authentication_center/row_limits.md
  docs/docs/administrator_guide/authentication_center/tenant.md
  docs/docs/administrator_guide/authentication_center/token.md
  docs/docs/administrator_guide/authentication_center/user.md
  docs/docs/administrator_guide/register_center/document_manager.md
  docs/docs/thanks.md
Labels: Doc

#2557 [Fix-2556] [cdc] Fix Mysql TimestampType convert to '1970-01-01' in CDCSOURCE
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.11/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.12/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.13/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.14/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.15/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.16/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.17/src/test/java/com/dlink/cdc/sql/SinkBuilderTest.java
Labels: bug

#2559 fix footer jvm info
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Refactor

#2566 Add console log when run debug
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/DebugDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-common/src/main/java/org/dinky/data/annotations/ProcessId.java
Labels: New Feature

#2568 [Optimization-2567][core] Merge dinky-executor into dinky-core
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-app/dinky-app-base/pom.xml
  dinky-core/pom.xml
  dinky-core/src/main/java/org/dinky/connector/printnet/sink/PrintNetDynamicTableSink.java
  dinky-core/src/main/java/org/dinky/connector/printnet/sink/PrintNetDynamicTableSinkFactory.java
  dinky-core/src/main/java/org/dinky/connector/printnet/sink/PrintNetSinkFunction.java
  dinky-core/src/main/java/org/dinky/constant/FlinkConstant.java
  dinky-core/src/main/java/org/dinky/constant/FlinkSQLConstant.java
  dinky-core/src/main/java/org/dinky/exception/FlinkException.java
  dinky-core/src/main/java/org/dinky/executor/AppBatchExecutor.java
  dinky-core/src/main/java/org/dinky/executor/AppStreamExecutor.java
  dinky-core/src/main/java/org/dinky/executor/CustomExtendedOperationExecutorImpl.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/executor/ExecutorConfig.java
  dinky-core/src/main/java/org/dinky/executor/ExecutorFactory.java
  dinky-core/src/main/java/org/dinky/executor/LocalBatchExecutor.java
  dinky-core/src/main/java/org/dinky/executor/LocalStreamExecutor.java
  dinky-core/src/main/java/org/dinky/executor/RemoteBatchExecutor.java
  dinky-core/src/main/java/org/dinky/executor/RemoteStreamExecutor.java
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
  dinky-core/src/main/java/org/dinky/interceptor/FlinkInterceptor.java
  dinky-core/src/main/java/org/dinky/interceptor/FlinkInterceptorResult.java
  dinky-core/src/main/java/org/dinky/parser/CreateCDCSourceSqlParser.java
  dinky-core/src/main/java/org/dinky/parser/SetSqlParser.java
  dinky-core/src/main/java/org/dinky/parser/ShowFragmentParser.java
  dinky-core/src/main/java/org/dinky/parser/SingleSqlParserFactory.java
  dinky-core/src/main/java/org/dinky/trans/Operation.java
  dinky-core/src/main/java/org/dinky/trans/Operations.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CDCSource.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
  dinky-core/src/main/java/org/dinky/trans/show/ShowFragmentOperation.java
  dinky-core/src/main/java/org/dinky/trans/show/ShowFragmentsOperation.java
  dinky-core/src/main/java/org/dinky/utils/KerberosUtil.java
  dinky-core/src/main/resource/META-INF/services/org.apache.flink.table.factories.Factory
  dinky-core/src/test/java/org/dinky/executor/ExecutorConfigTest.java
  dinky-core/src/test/java/org/dinky/interceptor/CdcSourceTests.java
  dinky-core/src/test/java/org/dinky/interceptor/FlinkInterceptorTest.java
  dinky-core/src/test/java/org/dinky/parse/SqlTypeTest.java
  dinky-core/src/test/java/org/dinky/trans/CreateTemporalTableFunctionParseStrategyTest.java
  dinky-executor/pom.xml
  pom.xml
Labels: Optimization

#2573 Add job overview
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/data/model/home/JobInstanceStatus.java
  dinky-admin/src/main/java/org/dinky/data/vo/task/JobInstanceVo.java
  dinky-admin/src/main/java/org/dinky/mapper/JobInstanceMapper.java
  dinky-admin/src/main/java/org/dinky/mybatis/mapper/SuperMapper.java
  dinky-admin/src/main/java/org/dinky/service/JobInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-web/src/components/Icons/DevopsIcons.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/StatisticsCard.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/function.tsx
  dinky-web/src/pages/DevOps/index.tsx
  dinky-web/src/types/Home/data.d.ts
Labels: Refactor

#2577 Add use hook
  dinky-web/src/hooks/index.tsx
  dinky-web/src/hooks/useHookRequest.tsx
  dinky-web/src/hooks/useService.tsx
Labels: Refactor

#2578 Optimized clusterinstance
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-admin/src/main/java/org/dinky/service/ClusterInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
Labels: Optimization

#2580 [Optimization-2579][core] Optimizate JobManager
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
  dinky-common/src/main/java/org/dinky/utils/URLUtils.java
  dinky-core/src/main/java/org/dinky/executor/ExecutorContext.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobParam.java
  dinky-core/src/main/java/org/dinky/job/builder/JobDDLBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-web/src/pages/DataStudio/model.ts
Labels: Optimization

#2584 [Optimization-2583][studio] Optimize project and data source switching
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SQLQuery/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/index.tsx
Labels: Optimization

#2587 Independent batch model field to fix the H 2 SQL incompatibility issue
  dinky-admin/src/main/java/org/dinky/data/model/job/History.java
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-core/src/main/java/org/dinky/job/Job.java
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2590 [Optimization-2588][studio] Optimize hide console when closing all tabs
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  docs/docusaurus.config.js
Labels: Optimization
