Repository DataLinkDC/dinky, pull requests merged in 2023-07, with the labels that each got.

#2118 [Fix][Metadata] Fix dependencies of metadata module
  dinky-metadata/dinky-metadata-hive/pom.xml
Labels: bug

#2122 Refactor the cluster form
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/ApplicationConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/BaseConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8sNative/DockerConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8sNative/K8sConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8sNative/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8sOperator/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/HighPriorityConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/YarnConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/function.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: Refactor

#2125 fix clickhouse Nullable columns
  dlink-metadata/dlink-metadata-clickhouse/src/main/java/com/dlink/metadata/driver/ClickHouseDriver.java
Labels: bug

#2127 [Feature-2126][connector] Add SQLServer Simple Connector in Flink 1.16
  dlink-assembly/src/main/assembly/package.xml
  dlink-connectors/dlink-connector-jdbc-1.16/pom.xml
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/dialect/sqlserver/SQLServerDialect.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/dialect/sqlserver/SQLServerDialectFactory.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/internal/converter/SQLServerRowConverter.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/resources/META-INF/services/org.apache.flink.connector.jdbc.dialect.JdbcDialectFactory
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dlink-connectors/pom.xml
  pom.xml
Labels: New Feature

#2131 [Fix-2126][connector] Add SQLServer Simple Connector in Flink 1.16
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/dialect/sqlserver/SQLServerDialect.java
Labels: bug

#2120 Refactor the Devops Job details page
  dinky-web/config/config.ts
  dinky-web/config/routes.ts
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/JobDetail/components/JobConfigTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/components/JobOperator.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/constants.tsx
  dinky-web/src/pages/DevOps/function.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/DevOps/data.d.ts
Labels: Refactor

#2128 [Optimization][admin] Lack of H2 dependency
  dinky-admin/pom.xml
  dinky-admin/src/main/resources/application.properties
  pom.xml
Labels: Optimization

#2135 [Fix-2134] Fix compilation failure
  dlink-connectors/pom.xml
Labels: bug

#2137 refactor: optimization IGNORE_TABLE_NAMES struct
  dinky-admin/src/main/java/org/dinky/configure/MybatisPlusConfig.java
Labels: Optimization

#2145 [Optimize][Metrics]Optimize get flink metrics
  dinky-admin/src/main/java/org/dinky/configure/schedule/metrics/FlinkMetricsIndicator.java
Labels: Optimization

#2148 [Fix-2147] [metadata] Missing precision and scale when generating MySql DDL
  dlink-common/src/main/java/com/dlink/utils/SplitUtil.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/driver/MySqlDriver.java
Labels: bug

#2149 [Feature] added user token info
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-admin/src/main/java/org/dinky/data/dto/UserDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-web/src/app.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/KeyBoard/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/constant.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/index.tsx
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/services/data.d.ts
  dinky-web/src/types/User/data.d.ts
Labels: New Feature, Optimization

#2150 [Optimization] Distinguish between data source categories
  dinky-web/src/pages/RegCenter/DataSource/components/constants.ts
Labels: Optimization

#2156 mssql tinyint Type conversion error
  dlink-metadata/dlink-metadata-sqlserver/src/main/java/com/dlink/metadata/convert/SqlServerTypeConvert.java
Labels: bug

#2157 [Fix] fix datasource bug
  dinky-web/public/database/clickhouse.png
  dinky-web/public/database/db.jpg
  dinky-web/public/database/doris.jpeg
  dinky-web/public/database/hive.png
  dinky-web/public/database/mysql.jpg
  dinky-web/public/database/oracle.jpg
  dinky-web/public/database/phoenix.png
  dinky-web/public/database/postgresql.jpg
  dinky-web/public/database/presto.png
  dinky-web/public/database/sqlserver.jpg
  dinky-web/public/database/starrocks.jpg
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/SchemaTree/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
Labels: bug
