Repository DataLinkDC/dinky, pull requests merged in 2023-10, with the labels that each got.

#2351 [Feature][Web]add dag select drawer
  dinky-web/src/components/FlinkDag/config.ts
  dinky-web/src/components/FlinkDag/index.tsx
Labels: New Feature

#2352 [Optimization][Web]formate code
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobErrorView/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
Labels: Optimization

#2353 fix devops's bug
  dinky-web/src/components/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/FlinkDag/component/DagPlanNode.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Home/DevOverView/ResourceView/index.tsx
Labels: bug

#2354 support show idle & busy
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/data/annotation/ConditionalOnListProperty.java
  dinky-admin/src/main/java/org/dinky/data/dto/ClusterConfigurationDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/JobDataDto.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/backpressure/FlinkJobNodeBackPressure.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/config/ExecutionConfig.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/config/FlinkJobConfigInfo.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/exceptions/FlinkJobExceptionsDetail.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/job/FlinkJobDetailInfo.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/job/FlinkJobPlan.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/job/FlinkJobPlanNode.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/job/FlinkJobPlanNodeInput.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/job/FlinkJobVertex.java
  dinky-admin/src/main/java/org/dinky/data/model/flink/watermark/FlinkJobNodeWaterMark.java
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/job/BuildConfiguration.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/utils/ExcelUtils.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkSender.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuSender.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatSender.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/AbstractSqlSinkBuilder.java
  dinky-common/src/main/java/org/dinky/utils/JsonUtils.java
  dinky-connectors/dinky-connector-pulsar-1.14/pom.xml
  dinky-connectors/dinky-connector-pulsar-1.14/src/main/java/org/dinky/connector/pulsar/PulsarSinkFunction.java
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
  dinky-core/src/main/java/org/dinky/data/constant/FlinkRestAPIConstant.java
  dinky-core/src/test/java/org/dinky/core/FlinkRestAPITest.java
  dinky-gateway/src/main/java/org/dinky/gateway/model/FlinkClusterConfig.java
  dinky-metadata/dinky-metadata-clickhouse/src/test/java/org/dinky/metadata/ClickHouseTest.java
  dinky-web/src/components/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/FlinkDag/component/DagPlanNode.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/JobTags/StatusTag.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/FlinkTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/DevOps/constants.tsx
  dinky-web/src/pages/Home/JobOverView/JobOperatorGraph/index.tsx
  dinky-web/src/types/DevOps/data.d.ts
  pom.xml
Labels: Refactor

#2347 [Feature][Flink]add read checkpoint
  dinky-admin/src/main/java/org/dinky/controller/FlinkController.java
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/sse/SseEmitterUTF8.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/BaseCheckpointRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/CheckpointRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/CheckpointReadFactory.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/CheckpointReadInterface.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/SupportSplitSerializer.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/base/BaseTypeCheckpointRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/pojo/PojoTypeCheckpointRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/BaseCheckpointSource.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/CheckpointSource.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/CheckpointSourceRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/KafkaSource.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/MysqlCdcSource.java
  dinky-common/src/main/java/org/dinky/data/model/CheckPointReadTable.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-executor/src/main/java/org/dinky/parser/check/AddJarSqlParser.java
  dinky-flink/dinky-flink-1.13/pom.xml
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#2355 [Fix]Fix some bug
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/CheckpointRead.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/source/MysqlCdcSource.java
  dinky-web/src/components/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/JobTags/StatusTag.tsx
Labels: bug

#2358 [Feature][Web]add_project_position button
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
Labels: New Feature

#2362 [Optimization-2361][web] Optimize the display of job which unable to obtain the latest status
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-common/src/main/java/com/dlink/constant/MsgConstant.java
  dlink-web/src/pages/DevOps/JobInfo/BaseInfo/index.tsx
Labels: Optimization

#2360 [Optimization][admin] Add job reconnecting status and optimize job monitor
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-common/src/main/java/org/dinky/data/enums/JobStatus.java
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-web/src/components/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/JobTags/StatusTag.tsx
  dinky-web/src/pages/DevOps/constants.tsx
Labels: Optimization

#2367 [Fix][web] Popup box cannot be closed
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/components/AlertGroupForm/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/index.tsx
Labels: bug

#2371 [Feature-2370][connect] Add jdbc scan filter in flink-connector-jdbc-1.16
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/dialect/AbstractDialect.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/internal/options/JdbcReadOptions.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/table/JdbcConnectorOptions.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactory.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSource.java
  dlink-connectors/dlink-connector-jdbc-1.16/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunction.java
  dlink-core/pom.xml
  dlink-flink/dlink-flink-1.16/pom.xml
Labels: New Feature

#2365 [Fix][Flink SQL] Fix flink sql use ctas syntax
  dinky-admin/src/main/java/org/dinky/init/EnvInit.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: bug

#2369 refactor lineage
  dinky-admin/src/main/java/org/dinky/data/dto/JobDataDto.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/Rules/ExceptionRule.java
  dinky-common/pom.xml
  dinky-common/src/main/java/org/dinky/data/flink/backpressure/FlinkJobNodeBackPressure.java
  dinky-common/src/main/java/org/dinky/data/flink/config/ExecutionConfig.java
  dinky-common/src/main/java/org/dinky/data/flink/config/FlinkJobConfigInfo.java
  dinky-common/src/main/java/org/dinky/data/flink/exceptions/FlinkJobExceptionsDetail.java
  dinky-common/src/main/java/org/dinky/data/flink/job/FlinkJobDetailInfo.java
  dinky-common/src/main/java/org/dinky/data/flink/job/FlinkJobPlan.java
  dinky-common/src/main/java/org/dinky/data/flink/job/FlinkJobPlanNode.java
  dinky-common/src/main/java/org/dinky/data/flink/job/FlinkJobPlanNodeInput.java
  dinky-common/src/main/java/org/dinky/data/flink/job/FlinkJobVertex.java
  dinky-common/src/main/java/org/dinky/data/flink/watermark/FlinkJobNodeWaterMark.java
  dinky-web/package.json
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/components/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/LineageGraph/index.tsx
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Lineage/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CkDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLineage/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/DevOps/data.d.ts
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Refactor

#2372 refactor project tree layout
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
Labels: Refactor

#2375 [Optimization][admin] Modify the resource directory from partial to one-time acquisition
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/data/model/Resources.java
  dinky-admin/src/main/java/org/dinky/service/resource/ResourcesService.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/utils/function.tsx
Labels: Optimization

#2377 Remove statements
  dinky-admin/src/main/java/org/dinky/assertion/Assert.java
  dinky-admin/src/main/java/org/dinky/controller/StatementController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/model/Statement.java
  dinky-admin/src/main/java/org/dinky/mapper/StatementMapper.java
  dinky-admin/src/main/java/org/dinky/service/StatementService.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StatementServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-admin/src/main/resources/mapper/StatementMapper.xml
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
Labels: Optimization

#2379 [Optimization][admin] Mark some unused methods with @Deprecated and add some methods without annotations
  dinky-admin/src/main/java/org/dinky/controller/AlertGroupController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleMenuController.java
  dinky-admin/src/main/java/org/dinky/controller/SysConfigController.java
  dinky-admin/src/main/java/org/dinky/service/AlertGroupService.java
  dinky-admin/src/main/java/org/dinky/service/AlertHistoryService.java
  dinky-admin/src/main/java/org/dinky/service/CatalogueService.java
  dinky-admin/src/main/java/org/dinky/service/ClusterConfigurationService.java
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/GitProjectService.java
  dinky-admin/src/main/java/org/dinky/service/HistoryService.java
  dinky-admin/src/main/java/org/dinky/service/JarService.java
  dinky-admin/src/main/java/org/dinky/service/JobInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/LdapService.java
  dinky-admin/src/main/java/org/dinky/service/LoginLogService.java
  dinky-admin/src/main/java/org/dinky/service/MenuService.java
  dinky-admin/src/main/java/org/dinky/service/MonitorService.java
  dinky-admin/src/main/java/org/dinky/service/PrintTableService.java
  dinky-admin/src/main/java/org/dinky/service/RoleMenuService.java
  dinky-admin/src/main/java/org/dinky/service/RoleService.java
  dinky-admin/src/main/java/org/dinky/service/RowPermissionsService.java
  dinky-admin/src/main/java/org/dinky/service/SavepointsService.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/SysConfigService.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/TaskVersionService.java
  dinky-admin/src/main/java/org/dinky/service/TokenService.java
  dinky-admin/src/main/java/org/dinky/service/UDFTemplateService.java
  dinky-admin/src/main/java/org/dinky/service/UserRoleService.java
  dinky-admin/src/main/java/org/dinky/service/UserService.java
  dinky-admin/src/main/java/org/dinky/service/resource/ResourcesService.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProcessClient.java
Labels: Refactor

#2382 [Feature-2381][udf] AGGTABLE supports udtaf in Flink 1.16
  dlink-executor/pom.xml
  dlink-executor/src/main/java/com/dlink/trans/ddl/AggTable.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateAggTableOperation.java
  dlink-executor/src/test/java/com/dlink/trans/ddl/CreateAggTableOperationTest.java
Labels: New Feature

#2383 Refactor: some code
  dinky-executor/src/main/java/org/dinky/trans/ddl/CreateTemporalTableFunctionOperation.java
  dinky-web/src/components/CallBackButton/LoadingBtn.tsx
  dinky-web/src/components/FlinkDag/functions.tsx
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsFilter/MetricsConfigTab.tsx
  dinky-web/src/services/endpoints.tsx
  dlink-web/src/pages/DevOps/JobInfo/Version/VersionList/index.tsx
Labels: Refactor

#2387 Optimize datastudio
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/DiffModal.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/constants.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.less
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/services/endpoints.tsx
Labels: Refactor

#2386 [Refactor][Web]Add catalog
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/TableEnvironmentInstance.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/utils/FlinkTableMetadataUtil.java
  dinky-common/src/main/java/org/dinky/data/enums/ColumnType.java
  dinky-common/src/main/java/org/dinky/data/model/FlinkColumn.java
  dinky-web/pom.xml
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/data.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/ColumnInfo/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Refactor

#2389 [Optimize][Flink]optimize flink mission cancel
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/test/java/org/dinky/core/FlinkRestAPITest.java
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/DiffModal.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#2393 [Optimize][Web]optimize-same-web-code
  dinky-admin/src/main/java/org/dinky/data/dto/JobDataDto.java
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/function.tsx
  dinky-web/src/pages/RegCenter/Cluster/constants.ts
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/service.tsx
Labels: Optimization

#2391 [Refactor ][admin]Refactor process
  dinky-admin/src/main/java/org/dinky/aop/LogAspect.java
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/configure/schedule/metrics/GatherSysIndicator.java
  dinky-admin/src/main/java/org/dinky/context/BaseSseContext.java
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ProcessServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/sse/LogSseAppender.java
  dinky-admin/src/main/resources/log4j2.xml
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/utils/LogUtil.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/sqllineage/LineageBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/test/java/org/dinky/core/JobManagerTest.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/PythonFunction.java
  dinky-function/src/main/java/org/dinky/function/compiler/ScalaCompiler.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetsOperatorGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubetnetsApplicationOperatorGateway.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/driver/DorisDriver.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
  dinky-process/src/main/java/org/dinky/process/annotations/ExecuteProcess.java
  dinky-process/src/main/java/org/dinky/process/annotations/ProcessId.java
  dinky-process/src/main/java/org/dinky/process/annotations/ProcessStep.java
  dinky-process/src/main/java/org/dinky/process/context/ProcessContextHolder.java
  dinky-process/src/main/java/org/dinky/process/enums/ProcessStepType.java
  dinky-process/src/main/java/org/dinky/process/exception/DinkyException.java
  dinky-process/src/main/java/org/dinky/process/exception/ExcuteException.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessEntity.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessStep.java
  dinky-web/src/pages/DataStudio/BottomContainer/Console/service.tsx
Labels: Refactor

#2397 [Fix][Admin]fix cache bug
  dinky-admin/src/main/java/org/dinky/data/model/Task.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: bug

#2398 [Optimize][Web]fix resource && resource config
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/data/dto/ResourcesDTO.java
  dinky-admin/src/main/java/org/dinky/data/exception/BusException.java
  dinky-admin/src/main/java/org/dinky/service/resource/ResourcesService.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/FileShow/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/function.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourcesUploadModal/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/constants.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/ResourcesConfig/index.tsx
  dinky-web/src/types/RegCenter/data.d.ts
  dinky-web/src/types/RegCenter/state.d.ts
Labels: bug, Optimization

#2395 [Optimize][Flink]Add Flink Table global variable
  dinky-executor/src/main/java/org/dinky/constant/FlinkSQLConstant.java
  dinky-executor/src/main/java/org/dinky/executor/VariableManager.java
Labels: Optimization

#2400 [Optimize][Web]add_common_sql_config
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/CommonSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/function.tsx
Labels: Optimization

#2401 Fix resource delete bug
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/CommonSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/function.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileShow/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/constants.tsx
Labels: bug

#2404 [Fix-2392][metadata] Fix listColumnsSortByPK infinite recursion
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/driver/DorisDriver.java
  dlink-metadata/dlink-metadata-starrocks/src/main/java/com/dlink/metadata/driver/StarRocksDriver.java
Labels: bug

#2403 [Fix][Flink]Fix local model bug and FlinkSql task type selected by default
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-executor/pom.xml
  dinky-executor/src/main/java/org/dinky/executor/ExecutorConfig.java
  dinky-executor/src/main/java/org/dinky/executor/ExecutorFactory.java
  dinky-executor/src/main/java/org/dinky/executor/LocalStreamExecutor.java
  dinky-executor/src/test/java/org/dinky/interceptor/FlinkInterceptorTest.java
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
Labels: bug

#2409 [Optimize ]optimize The Process
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-process/src/main/java/org/dinky/process/enums/ProcessStepType.java
Labels: Optimization

#2418 [optimization][docs] added responsive layout
  docs/README.md
  docs/src/pages/index.js
  docs/src/pages/index.module.css
Labels: Doc

#2419 [Bug][Admin]fix h2 alert sql err
  dinky-admin/src/main/resources/db/db-h2.sql
Labels: bug

#2420 [Optimize][Admin]Optimize the process
  dinky-admin/src/main/java/org/dinky/aop/ProcessAspect.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: Optimization

#2415 [Document-2414][doc] Add v0.7.5 download
  docs/docusaurus.config.js
  docs/download/dinky-0.7.5.md
  docs/download/download.md
Labels: Doc

#2416 feat: print table local address configure
  dinky-admin/src/main/java/org/dinky/service/impl/PrintTableServiceImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/constant/CustomerConfigureOptions.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/print_table/PrintStatementExplainer.java
  dinky-core/src/test/java/org/dinky/explainer/print_table/PrintStatementExplainerTest.java
  dinky-executor/src/main/java/org/dinky/connector/printnet/sink/PrintNetDynamicTableSinkFactory.java
  dinky-executor/src/main/java/org/dinky/connector/printnet/sink/PrintNetSinkFunction.java
  dinky-web/src/models/Sse.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/JobChart/JobChart.tsx
  dinky-web/src/pages/DevOps/constants.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
Labels: Optimization

#2424 [optimization][docs] update responsive layout
  docs/src/pages/index.js
  docs/src/pages/index.module.css
Labels: Doc

#2428 [Bug][web] datastudio editor height bug
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
Labels: bug

#2429 [Optimize][web]Add apache license header
  dinky-web/src/components/CallBackButton/LoadingBtn.tsx
  dinky-web/src/components/Front/Title.tsx
  dinky-web/src/components/JobTags/data.d.ts
  dinky-web/src/components/LineageGraph/index.tsx
  dinky-web/src/components/LineageGraph/lineage-dag-ext.tsx
  dinky-web/src/components/Scroll/ContentScroll/index.tsx
  dinky-web/src/components/Sidebar/MovableSidebar/index.tsx
  dinky-web/src/hooks/useAccess.tsx
  dinky-web/src/hooks/useService.tsx
  dinky-web/src/hooks/useThemeValue.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Lineage/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/function.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/FlinkGraph/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/data.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/service.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/service.tsx
  dinky-web/src/pages/DataStudio/data.d.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DevOps/JobDetail/JobLineage/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/FlinkTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/Metrics/Job/service.tsx
  dinky-web/src/pages/Metrics/service.tsx
  dinky-web/src/pages/RegCenter/DataSource/service.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/function.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourcesUploadModal/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/function.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/ResourcesConfig/index.tsx
  dinky-web/src/pages/SettingCenter/SystemLogs/TagInfo/LogList/LogsTree/function.tsx
  dinky-web/src/utils/hook/useLocalStorage.ts
  dinky-web/src/utils/modelUtils.ts
Labels: Optimization

#2441 refactor extra global variables
  dinky-executor/src/main/java/org/dinky/constant/FlinkSQLConstant.java
  dinky-executor/src/main/java/org/dinky/executor/VariableManager.java
  dinky-web/src/global.less
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/KeyBoard/constant.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/utils/function.tsx
Labels: Refactor

#2448 [Fix]fix_some_web_bug
  dinky-web/config/config.ts
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/languages/javalog/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/Explain/index.tsx
  dinky-web/src/utils/function.tsx
Labels: bug

#2449 [Feature-2447][studio] Add FlinkSQL and common SQL debug preview
  dinky-admin/src/main/java/org/dinky/controller/HistoryController.java
  dinky-admin/src/main/java/org/dinky/service/HistoryService.java
  dinky-admin/src/main/java/org/dinky/service/impl/HistoryServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/CommonSqlTask.java
  dinky-core/src/main/java/org/dinky/data/result/ResultPool.java
  dinky-web/package.json
  dinky-web/src/app.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#2451 [Feature][Web]support custom editor language height light
  dinky-web/config/config.ts
  dinky-web/package.json
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/languages/javalog/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/Explain/index.tsx
  dinky-web/src/utils/function.tsx
Labels: New Feature

#2455 [Fix]fix_jexl3_some_bug
  README.md
  pom.xml
Labels: bug

#2445 refactor admin's bean define
  dinky-admin/src/main/java/org/dinky/controller/AlertInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleMenuController.java
  dinky-admin/src/main/java/org/dinky/data/dto/AlertInstanceDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/AssignMenuToRoleDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/ClusterInstanceDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/DataBaseDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/MenuDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/RoleDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/RoleMenuDTO.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/AlertInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/ClusterInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/MenuService.java
  dinky-admin/src/main/java/org/dinky/service/RoleMenuService.java
  dinky-admin/src/main/java/org/dinky/service/RoleService.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/MenuServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/RoleMenuServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/RoleServiceImpl.java
Labels: Optimization

#2459 [Optimization][admin]Alert bug fix
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
Labels: Optimization

#2461 [Optimization-2460][studio] Optimize task preview result
  dinky-admin/src/main/java/org/dinky/data/dto/DebugDTO.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-executor/src/main/java/org/dinky/executor/VariableManager.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: Optimization

#2463 [Fix-2462] [studio] Fix refresh related content after renaming the task
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2464 [Fix][mvn]fix_version_bug
  dinky-admin/src/main/resources/application.yml
  dinky-admin/src/main/resources/banner.txt
Labels: bug

#2466 [Feature]Add json to sql tool
  dinky-admin/src/main/java/org/dinky/controller/ToolsController.java
  dinky-common/src/main/java/org/dinky/tools/JsonToSqlConvent.java
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/service.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: New Feature

#2457 [Optimize][Web]optimize_web_catalog
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
Labels: Optimization

#2467 fix project expand bug
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: bug

#2468 [Fix-2158][metadata] Fix column type convert in Doris and Oracle
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/constant/DorisConstant.java
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/convert/DorisTypeConvert.java
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/query/DorisQuery.java
  dlink-metadata/dlink-metadata-oracle/src/main/java/com/dlink/metadata/convert/OracleTypeConvert.java
Labels: bug
