Repository DataLinkDC/dinky, pull requests merged in 2023-08, with the labels that each got.

#2172 [Feature][Web]add_footer
  dinky-admin/src/main/java/org/dinky/controller/SseController.java
  dinky-admin/src/main/java/org/dinky/service/MonitorService.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Console/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/Explain/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
Labels: New Feature

#2181 [Optimization] Optimization right silder layout
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/FlinkGraph/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/KeyBoard/constant.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/KeyBoard/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/constant.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/ExecuteConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/constants.tsx
  dinky-web/src/pages/DataStudio/index.tsx
Labels: Optimization

#2182 [fix] fix some bug
  dinky-admin/src/main/resources/db/db-h2.sql
  dinky-web/src/pages/DataStudio/FooterContainer/JobRunningModal/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/model.ts
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
Labels: bug

#2185 [Feature][web] add result
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/function.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/service.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/ColumnInfo/Index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/utils/function.tsx
Labels: Refactor

#2187 [fix] fix sql bug
  dinky-admin/src/main/resources/db/db-h2.sql
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
Labels: bug

#2188 [Feature] change dinky-web for main
  .gitignore
  dinky-admin/pom.xml
  dinky-admin/src/main/resources/application.yml
  dinky-app/pom.xml
  dlink-web/pom.xml
Labels: New Feature

#2191 [Fix][Web] Fix web SSE problem
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-web/config/proxy.ts
  dinky-web/src/services/api.ts
Labels: bug, Optimization

#2193 [Feature] added return menu list
  dinky-admin/src/main/java/org/dinky/aop/LogAspect.java
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/data/constant/BaseConstant.java
  dinky-admin/src/main/java/org/dinky/data/dto/UserDTO.java
  dinky-admin/src/main/java/org/dinky/mapper/MenuMapper.java
  dinky-admin/src/main/java/org/dinky/mapper/RoleMenuMapper.java
  dinky-admin/src/main/java/org/dinky/service/MenuService.java
  dinky-admin/src/main/java/org/dinky/service/UserService.java
  dinky-admin/src/main/java/org/dinky/service/impl/MenuServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-admin/src/main/resources/mapper/MenuMapper.xml
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-web/src/app.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Menu/components/MenuForm/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/constants.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/function.tsx
  dinky-web/src/pages/Other/PersonCenter/OperationLogRecord/index.tsx
  dinky-web/src/services/data.d.ts
  dinky-web/src/types/RegCenter/data.d.ts
Labels: New Feature

#2199 [Optimization]modify some style
  dinky-web/src/pages/AuthCenter/Menu/function.tsx
Labels: Optimization

#2200 [Feature][Web] Menu permission control
  dinky-admin/src/main/resources/application-mysql.yml
  dinky-web/config/routes.ts
  dinky-web/src/access.ts
  dinky-web/src/app.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuForm/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuTree/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/index.tsx
  dinky-web/src/pages/Home/index.tsx
Labels: New Feature

#2207 [Refactor] Refactor Create root Folder
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Menu/components/MenuForm/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/constants.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/JobForm/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/types/Studio/data.d.ts
Labels: Refactor

#2206 [2176][fix] fix unknown jobid bug in version 0.7
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesApplicationGateway.java
Labels: bug

#2205 [FIX-2171] fix bug in new code
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
Labels: bug

#2209 fix one table hava two or more primary key
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java
Labels: bug

#2211 [Refactor] Refactor datastudio contextmenu
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/controller/UDFController.java
  dinky-admin/src/main/java/org/dinky/data/model/Catalogue.java
  dinky-admin/src/main/java/org/dinky/service/CatalogueService.java
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/resources/mapper/TaskMapper.xml
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-web/package.json
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/manifest.json
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/FolderModal/FolderForm/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/FolderModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/JobForm/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/constants.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/SavePoints/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/Studio/data.d.ts
  dinky-web/tests/setupTests.jsx
  dinky-web/types/cache/cache.json
  dinky-web/types/cache/login.cache.json
  dinky-web/types/cache/mock/login.mock.cache.js
  dinky-web/types/cache/mock/mock.cache.js
  dinky-web/types/index.d.ts
Labels: Refactor

#2222 [fix] fix menu bug
  .gitignore
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/service/RoleService.java
  dinky-admin/src/main/java/org/dinky/service/impl/RoleServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-web/pnpm-lock.yaml
  dinky-web/src/access.ts
  dinky-web/src/components/RightContextMenu/index.tsx
  dinky-web/src/components/TableTransfer/index.tsx
  dinky-web/src/hooks/useAccess.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Menu/components/MenuForm/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/function.tsx
  dinky-web/src/pages/AuthCenter/Role/components/AssignMenu/index.tsx
  dinky-web/src/pages/AuthCenter/Role/components/RoleProTable/index.tsx
  dinky-web/src/pages/AuthCenter/Role/components/RoleUserList/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantModalTransfer/TenantTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/RoleModalTransfer/RoleTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/UserProTable/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/services/data.d.ts
Labels: bug

#2229 [Refactor] refactor api doc
  dinky-admin/src/main/java/org/dinky/configure/Knife4jConfig.java
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertGroupController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertHistoryController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterConfigurationController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-admin/src/main/java/org/dinky/controller/DocumentController.java
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
  dinky-admin/src/main/java/org/dinky/controller/FileUploadController.java
  dinky-admin/src/main/java/org/dinky/controller/FlinkProxyController.java
  dinky-admin/src/main/java/org/dinky/controller/FragmentController.java
  dinky-admin/src/main/java/org/dinky/controller/GitController.java
  dinky-admin/src/main/java/org/dinky/controller/HistoryController.java
  dinky-admin/src/main/java/org/dinky/controller/HomeController.java
  dinky-admin/src/main/java/org/dinky/controller/JarController.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-admin/src/main/java/org/dinky/controller/LogController.java
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleMenuController.java
  dinky-admin/src/main/java/org/dinky/controller/RowPermissionsController.java
  dinky-admin/src/main/java/org/dinky/controller/SavePointsController.java
  dinky-admin/src/main/java/org/dinky/controller/SchedulerController.java
  dinky-admin/src/main/java/org/dinky/controller/SseController.java
  dinky-admin/src/main/java/org/dinky/controller/StatementController.java
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/controller/SysConfigController.java
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskVersionController.java
  dinky-admin/src/main/java/org/dinky/controller/TenantController.java
  dinky-admin/src/main/java/org/dinky/controller/UDFController.java
  dinky-admin/src/main/java/org/dinky/controller/UploadFileRecordController.java
  dinky-admin/src/main/java/org/dinky/controller/UserController.java
  dinky-admin/src/main/java/org/dinky/controller/WatchTableController.java
  dinky-admin/src/main/resources/application.properties
Labels: Refactor

#2233 Add vcs.xml for idea
  .gitignore
  .idea/vcs.xml
Labels: Optimization

#2239 fix sql bug
  dinky-admin/src/main/resources/db/db-h2.sql
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2242 fix-menu-added-bug
  dinky-web/src/pages/AuthCenter/Menu/components/MenuForm/index.tsx
Labels: bug

#2249 [fix][web] hotfix-some-import-interface-bug
  .github/workflows/issue-rebot.yml
  .gitmodules
  dinky-web/src/app.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/MetaData/service.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/ProjectForm/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/TemplateTable/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
  dinky-web/src/requestErrorConfig.ts
  dinky-web/src/services/BusinessCrud.ts
Labels: bug

#2213 [refactor]Watch to SSE
  dinky-admin/src/main/java/org/dinky/controller/WatchTableController.java
  dinky-admin/src/main/java/org/dinky/service/WatchTableService.java
  dinky-admin/src/main/java/org/dinky/service/impl/WatchTableServiceImpl.java
  dinky-admin/src/test/java/org/dinky/service/impl/WatchTableServiceImplTest.java
  dinky-web/src/app.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CheckpointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/SavePointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/ExceptionTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/TaskManagerLogsTab.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/ProjectForm/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/utils/messages.tsx
  dinky-web/src/utils/modals.tsx
  dlink-web/src/components/Studio/StudioMenu/index.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
Labels: Optimization, Refactor

#2259 optimized version lists
  dinky-admin/src/main/java/org/dinky/controller/TaskVersionController.java
  dinky-web/src/components/CallBackButton/PopconfirmDeleteBtn.tsx
  dinky-web/src/components/VersionList/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
  dinky-web/src/types/Studio/data.d.ts
Labels: Optimization

#2263 [Optimization-2262][core] Optimize the classloader of task that submit flink sql on yarn-application mode
  dlink-core/src/main/java/com/dlink/job/JobManager.java
  dlink-executor/src/main/java/com/dlink/trans/Operations.java
  dlink-executor/src/main/resources/META-INF/services/com.dlink.trans.Operation
Labels: Optimization

#2264 fix: typo and closealltab
  dinky-web/src/components/Modal/ErrorModalShow/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
Labels: bug

#2268 Internalization
  dinky-admin/src/main/java/org/dinky/aop/WebExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-admin/src/main/java/org/dinky/data/exception/AuthException.java
  dinky-admin/src/main/java/org/dinky/data/result/Result.java
  dinky-admin/src/main/java/org/dinky/interceptor/LocaleChangeInterceptor.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/LdapServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/LoginLogServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/I18nMsgUtils.java
  dinky-admin/src/main/resources/i18n/messages.properties
  dinky-admin/src/main/resources/i18n/messages_en_US.properties
  dinky-admin/src/main/resources/i18n/messages_zh_CN.properties
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/utils/ConvertEnumToInternalization.java
  dinky-common/src/main/java/org/dinky/utils/I18n.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#2271 modify some logical
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/enums/GatewayType.java
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/Other/PersonCenter/index.tsx
Labels: Optimization

#2281 feat: fix encode
  dinky-common/src/main/java/org/dinky/utils/I18n.java
Labels: bug

#2280 [Fix] [UDF] Fix UDF's submission to submission with Checkpoint failed
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-web/src/pages/DataStudio/HeaderContainer/Explain/index.tsx
Labels: bug

#2282 [fix]fix_flink_proxy
  dinky-admin/src/main/java/org/dinky/controller/FlinkProxyController.java
Labels: bug
