Repository DataLinkDC/dinky, pull requests merged in 2023-04, with the labels that each got.

#1811 refactor: sql type detection with regrex.
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
  dinky-executor/src/main/java/org/dinky/trans/Operations.java
  dinky-executor/src/test/java/org/dinky/parser/SqlTypeTest.java
Labels: refactor

#1812 [Fix][SqlSegment]修复SQL配置在特定场景下解析失败的问题
  dlink-executor/src/main/java/com/dlink/parser/SqlSegment.java
Labels: bug

#1829 [Fix-1784] [admin] Fix task is deleted but task instances and history are not deleted consecutively
  dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
Labels: bug

#1834 Replace int type with long type in the table process
  dinky-common/src/main/java/org/dinky/utils/SplitUtil.java
Labels: optimization

#1841 feat: add temporalTableFunction
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/ExtendedOperationExecutorWrapper.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-executor/src/main/java/org/dinky/executor/CustomExtendedOperationExecutorImpl.java
  dinky-executor/src/main/java/org/dinky/parser/CustomParserImpl.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
  dinky-executor/src/main/java/org/dinky/trans/CreateAggTableOperationNewParseStrategy.java
  dinky-executor/src/main/java/org/dinky/trans/CreateTemporalTableFunctionParseStrategy.java
  dinky-executor/src/main/java/org/dinky/trans/ExtendOperation.java
  dinky-executor/src/main/java/org/dinky/trans/ddl/CreateTemporalTableFunctionOperation.java
  dinky-executor/src/test/java/org/dinky/parser/SqlTypeTest.java
  dinky-executor/src/test/java/org/dinky/trans/CreateTemporalTableFunctionParseStrategyTest.java
Labels: new feature

#1853 [Optimization-1851][flink] Upgrade all versions of Flink to the latest version
  dlink-flink/dlink-flink-1.15/pom.xml
  dlink-flink/dlink-flink-1.16/pom.xml
Labels: optimization

#1854 [Feature-1774][flink] Support Apache Flink 1.17
  .github/workflows/backend.yaml
  dlink-app/dlink-app-1.17/pom.xml
  dlink-app/dlink-app-1.17/src/main/java/com/dlink/app/MainApp.java
  dlink-app/dlink-app-base/pom.xml
  dlink-app/pom.xml
  dlink-assembly/src/main/assembly/package.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.17/pom.xml
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.17/src/main/java/com/dlink/flink/catalog/DlinkMysqlCatalog.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.17/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactory.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.17/src/main/java/com/dlink/flink/catalog/factory/DlinkMysqlCatalogFactoryOptions.java
  dlink-catalog/dlink-catalog-mysql/dlink-catalog-mysql-1.17/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dlink-catalog/dlink-catalog-mysql/pom.xml
  dlink-client/dlink-client-1.11/pom.xml
  dlink-client/dlink-client-1.12/pom.xml
  dlink-client/dlink-client-1.17/pom.xml
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/CDCBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/CDCBuilderFactory.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/SinkBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/CustomTableResultImpl.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/StaticResultProvider.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/TableSchemaField.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/utils/FlinkUtil.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/utils/ObjectConvertUtil.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/flink/table/delegation/Parser.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dlink-client/dlink-client-1.17/src/test/java/com/dlink/utils/LineageContextTest.java
  dlink-client/dlink-client-base/pom.xml
  dlink-client/pom.xml
  dlink-core/pom.xml
  dlink-executor/pom.xml
  dlink-extends/dependency-reduced-pom.xml
  dlink-extends/pom.xml
  dlink-flink/dlink-flink-1.17/pom.xml
  dlink-flink/pom.xml
  dlink-function/pom.xml
  dlink-gateway/pom.xml
  pom.xml
Labels: new feature

#1858 feat: multi tab to display watch table information.
  dlink-web/src/components/Studio/StudioConsole/StudioData/index.tsx
  dlink-web/src/components/Studio/StudioConsole/index.tsx
  dlink-web/src/utils/stompClientUtil.ts
Labels: new feature

#1859 fix: port pass error
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/test/java/org/dinky/job/JobConfigTest.java
Labels: bug

#1860 feat: add watch table comboBox select.
  dinky-admin/src/main/java/org/dinky/controller/StatementController.java
  dinky-admin/src/main/java/org/dinky/service/StatementService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StatementServiceImpl.java
  dinky-executor/src/main/java/org/dinky/trans/Operations.java
  dlink-web/src/components/Studio/StudioConsole/StudioData/index.tsx
  dlink-web/src/components/Studio/StudioEvent/DDL.ts
Labels: new feature

#1862 [Fix-1847][metadata] Fix postgreSql get DDL script error
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/convert/ITypeConvert.java
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/convert/PostgreSqlTypeConvert.java
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/driver/PostgreSqlDriver.java
  dlink-metadata/dlink-metadata-postgresql/src/main/java/com/dlink/metadata/query/PostgreSqlQuery.java
Labels: bug

#1865 [Fix-1847][metadata]fix: pgsql ddl error #1847
  dinky-metadata/dinky-metadata-postgresql/pom.xml
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/driver/PostgreSqlDriver.java
  dinky-metadata/dinky-metadata-postgresql/src/test/java/org/dinky/metadata/driver/PostgreSqlDriverTest.java
Labels: bug

#1870 feat: add exception sql prompt line number
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: new feature

#1872 feat: watch multi table one watch statemnt
  dinky-admin/src/main/java/org/dinky/service/impl/StatementServiceImpl.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/watchTable/WatchStatementExplainer.java
  dinky-core/src/test/java/org/dinky/explainer/watchTable/WatchStatementExplainerTest.java
Labels: new feature

#1864 oracle cdc整库同步到 iceberg #1850
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
Labels: bug

#1875 Update MySqlDriver.java
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/driver/MySqlDriver.java
Labels: bug

#1879 fix:ObjectConvertUtil类中的强转String异常
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/utils/ObjectConvertUtil.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/utils/ObjectConvertUtil.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/utils/ObjectConvertUtil.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/utils/ObjectConvertUtil.java
Labels: bug

#1882 fix sql annotations replace bug
  dinky-admin/src/test/java/org/dinky/utils/SqlUtilTest.java
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
Labels: bug

#1888 [Fix-1887] [admin] Fix DolphinScheduler can not generate task code in createTaskDefinition
  dlink-admin/src/main/java/com/dlink/controller/SchedulerController.java
Labels: bug

#1889 feat: websocket standalone log file and not print on console
  dinky-admin/src/main/resources/log4j2.xml
Labels: new feature

#1894 Add Global err check
  dinky-admin/src/main/java/org/dinky/common/result/Result.java
  dinky-web/src/locales/en-US/request.ts
  dinky-web/src/locales/zh-CN/request.ts
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: optimization

#1896 feat: compatiable office create function sql syntax, and fix some bug
  dinky-admin/src/main/java/org/dinky/aop/UdfClassLoaderAspect.java
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-function/src/test/java/org/dinky/function/util/UDFUtilTest.java
  docs/docs/administrator_guide/udf_develop/how_to/Python.md
  script/sql/dinky.sql
Labels: new feature

#1909 FIXBUG:修复mysql自动生成DDL语句时，没有数据类型的问题
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/driver/MySqlDriver.java
Labels: bug

#1908 refactor: refact UDF
  dinky-admin/src/main/java/org/dinky/utils/UDFUtils.java
  dinky-function/src/main/java/org/dinky/function/pool/UdfCodePool.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
Labels: refactor

#1905 feat: add docker compose config
  .github/workflows/docker_build.yaml
  docker-compose.yaml
  docker/.env
  docker/DockerfileDinkyFlink
  docker/DockerfileMysql
  docker/DockerfileWeb
  docker/app/Dockerfile
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  docker/mysql/Dockerfile
  docker/server/Dockerfile
  docs/docs/deploy_guide/docker_deploy.md
  script/bin/auto.sh
Labels: new feature
