Repository DataLinkDC/dinky, pull requests merged in 2023-05, with the labels that each got.

#1921 [Document-1920][doc] Add 0.7.3 docs
  .github/ISSUE_TEMPLATE/bug-report.yml
  dlink-web/src/pages/RegistrationCenter/DataBase/components/DBForm.tsx
  docs/docs/data_integration_guide/cdcsource_statements.md
  docs/docs/flink_sql_development_guide/expand_statements/create_temporal_function.md
  docs/download/dinky-0.7.3.md
  docs/download/download.md
Labels: documentation

#1919 refactor: pom.xml
  .github/workflows/backend.yaml
  dinky-admin/pom.xml
  dinky-app/dinky-app-1.12/pom.xml
  dinky-app/dinky-app-1.13/pom.xml
  dinky-app/dinky-app-1.14/pom.xml
  dinky-app/dinky-app-1.15/pom.xml
  dinky-app/dinky-app-1.16/pom.xml
  dinky-app/dinky-app-base/pom.xml
  dinky-app/pom.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.13/pom.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.14/pom.xml
  dinky-catalog/dinky-catalog-mysql/pom.xml
  dinky-catalog/pom.xml
  dinky-client/dinky-client-1.12/pom.xml
  dinky-client/dinky-client-1.13/pom.xml
  dinky-client/dinky-client-1.14/pom.xml
  dinky-client/dinky-client-1.15/pom.xml
  dinky-client/dinky-client-1.16/pom.xml
  dinky-client/dinky-client-base/pom.xml
  dinky-client/pom.xml
  dinky-common/pom.xml
  dinky-core/pom.xml
  dinky-executor/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/pom.xml
  dinky-function/pom.xml
  dinky-function/src/main/java/org/dinky/function/compiler/CustomStringJavaCompiler.java
  dinky-gateway/pom.xml
  dinky-metadata/dinky-metadata-base/pom.xml
  dinky-metadata/dinky-metadata-mysql/pom.xml
  dinky-process/pom.xml
  pom.xml
Labels: refactor

#1933 [Feature-1932][admin] flink1.15 CDCSOURCE add pg2sr
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/CDCBuilderFactory.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/SinkBuilderFactory.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/postgres/PostgresCDCBuilder.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/starrocks/StarrocksSinkBuilder.java
  dinky-flink/dinky-flink-1.15/pom.xml
Labels: new feature

#1938 [Fix-1936][Client]: cdcsource convert value error
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
Labels: bug

#1940 [Fix-1939][Client] cdcsource task set checkpoint invalid
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
Labels: bug

#1943 refactor: rename not-all to flink-single-version
  .github/workflows/backend.yaml
  dinky-app/dinky-app-base/pom.xml
  dinky-app/pom.xml
  dinky-catalog/dinky-catalog-mysql/pom.xml
  dinky-client/dinky-client-base/pom.xml
  dinky-client/pom.xml
  dinky-core/pom.xml
  dinky-flink/pom.xml
  pom.xml
Labels: refactor

#1944 [Feature-1930][dlink-client] Analyze custom functions from Flink SQL
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/utils/FunctionVisitor.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.14/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dlink-client/dlink-client-1.14/src/main/java/org/apache/flink/table/delegation/Parser.java
  dlink-client/dlink-client-1.14/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dlink-client/dlink-client-1.14/src/test/java/com/dlink/utils/LineageContextTest.java
  dlink-client/dlink-client-1.14/src/test/java/com/dlink/utils/MySuffixFunction.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/utils/FunctionVisitor.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.15/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dlink-client/dlink-client-1.15/src/main/java/org/apache/flink/table/delegation/Parser.java
  dlink-client/dlink-client-1.15/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dlink-client/dlink-client-1.15/src/test/java/com/dlink/utils/LineageContextTest.java
  dlink-client/dlink-client-1.15/src/test/java/com/dlink/utils/MySuffixFunction.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/utils/FunctionVisitor.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.16/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dlink-client/dlink-client-1.16/src/main/java/org/apache/flink/table/delegation/Parser.java
  dlink-client/dlink-client-1.16/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dlink-client/dlink-client-1.16/src/test/java/com/dlink/utils/LineageContextTest.java
  dlink-client/dlink-client-1.16/src/test/java/com/dlink/utils/MySuffixFunction.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/utils/FunctionVisitor.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/utils/LineageContext.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/flink/table/delegation/Parser.java
  dlink-client/dlink-client-1.17/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dlink-client/dlink-client-1.17/src/test/java/com/dlink/utils/LineageContextTest.java
  dlink-client/dlink-client-1.17/src/test/java/com/dlink/utils/MySuffixFunction.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/model/FunctionResult.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/model/LineageRel.java
Labels: new feature

#1945 [Fix-1916][*] Correct typos jackjson into jackson
  .gitignore
  dlink-web/src/components/Studio/StudioConsole/StudioData/index.tsx
  dlink-web/src/pages/Welcome.tsx
  docs/download/dinky-0.6.7.md
  pom.xml
Labels: refactor

#1927 feat: add official `add jar` sql syntax, and rename custom `add jar` to `add customJar`
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
  dinky-executor/src/main/java/org/dinky/parser/check/AddJarSqlParser.java
  dinky-executor/src/main/java/org/dinky/trans/ddl/AddJarOperation.java
  dinky-executor/src/test/java/org/dinky/parser/SqlTypeTest.java
  dinky-function/src/main/java/org/dinky/function/pool/UdfCodePool.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
Labels: new feature

#1948 Add error show modal
  dinky-web/src/components/Modal/ErrorModalShow/index.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/utils/messages.tsx
  dinky-web/src/utils/modals.tsx
Labels: refactor

#1954 [Fix][SqlSegment]修复SQL配置在特定场景下解析失败的问题 (#1812)
  dinky-executor/src/main/java/org/dinky/parser/SqlSegment.java
Labels: bug

#1955 feat: add flink-1.17 support
  .github/workflows/backend.yaml
  .github/workflows/docker_build.yaml
  dinky-app/dinky-app-1.17/pom.xml
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/pom.xml
  dinky-app/pom.xml
  dinky-assembly/src/main/assembly/package.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.17/pom.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.17/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.17/src/main/java/org/dinky/flink/catalog/factory/DinkyMysqlCatalogFactory.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.17/src/main/java/org/dinky/flink/catalog/factory/DinkyMysqlCatalogFactoryOptions.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.17/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dinky-catalog/dinky-catalog-mysql/pom.xml
  dinky-client/dinky-client-1.17/pom.xml
  dinky-client/dinky-client-1.17/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/AbstractCDCBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/CDCBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/CDCBuilderFactory.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/SinkBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/SinkBuilderFactory.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableResultImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/ExtendedOperationExecutorWrapper.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/ExtendedParser.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/ParserWrapper.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/StaticResultProvider.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/TableSchemaField.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/ObjectConvertUtil.java
  dinky-client/dinky-client-base/pom.xml
  dinky-client/pom.xml
  dinky-core/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/pom.xml
  pom.xml
Labels: new feature

#1960 Fix #1958 (When PK do not declare at the table head, data misalignmen…
  dlink-executor/src/main/java/com/dlink/executor/Executor.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/driver/DorisDriver.java
  dlink-metadata/dlink-metadata-starrocks/src/main/java/com/dlink/metadata/driver/StarRocksDriver.java
Labels: bug

#1970 [Refactor][web] refactor process table list
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-admin/src/main/java/org/dinky/service/ProcessService.java
  dinky-web/config/routes.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/SubStepsTable/ShowLog/index.tsx
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/SubStepsTable/index.tsx
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/constants.tsx
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/function.tsx
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/index.tsx
  dinky-web/src/pages/SettingCenter/Process/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: refactor

#1980 [Feature][web] added home routes
  dinky-web/config/routes.ts
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
  dinky-web/src/pages/Home/index.tsx
Labels: new feature

#1990 add devops page
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-web/config/routes.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/.ignore
  dinky-web/src/pages/DevOps/JobList/compents/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/constants.tsx
  dinky-web/src/pages/DevOps/JobList/function.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/DevOps/data.d.ts
  dinky-web/src/utils/function.tsx
Labels: new feature

#1992 [Refactor][web] refactor cluster instance
  dinky-admin/src/main/java/org/dinky/controller/ClusterController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/mapper/ClusterConfigurationMapper.java
  dinky-admin/src/main/java/org/dinky/mapper/ClusterInstanceMapper.java
  dinky-admin/src/main/java/org/dinky/mapper/ClusterMapper.java
  dinky-admin/src/main/java/org/dinky/service/ClusterInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/i18n/messages.properties
  dinky-admin/src/main/resources/i18n/messages_en_US.properties
  dinky-admin/src/main/resources/i18n/messages_zh_CN.properties
  dinky-admin/src/main/resources/mapper/ClusterInstanceMapper.xml
  dinky-web/config/routes.ts
  dinky-web/src/components/Icons/CustomIcons.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/InstanceForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/function.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/index.tsx
  dinky-web/src/services/constants.tsx
  dlink-web/src/pages/RegistrationCenter/ClusterManage/Cluster/index.tsx
Labels: refactor

#1994 [feat][database] add h2&pgsql
  dinky-admin/pom.xml
  dinky-admin/src/main/resources/application-h2.yml
  dinky-admin/src/main/resources/application-mysql.yml
  dinky-admin/src/main/resources/application-pgsql.yml
  dinky-admin/src/main/resources/application.yml
  dinky-admin/src/main/resources/db/db-h2.sql
  script/sql/dinky-pg.sql
  script/sql/dinky.sql
Labels: new feature
