Repository DataLinkDC/dinky, pull requests merged in 2023-09, with the labels that each got.

#2285 [Optimization-2284][web] Optimize dinky web and fix some bugs
  dinky-admin/src/main/java/org/dinky/data/model/TaskExtConfig.java
  dinky-web/src/app.tsx
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/Home/DevOverView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobErrorView/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
  dinky-web/src/pages/Other/Login/LoginForm/MainWithStyle/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/index.tsx
  dinky-web/src/pages/RegCenter/Resource/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/index.tsx
Labels: Optimization

#2299 Fix warning
  dinky-web/config/config.ts
  dinky-web/src/components/RightContextMenu/index.tsx
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Role/components/RoleModalForm/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantModalTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/PasswordModal/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/RoleModalTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/UserModalForm/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/JobRunningModal/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/Other/Login/ChooseModal/index.tsx
  dinky-web/src/pages/Other/PersonCenter/OperationLogRecord/ResultShow/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/index.tsx
  dinky-web/src/pages/RegCenter/GlobalVar/components/GlobalVarModal/index.tsx
  dinky-web/src/pages/SettingCenter/Process/components/ProcessList/SubStepsTable/ShowLog/index.tsx
Labels: bug

#2302 [Feature-1621][`docs`]k8s install tutorial docs
  docs/versioned_docs/version-0.7/k8s_guide/dinky_k8s_quick_install.md
Labels: Doc

#2304 [Document-2303][doc] Add 0.7.4 download link
  docs/docusaurus.config.js
  docs/download/dinky-0.7.4.md
  docs/download/download.md
  docs/src/pages/index.js
  docs/versioned_docs/version-0.7/k8s_guide/dinky_k8s_quick_install.md
Labels: Doc

#2306 append k8s change flink version tutorial and k8s tips
  docs/versioned_docs/version-0.7/k8s_guide/dinky_k8s_quick_install.md
Labels: Doc, Optimization

#2308 [Fix][web] fix role added bug
  dinky-web/src/pages/AuthCenter/Role/components/RoleProTable/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenList/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
Labels: bug

#2312 Refactor alert template
  dinky-admin/src/main/java/org/dinky/configure/schedule/Alert/JobAlerts.java
  dinky-admin/src/main/java/org/dinky/service/impl/AlertInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/HttpUtils.java
  dinky-admin/src/main/resources/mapper/AlertRulesMapper.xml
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/AbstractAlert.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/AlertBaseConstant.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/Rules/CheckpointsRule.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkAlert.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkSender.java
  dinky-alert/dinky-alert-dingtalk/src/main/resources/DingTalk.ftl
  dinky-alert/dinky-alert-dingtalk/src/test/java/org/dinky/alert/dingtalk/DingTalkTest.java
  dinky-alert/dinky-alert-email/pom.xml
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/EmailAlert.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/EmailConstants.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/EmailSender.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/template/DefaultHTMLTemplate.java
  dinky-alert/dinky-alert-email/src/main/resources/Email.ftl
  dinky-alert/dinky-alert-email/src/test/java/org/dinky/alert/email/EmailSenderTest.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuAlert.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuConstants.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuSender.java
  dinky-alert/dinky-alert-feishu/src/main/resources/FeiShu.ftl
  dinky-alert/dinky-alert-feishu/src/test/java/org/dinky/alert/feishu/FeiShuSenderTest.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatAlert.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatConstants.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatSender.java
  dinky-alert/dinky-alert-wechat/src/main/resources/WeChat-app.ftl
  dinky-alert/dinky-alert-wechat/src/main/resources/WeChat-wechat.ftl
  dinky-alert/dinky-alert-wechat/src/test/java/org/dinky/alert/wechat/WeChatSenderTest.java
  dinky-common/pom.xml
  dinky-common/src/main/java/org/dinky/data/model/ProxyConfig.java
  dinky-common/src/main/java/org/dinky/utils/HttpUtils.java
  dinky-common/src/main/java/org/dinky/utils/TimeUtil.java
  dinky-web/src/pages/AuthCenter/Role/components/RoleProTable/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenList/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/DingTalk/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Email/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/FeiShu/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/WeChat/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  pom.xml
  script/sql/dinky-mysql.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Refactor

#2313 modify alert rule layout
  dinky-admin/src/main/java/org/dinky/configure/schedule/Alert/JobAlerts.java
  dinky-admin/src/main/java/org/dinky/controller/AlertRuleController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertTemplateConteroller.java
  dinky-admin/src/main/java/org/dinky/data/model/AlertRule.java
  dinky-admin/src/main/java/org/dinky/data/model/AlertTemplate.java
  dinky-admin/src/main/java/org/dinky/data/options/AlertRuleOptions.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkAlert.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkConstants.java
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/DingTalkSender.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/EmailAlert.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/EmailConstants.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuAlert.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuConstants.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/FeiShuSender.java
  dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsSender.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatAlert.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatConstants.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatSender.java
  dinky-web/package.json
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/constants.ts
  dinky-web/src/pages/SettingCenter/AlertRule/function.ts
Labels: Optimization

#2316 Disable the monitoring configuration when the task stops
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsFilter/MetricsConfigForm.tsx
Labels: Optimization

#2315 migrated global config i81n to the back end
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/Configuration.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/ResourcesConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: Optimization

#2319 fix i81n
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
Labels: Optimization

#2321 [Fix-2320] [web] Fix expanding all but only the root directory
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/index.tsx
Labels: bug

#2330 [Feature] [Flink] support_add_jar_other_url
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/resource/BaseResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/HdfsResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/OssResourceManager.java
  dinky-admin/src/main/java/org/dinky/url/RsURLConnection.java
  dinky-admin/src/main/java/org/dinky/url/RsURLStreamHandler.java
  dinky-admin/src/main/java/org/dinky/url/RsURLStreamHandlerFactory.java
  dinky-common/src/main/java/org/dinky/utils/URLUtils.java
  dinky-executor/src/main/java/org/dinky/parser/check/AddJarSqlParser.java
Labels: New Feature

#2327 fix: Adjust the http request time to job manager
  dinky-common/src/main/java/org/dinky/data/constant/NetConstant.java
Labels: Optimization

#2324 refactor JobInstance refesh
  dinky-admin/src/main/java/org/dinky/controller/AlertRuleController.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/data/dto/JobDataDto.java
  dinky-admin/src/main/java/org/dinky/data/model/JobHistory.java
  dinky-admin/src/main/java/org/dinky/data/model/JobInfoDetail.java
  dinky-admin/src/main/java/org/dinky/data/model/JobInstance.java
  dinky-admin/src/main/java/org/dinky/data/options/AlertRuleOptions.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefeshHandler.java
  dinky-admin/src/main/java/org/dinky/service/JobHistoryService.java
  dinky-admin/src/main/java/org/dinky/service/JobInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobHistoryServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/Rules/ExceptionRule.java
  dinky-common/src/main/java/org/dinky/data/enums/JobStatus.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/utils/JSONUtil.java
  dinky-common/src/main/java/org/dinky/utils/TimeUtil.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-core/src/main/java/org/dinky/data/constant/FlinkRestResultConstant.java
  dinky-daemon/src/main/java/org/dinky/daemon/constant/FlinkTaskConstant.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskQueue.java
  dinky-daemon/src/main/java/org/dinky/daemon/entity/TaskWorker.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonFactory.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonTask.java
  dinky-daemon/src/main/java/org/dinky/daemon/task/DaemonTaskConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/exception/NotSupportGetStatusException.java
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CheckpointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CkDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/ExceptionTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsFilter/MetricsConfigForm.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsFilter/MetricsConfigTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/FlinkTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
  dinky-web/src/types/DevOps/data.d.ts
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Refactor

#2332 Refactor cluster model，Fix submit bug
  dinky-admin/src/main/java/org/dinky/controller/ClusterConfigurationController.java
  dinky-admin/src/main/java/org/dinky/data/dto/ClusterConfigurationDTO.java
  dinky-admin/src/main/java/org/dinky/data/model/ClusterConfiguration.java
  dinky-admin/src/main/java/org/dinky/data/model/JobInfoDetail.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefeshHandler.java
  dinky-admin/src/main/java/org/dinky/service/ClusterConfigurationService.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-gateway/src/main/java/org/dinky/gateway/model/FlinkClusterConfig.java
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/ApplicationConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/HighPriorityConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/YarnConfig/index.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: bug

#2337 [Feature][Web]Add flink dag
  dinky-web/package.json
  dinky-web/src/components/FlinkDag/component/DagNode.tsx
  dinky-web/src/components/FlinkDag/config.ts
  dinky-web/src/components/FlinkDag/functions.tsx
  dinky-web/src/components/FlinkDag/index.css
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/JobTags/StatusTag.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/types/DevOps/data.d.ts
Labels: New Feature

#2338 [Fix][Web] Fix DataStudio page bug
  .github/workflows/backend.yaml
  .github/workflows/docker_build.yaml
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/sse/SseEmitterUTF8.java
  dinky-web/package.json
  dinky-web/src/components/Sidebar/MovableSidebar/index.tsx
  dinky-web/src/global.less
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Editor/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/KeyBoard/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2335 [Document-2335][doc] Create Dinky_integrated_Flink_on_K8s.md and update dinky_k8s_quick_install.md
  docs/versioned_docs/version-0.7/k8s_guide/Dinky_integrated_Flink_on_K8s.md
  docs/versioned_docs/version-0.7/k8s_guide/dinky_k8s_quick_install.md
Labels: Doc

#2348 [Optimize][Web]add_clear_page_cache & add flink operator graph zoom
  dinky-web/src/components/FlinkDag/index.tsx
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobErrorView/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
Labels: Optimization
