Repository DataLinkDC/dinky, pull requests merged in 2023-02, with the labels that each got.

#1586 fix(sec): upgrade org.postgresql:postgresql to 42.5.1
  pom.xml
Labels: optimization

#1590 refactor: rename Submiter class
  dinky-app/dinky-app-1.12/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.13/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
Labels: optimization

#1594 [Feature-1593][cdc] Add CDCSOURCE support sink catalog
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/utils/FlinkBaseUtil.java
Labels: new feature

#1610 [Feature-1493][web] remove flink jar settings to flink cluster manage
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/RegistrationCenter/ClusterManage/ClusterConfiguration/components/ClusterConfigurationForm.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/components/flinkConfig.tsx
  dlink-web/src/pages/SettingCenter/FlinkSettings/model.ts
Labels: new feature, optimization, refactor

#1616 [Fix-1615] [api] Fix submit task error but return succeed when using dolphinscheduler
  dlink-admin/src/main/java/com/dlink/controller/APIController.java
  dlink-core/src/main/java/com/dlink/job/JobResult.java
Labels: bug

#1613 refactor: refactCustomTableEnvironmentImpl
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
Labels: refactor

#1625 [Fix-1624][admin] Fix lineage api in data explore module returns empty result
  dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
  dlink-web/src/components/Studio/StudioEdit/data.d.ts
Labels: bug

#1623 refactor: dinky process module
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTaskPool.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ProcessServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/pool/AbstractPool.java
  dinky-process/src/main/java/org/dinky/process/context/ProcessContextHolder.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessEntity.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessStatus.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessType.java
  dinky-process/src/main/java/org/dinky/process/pool/ConsolePool.java
  dinky-process/src/main/java/org/dinky/process/pool/ProcessPool.java
Labels: refactor

#1609 refactor: delete task alias
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskVersionController.java
  dinky-admin/src/main/java/org/dinky/db/handler/DateMetaObjectHandler.java
  dinky-admin/src/main/java/org/dinky/db/properties/MybatisPlusFillProperties.java
  dinky-admin/src/main/java/org/dinky/dto/CatalogueTaskDTO.java
  dinky-admin/src/main/java/org/dinky/dto/TaskVersionHistoryDTO.java
  dinky-admin/src/main/java/org/dinky/job/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/model/Cluster.java
  dinky-admin/src/main/java/org/dinky/model/History.java
  dinky-admin/src/main/java/org/dinky/model/Jar.java
  dinky-admin/src/main/java/org/dinky/model/Task.java
  dinky-admin/src/main/java/org/dinky/model/TaskVersion.java
  dinky-admin/src/main/java/org/dinky/service/CatalogueService.java
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/mapper/ClusterMapper.xml
  dinky-admin/src/main/resources/mapper/HistoryMapper.xml
  dinky-admin/src/main/resources/mapper/JarMapper.xml
  dinky-admin/src/main/resources/mapper/TaskMapper.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-doc/sql/dinky.sql
  dinky-doc/sql/upgrade/0.8.0_schema/mysql/dinky_ddl.sql
  dlink-web/src/components/Common/CodeShow.tsx
  dlink-web/src/components/Studio/StudioConsole/StudioHistory/data.d.ts
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/components/SessionForm.tsx
  dlink-web/src/components/Studio/StudioMenu/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioHistory/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioJarSetting/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioSetting/index.tsx
  dlink-web/src/components/Studio/StudioRightTool/StudioTaskInfo/index.tsx
  dlink-web/src/components/Studio/StudioTree/Function.ts
  dlink-web/src/components/Studio/StudioTree/components/SimpleTaskForm.tsx
  dlink-web/src/components/Studio/StudioTree/components/UpdateCatalogueForm.tsx
  dlink-web/src/components/Studio/StudioTree/components/UploadModal.tsx
  dlink-web/src/components/Studio/StudioTree/data.d.ts
  dlink-web/src/components/Studio/StudioTree/index.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/DataCenter/MetaData/index.tsx
  dlink-web/src/pages/DataStudio/model.ts
  dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
  dlink-web/src/pages/DevOps/JobInfo/Version/VersionList/index.tsx
  dlink-web/src/pages/DevOps/JobInstanceTable/index.tsx
  dlink-web/src/pages/DevOps/data.d.ts
  dlink-web/src/pages/RegistrationCenter/ClusterManage/Cluster/components/ClusterForm.tsx
  dlink-web/src/pages/RegistrationCenter/ClusterManage/Cluster/index.tsx
  dlink-web/src/pages/RegistrationCenter/ClusterManage/ClusterConfiguration/function.ts
  dlink-web/src/pages/RegistrationCenter/DataBase/index.tsx
  dlink-web/src/pages/RegistrationCenter/Jar/components/JarForm.tsx
  dlink-web/src/pages/RegistrationCenter/Jar/index.tsx
  dlink-web/src/pages/RegistrationCenter/data.d.ts
  dlink-web/src/pages/Task/components/UpdateForm.tsx
  dlink-web/src/pages/Task/data.d.ts
  dlink-web/src/pages/Task/index.tsx
Labels: refactor

#1632 [Optimization-1631][doc] Optimize auto.sh and remove useless files
  dlink-assembly/src/main/assembly/package.xml
  dlink-doc/bin/auto.sh
  dlink-doc/config/application.yml
  dlink-doc/doc/Dlink-0.3.2更新说明.md
  dlink-doc/doc/Dlink0.3.0重磅来袭.md
  dlink-doc/doc/DlinkOnYarn三种Flink执行方式的实践.md
  dlink-doc/doc/Dlink一款交互式FlinkSQL开发平台.md
  dlink-doc/doc/Dlink在Flink-mysql-cdc到Doris的实践.md
  dlink-doc/doc/Dlink实时计算平台——部署篇.md
  dlink-doc/doc/Dlink核心概念与实现原理详解.md
  dlink-doc/doc/Dlink读写Hive的实践.md
  dlink-doc/doc/FlinkAggTable在Dlink的应用.md
  dlink-doc/images/040/Dlink_principle.png
  dlink-doc/images/040/ca.png
  dlink-doc/images/040/cluster.png
  dlink-doc/images/040/clusterconfiguration.png
  dlink-doc/images/040/datashow.png
  dlink-doc/images/040/db.png
  dlink-doc/images/040/function.png
  dlink-doc/images/040/history.png
  dlink-doc/images/040/login.png
  dlink-doc/images/040/metadata.png
  dlink-doc/images/040/process.png
  dlink-doc/images/040/savepoint.png
  dlink-doc/images/040/selectpreview.png
  dlink-doc/images/040/session.png
  dlink-doc/images/040/sqlcheck.png
  dlink-doc/images/040/sqldev.png
  dlink-doc/images/040/sqlerror.png
  dlink-doc/images/040/welcome.png
  dlink-doc/images/050/050autocomplete.png
  dlink-doc/images/050/050ca.png
  dlink-doc/images/050/050changelog.png
  dlink-doc/images/050/050check.png
  dlink-doc/images/050/050cluster.png
  dlink-doc/images/050/050clusterconf.png
  dlink-doc/images/050/050export.png
  dlink-doc/images/050/050flinksqlstudio.png
  dlink-doc/images/050/050home.png
  dlink-doc/images/050/050jobplan.png
  dlink-doc/images/050/050line.png
  dlink-doc/images/050/050login.png
  dlink-doc/images/050/050metadata.png
  dlink-doc/images/050/050savepoint.png
  dlink-doc/images/050/050session.png
  dlink-doc/images/050/050table.png
  dlink-doc/images/060/charts.png
  dlink-doc/images/060/checksql.png
  dlink-doc/images/060/datamap.png
  dlink-doc/images/060/datasource.png
  dlink-doc/images/060/flinksqlstudio.png
  dlink-doc/images/060/jobinfo.png
  dlink-doc/images/060/jobplan.png
  dlink-doc/images/060/lineage.png
  dlink-doc/images/060/metadata.png
  dlink-doc/images/060/monitor.png
  dlink-doc/images/060/selectpreview.png
Labels: optimization

#1634 [Feature-1608][admin] Support get task lineage by taskid with openapi
  dlink-admin/src/main/java/com/dlink/controller/APIController.java
  dlink-admin/src/main/java/com/dlink/controller/StudioController.java
  dlink-admin/src/main/java/com/dlink/dto/StudioLineageDTO.java
  dlink-admin/src/main/java/com/dlink/service/StudioService.java
  dlink-admin/src/main/java/com/dlink/service/TaskService.java
  dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Labels: new feature

#1626 refactor: gatewary configure
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/AbstractGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/Gateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/ActionType.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/ClusterConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/ConfigPara.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/FlinkConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/GatewayConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/SavePointType.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesSessionGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/AbstractGatewayResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/GatewayResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/KubernetesResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/SavePointResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/YarnResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnPerJobGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnSessionGateway.java
Labels: refactor

#1635 [refactor][k8s cluster]K8s doc optimize and refactor code
  .github/workflows/backend.yaml
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/DinkyFlinkDockerfile
  dinky-common/pom.xml
  dinky-common/src/main/java/org/dinky/config/Docker.java
  dinky-common/src/main/java/org/dinky/model/FlinkClusterConfiguration.java
  dinky-common/src/main/java/org/dinky/utils/DockerClientUtils.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/RegistrationCenter/ClusterManage/ClusterConfiguration/conf.ts
  docs/docs/k8s_guide/dinky_k8s_quick_start.md
  docs/docs/k8s_guide/dinky_k8s_quick_start.mdx
  docs/docs/k8s_guide/remote_link_k8s.md
  docs/docusaurus.config.js
  pom.xml
Labels: refactor

#1645 [Optimization-957][*] Optimization test code replace System.out.println with logger.info
  dinky-core/src/test/java/org/dinky/core/FlinkRestAPITest.java
  dinky-core/src/test/java/org/dinky/core/FlinkSqlPlusTest.java
  dinky-core/src/test/java/org/dinky/core/JobManagerTest.java
  dinky-core/src/test/java/org/dinky/core/LineageTest.java
  dinky-metadata/dinky-metadata-clickhouse/src/test/java/org/dinky/metadata/ClickHouseTest.java
  dinky-metadata/dinky-metadata-doris/src/test/java/org/dinky/metadata/DorisTest.java
  dinky-metadata/dinky-metadata-hive/src/test/java/org/dinky/metadata/HiveTest.java
  dinky-metadata/dinky-metadata-mysql/src/test/java/org/dinky/metadata/MysqlTest.java
  dinky-metadata/dinky-metadata-oracle/src/test/java/org/dinky/metadata/OracleTest.java
  dinky-metadata/dinky-metadata-phoenix/src/test/java/org/dinky/metadata/PhoenixTest.java
  dinky-metadata/dinky-metadata-presto/src/test/java/org/dinky/PrestoTest.java
  dinky-metadata/dinky-metadata-sqlserver/src/test/java/org/dinky/metadata/SqlServerTest.java
Labels: refactor

#1649 fixed catalog cannot be deleted and alter
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.13/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.14/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.15/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.16/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
Labels: bug

#1653 [Fix-1652] [admin] Fix the task using the FlinkSQLEnv cannot obtain lineage
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Labels: bug

#1660 [Fix-1659][admin] 数据库信息修改后，更新catalog ddl
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: bug

#1663 [Fix-1662] [admin] OpenApi notLoginException
  dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
Labels: bug

#1667 [Optimization-1666][admin] Add job reconnecting status and optimize job monitor
  dlink-admin/src/main/java/com/dlink/job/FlinkJobTask.java
  dlink-admin/src/main/java/com/dlink/service/JobHistoryService.java
  dlink-admin/src/main/java/com/dlink/service/impl/JobHistoryServiceImpl.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-common/src/main/java/com/dlink/model/JobStatus.java
  dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnGateway.java
  dlink-web/src/components/Common/JobStatus.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
Labels: optimization

#1670 [Fix] [sql] Fix wrong Python type
  dlink-doc/sql/dinky.sql
  dlink-doc/sql/upgrade/0.7.0_schema/mysql/dinky_dml.sql
Labels: bug

#1673 [Fix-1672] [cdc] Fix failed to get metadata due to jdbc session timeout in CDCSOURCE
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
Labels: bug

#1675 [Optimization-1636][admin] Add web console error output when getting lineage exception
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-core/src/main/java/org/dinky/explainer/sqllineage/LineageBuilder.java
  dinky-process/src/main/java/org/dinky/process/model/ProcessType.java
Labels: optimization

#1683 [Optimization-1682][metadata] Optimize setting named tinyInt1isBit for mysql metadata
  dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/convert/ITypeConvert.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/convert/MySqlTypeConvert.java
Labels: optimization

#1684 [Fix-1638] [core] Fix dlink web could not correct display Boolean type data
  dlink-core/src/main/java/com/dlink/result/ResultRunnable.java
Labels: bug

#1685 [docs] 修改'数据集成指南'->'CDCSOURCE 整库同步'->'说明' : jar包位置
  docs/docs/data_integration_guide/cdcsource_statements.md
Labels: documentation

#1688 [Fix-1686][app] Fix ZipFile got wrong in K8s native app mode
  dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
Labels: bug

#1690 [Feature-1547][web] Flink Jar support alert
  dlink-web/src/components/Studio/StudioRightTool/StudioJarSetting/index.tsx
Labels: new feature
