Repository DataLinkDC/dinky, pull requests merged in 2023-06, with the labels that each got.

#2007 [Optimization-2006][web] Optimize alert group through dva effect
  dinky-cdc/dinky-cdc-plus/pom.xml
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/service.ts
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/model.ts
Labels: optimization

#2008 [Refactor][web] system settings web
  dinky-web/config/routes.ts
  dinky-web/src/components/Footer/index.tsx
  dinky-web/src/components/Icons/CustomIcons.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/JarShow/JarList/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectProTable/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/DSConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/EnvConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/FlinkConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/MavenConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: refactor

#1988 [Optimization][admin] modified some naming and logical sinking
  dinky-admin/src/main/java/org/dinky/Dinky.java
  dinky-admin/src/main/java/org/dinky/common/result/Result.java
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-admin/src/main/java/org/dinky/enums/Status.java
  dinky-admin/src/main/java/org/dinky/service/UserService.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  script/bin/auto.sh
Labels: refactor

#2009 [Feature][admin,web] support switching language and backend synchronization
  dinky-admin/src/main/java/org/dinky/interceptor/LocaleChangeInterceptor.java
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Other/Login/LangSwitch/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/utils/function.tsx
Labels: new feature, optimization

#2018 [Refactor][web] Re-request interface when switching tenants
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
Labels: optimization, refactor

#2024 [build] [update version] update_version & add_actuator
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/configure/CacheConfig.java
  dinky-admin/src/main/java/org/dinky/configure/Knife4jConfig.java
  dinky-admin/src/main/java/org/dinky/data/model/SysConfig.java
  dinky-admin/src/main/java/org/dinky/init/EnvInit.java
  dinky-admin/src/main/java/org/dinky/service/impl/SysConfigServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-admin/src/main/resources/application.properties
  dinky-admin/src/main/resources/application.yml
  dinky-scheduler/pom.xml
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  pom.xml
Labels: Optimization

#2038 Modify userlist page，add userType column
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/User/components/UserProTable/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/constants.tsx
  dinky-web/src/types/User/data.d.ts
Labels: New Feature

#2043 [Optimization][web] Optimization home page
  dinky-web/package.json
  dinky-web/src/components/CountFormatter/index.tsx
  dinky-web/src/components/Icons/HomeIcon.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Home/DevOverView/BatchStreamProportion/index.tsx
  dinky-web/src/pages/Home/DevOverView/DevHeatmap/index.tsx
  dinky-web/src/pages/Home/DevOverView/ResourceView/index.tsx
  dinky-web/src/pages/Home/DevOverView/TaskDialectRadar/index.tsx
  dinky-web/src/pages/Home/DevOverView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobErrorView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobFinishedView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobRecoveryView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobRunView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobStatusPie/index.tsx
  dinky-web/src/pages/Home/JobOverView/LoadScoreGauge/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
  dinky-web/src/pages/Home/constants.tsx
  dinky-web/src/utils/function.tsx
Labels: Optimization

#2045 Add the LDAP user list interface and the test connection interface
  dinky-admin/src/main/java/org/dinky/context/LdapContext.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-admin/src/main/java/org/dinky/service/LdapService.java
  dinky-admin/src/main/java/org/dinky/service/impl/LdapServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
Labels: New Feature

#2046 [doc fix] fix the link not valid
  README.md
  README_zh_CN.md
Labels: Doc

#2047 [Fix] fix_pg & sms_alert & SystemConfiguration
  dinky-admin/src/main/java/org/dinky/configure/MybatisPlusConfig.java
  dinky-admin/src/main/java/org/dinky/data/annotation/ConditionalOnListProperty.java
  dinky-admin/src/main/java/org/dinky/interceptor/PostgreSQLPrepareInterceptor.java
  dinky-admin/src/main/java/org/dinky/interceptor/PostgreSQLQueryInterceptor.java
  dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsSender.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  script/sql/dinky-pg.sql
  script/sql/upgrade/0.8.0_schema/mysql/dinky_ddl.sql
Labels: bug

#2048 [Feature][web] added metrics layout
  dinky-web/config/routes.ts
  dinky-web/src/components/Icons/MetricsIcon.tsx
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/GlobalFilter/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/constants.tsx
  dinky-web/src/pages/Metrics/Server/function.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
Labels: New Feature

#2050 LDAP is prohibited in conflict with the local user.
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
Labels: New Feature

#2053 Fixed user form display error
  dinky-web/src/pages/AuthCenter/User/components/UserModalForm/UserForm/index.tsx
Labels: bug

#2054 fix metrics function bug
  dinky-web/src/pages/Metrics/Server/constants.tsx
  dinky-web/src/pages/Metrics/Server/function.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
Labels: bug

#2055 refactor: metadata, a little adjustitive on code
  dinky-common/src/main/java/org/dinky/data/enums/ColumnType.java
  dinky-common/src/main/java/org/dinky/data/model/Table.java
  dinky-metadata/dinky-metadata-base/pom.xml
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/convert/AbstractTypeConvert.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/DriverPool.java
  dinky-metadata/dinky-metadata-base/src/test/java/org/dinky/metadata/driver/AbstractDriverTest.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/convert/ClickHouseTypeConvert.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/convert/DorisTypeConvert.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/convert/HiveTypeConvert.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/convert/MySqlTypeConvert.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
  dinky-metadata/dinky-metadata-mysql/src/test/java/org/dinky/metadata/driver/MySqlDriverTest.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/convert/OracleTypeConvert.java
  dinky-metadata/dinky-metadata-phoenix/src/main/java/org/dinky/metadata/convert/PhoenixTypeConvert.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/convert/SqlServerTypeConvert.java
  dinky-metadata/dinky-metadata-starrocks/src/main/java/org/dinky/metadata/convert/StarRocksTypeConvert.java
Labels: Refactor

#2056 [Feature] [monitor] add monitor & jmx
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/MetricConfig.java
  dinky-admin/src/main/java/org/dinky/configure/ThreadPoolConfig.java
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/data/annotation/GaugeM.java
  dinky-admin/src/main/java/org/dinky/data/metrics/BaseMetrics.java
  dinky-admin/src/main/java/org/dinky/data/metrics/Cpu.java
  dinky-admin/src/main/java/org/dinky/data/metrics/Jvm.java
  dinky-admin/src/main/java/org/dinky/data/metrics/Mem.java
  dinky-admin/src/main/java/org/dinky/data/metrics/MetricsTotal.java
  dinky-admin/src/main/java/org/dinky/data/vo/MetricsVO.java
  dinky-admin/src/main/java/org/dinky/init/EnvInit.java
  dinky-admin/src/main/java/org/dinky/service/MonitorService.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
  dinky-admin/src/main/resources/application-jmx.yml
  dinky-admin/src/main/resources/application.yml
  pom.xml
Labels: New Feature

#2057 [wip]Perfect ldap test login and test connection function with front end pages
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
  dinky-web/src/services/constants.tsx
Labels: Optimization

#2059 [Optimization][web] Optimization person page
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-web/src/pages/Other/PersonCenter/BaseInfo/index.tsx
  dinky-web/src/pages/Other/PersonCenter/index.tsx
Labels: Optimization

#2063 [Optimize] [web] Optimize Minitor front
  dinky-admin/src/main/java/org/dinky/configure/MetricConfig.java
  dinky-admin/src/main/java/org/dinky/data/metrics/Jvm.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/GlobalFilter/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/constants.tsx
  dinky-web/src/pages/Metrics/Server/data.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/services/constants.tsx
Labels: Optimization

#2064 [Optimize] [doc] 修正错别字
  docs/docs/deploy_guide/docker_deploy.md
Labels: Doc

#2065 [Optimize] [doc] optimize_doc
  README.md
  README_zh_CN.md
Labels: Doc

#2067 [Feature][admin,web]support some home overview
  dinky-admin/src/main/java/org/dinky/controller/HomeController.java
  dinky-admin/src/main/java/org/dinky/data/model/HomeResource.java
  dinky-admin/src/main/java/org/dinky/data/model/JobModelOverview.java
  dinky-admin/src/main/java/org/dinky/data/model/JobStatusOverView.java
  dinky-admin/src/main/java/org/dinky/data/model/JobTypeOverView.java
  dinky-admin/src/main/java/org/dinky/service/HomeService.java
  dinky-admin/src/main/java/org/dinky/service/impl/HomeServiceImpl.java
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Home/DevOverView/ResourceView/index.tsx
  dinky-web/src/pages/Home/DevOverView/TaskDialectRadar/index.tsx
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/GlobalFilter/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/constants.tsx
  dinky-web/src/pages/Metrics/Server/data.tsx
  dinky-web/src/pages/Metrics/Server/function.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/services/constants.tsx
Labels: New Feature, Optimization

#2072 [Feature][web] added flink job metrics layout
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/services/constants.tsx
Labels: New Feature

#2071 [fix] fix paimon use in win ，login filter failure
  dinky-admin/src/main/java/org/dinky/controller/GitController.java
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/data/annotation/PublicInterface.java
  dinky-admin/src/main/java/org/dinky/interceptor/TenantInterceptor.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/services/api.ts
  pom.xml
Labels: bug

#2073 [Fix][admin] fix bug of sys log
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
Labels: bug

#2075 [Feature][web] support some home overview
  dinky-admin/src/main/java/org/dinky/mapper/TaskMapper.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/HomeServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/mapper/TaskMapper.xml
  dinky-web/src/pages/Home/DevOverView/BatchStreamProportion/index.tsx
  dinky-web/src/pages/Home/DevOverView/ResourceView/index.tsx
  dinky-web/src/pages/Home/DevOverView/TaskDialectRadar/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobStatusPie/index.tsx
  dinky-web/src/types/Home/data.d.ts
Labels: New Feature

#2076 fix: newline problem
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/template/DefaultHTMLTemplate.java
  dinky-common/src/main/java/org/dinky/data/model/Table.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractDriver.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
Labels: bug

#2077 feat: enable enforcer check
  .github/workflows/backend.yaml
  dinky-admin/pom.xml
Labels: New Feature

#2086 [Optimization][cdc] Optimize CDCSOURCE in Flink 1.16
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
Labels: Optimization

#2088 [Fix-2087][UDF] udf cannot run on flink1.16 and flink 1.17
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-client/dlink-client-1.17/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
  dlink-common/src/main/java/com/dlink/classloader/DinkyClassLoader.java
  dlink-common/src/main/java/com/dlink/context/DinkyClassLoaderContextHolder.java
  dlink-core/src/main/java/com/dlink/job/JobManager.java
Labels: bug

#2080 Feature add import user from ldap
  dinky-admin/src/main/java/org/dinky/context/LdapContext.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/compontents/LoadUser.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/compontents/TestLogin.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
  dinky-web/src/services/api.ts
  dinky-web/src/services/constants.tsx
Labels: New Feature

#2081 refactor: asome trivial modified.
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobParam.java
  dinky-executor/src/main/java/org/dinky/executor/Executor.java
  dinky-executor/src/main/java/org/dinky/executor/SqlManager.java
  dinky-executor/src/main/java/org/dinky/parser/SingleSqlParserFactory.java
Labels: Optimization

#2090 [Optimization-2089][flink] Upgrade Flink version
  dlink-flink/dlink-flink-1.16/pom.xml
  dlink-flink/dlink-flink-1.17/pom.xml
Labels: Optimization

#2094 [Feature][web] added resource layout
  dinky-web/config/routes.ts
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/FileShow/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/RegCenter/Resource/index.tsx
Labels: New Feature

#2098 [Fix] fix when DataSource type is doris the password is not required
  dinky-web-flink/pom.xml
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
Labels: bug

#2099 refactor metadata module pom file
  dinky-metadata/dinky-metadata-clickhouse/pom.xml
  dinky-metadata/dinky-metadata-doris/pom.xml
  dinky-metadata/dinky-metadata-hive/pom.xml
  dinky-metadata/dinky-metadata-mysql/pom.xml
  dinky-metadata/dinky-metadata-phoenix/pom.xml
  dinky-metadata/dinky-metadata-postgresql/pom.xml
  dinky-metadata/dinky-metadata-presto/pom.xml
  dinky-metadata/dinky-metadata-sqlserver/pom.xml
  dinky-metadata/dinky-metadata-starrocks/pom.xml
  dinky-web-flink/.gitignore
Labels: Refactor

#2103 [BUG][web] Reorder after removing git project
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectProTable/index.tsx
Labels: bug, Optimization

#2115 fix: adapt for sql hints semtanic
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
Labels: bug
