Repository DataLinkDC/dinky, pull requests merged in 2023-01, with the labels that each got.

#1497 [Fix][UDF] Fix FLINK SQL note causes entering UDF analysis
  dlink-core/src/main/java/com/dlink/explainer/Explainer.java
Labels: bug

#1495 [Fix][docker] fix docker-image flink version
  Dockerfile
  DockerfileDinkyFlink
Labels: fixing

#1498 [Fix][Develop]Fix the netty error under Mac OS development
  dlink-admin/pom.xml
Labels: bug

#1501 fix(sec): upgrade org.apache.httpcomponents:httpclient to 4.5.13
  pom.xml
Labels: optimization

#1506 [fix][web,sql] fix sqlfile && fix i18n
  dlink-doc/sql/dinky.sql
  dlink-doc/sql/upgrade/0.7.0_schema/mysql/dinky_ddl.sql
  dlink-web/src/components/Studio/StudioRightTool/StudioSqlConfig/index.tsx
Labels: bug

#1507 [Fix][admin]Fix add k8s ClusterConfiguration npe
  dlink-admin/src/main/java/com/dlink/service/impl/ClusterConfigurationServiceImpl.java
Labels: bug

#1509 fix: udf not support CASE INSENSITIVE
  dlink-function/src/main/java/com/dlink/function/util/UDFUtil.java
Labels: bug

#1510 [fix] UDF function case insensitive
  dlink-function/src/main/java/com/dlink/function/util/UDFUtil.java
Labels: bug

#1515 [Optimize][doc]doc optimize
  build.cmd
  build.sh
  docs/docs/deploy_guide/compile.mdx
  docs/docs/deploy_guide/deploy.md
  docs/docs/deploy_guide/deploy.mdx
  docs/docs/deploy_guide/quick_start.md
  docs/docs/extend/practice_guide/hive.md
  docs/docs/get_started/docker_deploy.md
  docs/docs/get_started/operation_guide.md
  docs/docs/operation_guide/_category_.json
  docs/docs/operation_guide/job_debug.md
  docs/docs/operation_guide/job_submit.md
  docs/docs/operation_guide/summary.md
  docs/docs/upgrade.md
  docs/docusaurus.config.js
  docs/i18n/en/code.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-plugin-content-docs/version-0.7.json
  docs/i18n/en/docusaurus-theme-classic/footer.json
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs/version-0.7.json
  docs/i18n/zh/docusaurus-theme-classic/footer.json
  docs/package.json
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/versioned_docs/version-0.7/comminicate.md
  docs/versioned_docs/version-0.7/deploy_guide/compile.mdx
  docs/versioned_docs/version-0.7/deploy_guide/deploy.md
  docs/versioned_docs/version-0.7/deploy_guide/deploy.mdx
  docs/versioned_docs/version-0.7/deploy_guide/quick_start.md
  docs/versioned_docs/version-0.7/extend/practice_guide/hive.md
  docs/versioned_docs/version-0.7/flink_sql_development_guide/development_guide_overview.md
  docs/versioned_docs/version-0.7/get_started/docker_deploy.md
  docs/versioned_docs/version-0.7/get_started/operation_guide.md
  docs/versioned_docs/version-0.7/operation_guide/_category_.json
  docs/versioned_docs/version-0.7/operation_guide/job_debug.md
  docs/versioned_docs/version-0.7/operation_guide/job_submit.md
  docs/versioned_docs/version-0.7/operation_guide/summary.md
  docs/versioned_docs/version-0.7/sql_development_guide/_category_.json
  docs/versioned_docs/version-0.7/sql_development_guide/data_type.md
  docs/versioned_docs/version-0.7/sql_development_guide/ddl_statement/_category_.json
  docs/versioned_docs/version-0.7/sql_development_guide/ddl_statement/alter_statements.md
  docs/versioned_docs/version-0.7/sql_development_guide/ddl_statement/create_statements.md
  docs/versioned_docs/version-0.7/sql_development_guide/ddl_statement/drop_statements.md
  docs/versioned_docs/version-0.7/sql_development_guide/development_guide_overview.md
  docs/versioned_docs/version-0.7/sql_development_guide/dml_statements/_category_.json
  docs/versioned_docs/version-0.7/sql_development_guide/dml_statements/insert_statements.md
  docs/versioned_docs/version-0.7/sql_development_guide/dml_statements/show_statements.md
  docs/versioned_docs/version-0.7/sql_development_guide/extend_statement.md
  docs/versioned_docs/version-0.7/sql_development_guide/glossary.md
  docs/versioned_docs/version-0.7/sql_development_guide/operators_functions.md
  docs/versioned_docs/version-0.7/sql_development_guide/set_statement.md
  docs/versioned_docs/version-0.7/upgrade.md
Labels: documentation, optimization

#1522 [Fix][ReadMe] fix show image
  README.md
Labels: optimization

#1513 optimize clear console, add clear console at right click
  dlink-web/src/components/Common/CodeShow.tsx
  dlink-web/src/components/Studio/StudioConsole/StudioMsg/index.tsx
Labels: optimization

#1516 Fix the success info after a failed task submission
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/AbstractGatewayResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/result/GatewayResult.java
Labels: bug

#1526 refacotr: simpily dinky-executor code
  dinky-executor/src/main/java/org/dinky/executor/SqlManager.java
  dinky-executor/src/main/java/org/dinky/parser/BaseSingleSqlParser.java
  dinky-executor/src/main/java/org/dinky/parser/InsertSqlParser.java
  dinky-executor/src/main/java/org/dinky/parser/SingleSqlParserFactory.java
  dinky-executor/src/main/java/org/dinky/parser/SqlSegment.java
  dinky-executor/src/main/java/org/dinky/parser/check/AddJarSqlParser.java
  dinky-executor/src/main/java/org/dinky/trans/AbstractOperation.java
  dinky-executor/src/main/java/org/dinky/trans/CreateOperation.java
  dinky-executor/src/main/java/org/dinky/trans/Operations.java
Labels: optimization

#1527 refactor: modify spotless configure, support apply files that changed…
  .github/workflows/backend.yaml
  pom.xml
Labels: optimization

#1276 refactor: flink CustomTableEnvironment 1.11~1.16
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/TableEnvironmentInstance.java
Labels: optimization

#1531 [fix][metedata-postgres]parsing type error when use bigint types
  dinky-common/src/main/java/org/dinky/model/ColumnType.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
Labels: bug

#1539 [Feature][flink]remove flink1.11
  .github/workflows/backend.yaml
  dinky-app/dinky-app-1.11/pom.xml
  dinky-app/dinky-app-1.11/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/pom.xml
  dinky-app/pom.xml
  dinky-assembly/src/main/assembly/package.xml
  dinky-client/dinky-client-1.11/pom.xml
  dinky-client/dinky-client-1.11/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/client/python/PythonFunctionFactory.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/configuration/Configuration.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/configuration/ConfigurationUtils.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClientFactory.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentFactory.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/table/api/DataTypes.java
  dinky-client/dinky-client-1.11/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/AbstractCDCBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/CDCBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/CDCBuilderFactory.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/SinkBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/SinkBuilderFactory.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/doris/DorisSinkBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/CustomTableResultImpl.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/executor/TableSchemaField.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/utils/FlinkStreamProgramWithoutPhysical.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.11/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-base/pom.xml
  dinky-client/pom.xml
  dinky-connectors/dinky-connector-jdbc-1.11/pom.xml
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/dialect/ClickHouseDialect.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/dialect/JdbcDialects.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/dialect/OracleDialect.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/dialect/SQLServerDialect.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/internal/converter/ClickHouseRowConverter.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/internal/converter/OracleRowConverter.java
  dinky-connectors/dinky-connector-jdbc-1.11/src/main/java/org/apache/flink/connector/jdbc/internal/converter/SQLServerRowConverter.java
  dinky-connectors/pom.xml
  dinky-core/pom.xml
  dinky-executor/pom.xml
  dinky-flink/dinky-flink-1.11/pom.xml
  dinky-flink/pom.xml
  dinky-function/pom.xml
  dinky-gateway/pom.xml
  pom.xml
Labels: new feature

#1545 [Feature][metadata,alter]Metadata & alert available in development mode
  dinky-admin/pom.xml
  dinky-alert/dinky-alert-dingtalk/src/main/resources/META-INF/services/org.dinky.alert.Alert
  dinky-alert/dinky-alert-email/src/main/resources/META-INF/services/org.dinky.alert.Alert
  dinky-alert/dinky-alert-wechat/src/main/resources/META-INF/services/org.dinky.alert.Alert
  dinky-metadata/dinky-metadata-clickhouse/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-doris/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-hive/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-mysql/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-oracle/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-phoenix/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-postgresql/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-presto/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-sqlserver/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-starrocks/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
Labels: new feature

#1549 refactor: format CustomTableEnvironmentImpl
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-common/src/main/java/org/dinky/utils/LogicUtil.java
Labels: optimization

#1551 refactor: dinky-common
  dinky-client/dinky-client-1.12/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/kafka/KafkaSinkJsonBuilder.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-common/src/main/java/org/dinky/model/Column.java
  dinky-common/src/main/java/org/dinky/model/ColumnType.java
  dinky-common/src/main/java/org/dinky/model/JobLifeCycle.java
  dinky-common/src/main/java/org/dinky/model/JobStatus.java
  dinky-common/src/main/java/org/dinky/model/SystemConfiguration.java
  dinky-common/src/main/java/org/dinky/model/TableType.java
  dinky-common/src/main/java/org/dinky/model/TaskOperatingSavepointSelect.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/convert/OracleTypeConvert.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/convert/SqlServerTypeConvert.java
Labels: optimization

#1537 refactor: flinkAPI
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
Labels: optimization

#1562 [Fix-1503][executor] Fix use yarn application mode to submit job repo…
  dlink-executor/src/main/java/com/dlink/executor/ExecutorSetting.java
Labels: bug

#1564 [Fix-1563] [metadata-mysql] NPE caused by querying data
  dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/convert/MySqlTypeConvert.java
Labels: bug

#1566 [Optimization-1548][metadata] Optimize datasource registration should can save config before validate
  dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dlink-web/src/locales/zh-CN/request.ts
  dlink-web/src/pages/RegistrationCenter/DataBase/service.ts
Labels: optimization

#1574 refactor admin hdfs file upload
  .github/workflows/docs.yml
  dinky-admin/src/main/java/org/dinky/aop/WebExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/common/result/Result.java
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/configure/CacheConfig.java
  dinky-admin/src/main/java/org/dinky/configure/Knife4jConfig.java
  dinky-admin/src/main/java/org/dinky/controller/FileUploadController.java
  dinky-admin/src/main/java/org/dinky/exception/BusException.java
  dinky-admin/src/main/java/org/dinky/service/FileUploadService.java
  dinky-admin/src/main/java/org/dinky/service/impl/FileUploadServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/HdfsUtil.java
  dinky-admin/src/main/java/org/dinky/utils/MessageResolverUtils.java
  dinky-admin/src/main/resources/i18n/messages.properties
  dinky-admin/src/main/resources/i18n/messages_en_US.properties
  dinky-admin/src/main/resources/i18n/messages_zh_CN.properties
Labels: optimization

#1576 [Optimization-1548][metadata] Optimize datasource registration should…
  dlink-admin/src/main/java/com/dlink/controller/DataBaseController.java
  dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
  dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
  dlink-web/src/locales/zh-CN/request.ts
  dlink-web/src/pages/RegistrationCenter/DataBase/service.ts
Labels: optimization

#1580 postgres的limit查询添加上偏移量limitStart
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/driver/PostgreSqlDriver.java
Labels: optimization

#1581 [Fix][UDF]Fix that udf cannot run on flik1.16
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-common/src/main/java/org/dinky/classloader/DinkyClassLoader.java
  dinky-common/src/main/java/org/dinky/context/DinkyClassLoaderContextHolder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: bug, fixing
