Repository DataLinkDC/dinky, pull requests merged in 2023-03, with the labels that each got.

#1694 [Optimization][dinky-web] Upgrade dependency version
  dinky-web/config/config.ts
  dinky-web/package.json
Labels: optimization

#1700 [Fix-1697][doc]fix add k8s app cluster failed (#1697)
  dlink-doc/bin/auto.sh
Labels: bug

#1702 [Fix-1697][doc]fix add k8s app cluster failed
  script/bin/auto.sh
Labels: bug

#1701 feat: add MySqlDriverTest and refactor mysql metadata
  dinky-metadata/dinky-metadata-mysql/pom.xml
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
  dinky-metadata/dinky-metadata-mysql/src/main/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dinky-metadata/dinky-metadata-mysql/src/test/java/org/dinky/metadata/MysqlTest.java
  dinky-metadata/dinky-metadata-mysql/src/test/java/org/dinky/metadata/driver/MySqlDriverTest.java
  dlink-web/package.json
  pom.xml
Labels: new feature

#1703 [Fix-797][web] Fix no fragment parameters were passed when getting lineage
  dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
  dlink-web/src/components/Studio/StudioEdit/data.d.ts
Labels: bug

#1706 [Document-1705][doc] Update download document and menu
  docs/docs/administrator_guide/_category_.json
  docs/docs/administrator_guide/devops_center/_category_.json
  docs/docs/administrator_guide/studio/k8s_guide/_category_.json
  docs/docs/administrator_guide/studio/k8s_guide/dinky_k8s_quick_start.mdx
  docs/docs/administrator_guide/studio/k8s_guide/remote_link_k8s.md
  docs/docs/administrator_guide/udf_develop/_category_.json
  docs/docs/administrator_guide/udf_develop/how_to/Java&Scala.md
  docs/docs/administrator_guide/udf_develop/how_to/Python.md
  docs/docs/administrator_guide/udf_develop/how_to/_category_.json
  docs/docs/administrator_guide/udf_develop/intro.md
  docs/docs/administrator_guide/udf_develop/template_intro.md
  docs/docs/connector/_category_.json
  docs/docs/connector/flinksql_connectors.md
  docs/docs/data_integration_guide/cdcsource_statements.md
  docs/docs/deploy_guide/_category_.json
  docs/docs/deploy_guide/compile.mdx
  docs/docs/deploy_guide/deploy.mdx
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/extend/function_expansion/connector.md
  docs/docs/plans.md
  docs/docs/platform_intro/_category_.json
  docs/docs/udf_develop/_category_.json
  docs/download/dinky-0.7.1.md
  docs/download/dinky-0.7.2.md
  docs/download/download.md
Labels: documentation

#1716 [Optimization-1715][admin] Optimize job monitor reconnect
  dlink-admin/src/main/java/com/dlink/job/FlinkJobTask.java
  dlink-admin/src/main/java/com/dlink/service/TaskService.java
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
  dlink-web/src/components/Common/JobStatus.tsx
  dlink-web/src/locales/zh-CN/pages.ts
Labels: optimization

#1725 [Document][doc] Update Readme
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
  README_zh_CN.md
Labels: documentation

#1722 [Optimization][dlink-client] optmizatiion cdcsource filter to process
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-client/dinky-client-1.13/src/main/java/org/dinky/cdc/starrocks/StarrocksSinkBuilder.java
Labels: optimization

#1738 [Fix][flink-connectors] missing profile
  dinky-connectors/pom.xml
Labels: bug

#1743 [Fix-1742][web] Fix data studio margin overflow
  dlink-web/src/components/Studio/index.tsx
  dlink-web/src/global.less
Labels: bug

#1747 [Fix-1744][script] Fix startup class error in anto.sh
  script/bin/auto.sh
Labels: bug

#1751 [Fix][metadata] Fix postgres schema error
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java
Labels: bug

#1758 [Optimization-1753][core] Remove deprecated lineage code
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/ca/CABuilder.java
  dinky-core/src/main/java/org/dinky/explainer/ca/CAGenerator.java
  dinky-core/src/main/java/org/dinky/explainer/ca/ColumnCA.java
  dinky-core/src/main/java/org/dinky/explainer/ca/ColumnCAGenerator.java
  dinky-core/src/main/java/org/dinky/explainer/ca/ColumnCANode.java
  dinky-core/src/main/java/org/dinky/explainer/ca/ColumnCAResult.java
  dinky-core/src/main/java/org/dinky/explainer/ca/ICA.java
  dinky-core/src/main/java/org/dinky/explainer/ca/NodeRel.java
  dinky-core/src/main/java/org/dinky/explainer/ca/TableCA.java
  dinky-core/src/main/java/org/dinky/explainer/ca/TableCAGenerator.java
  dinky-core/src/main/java/org/dinky/explainer/ca/TableCANode.java
  dinky-core/src/main/java/org/dinky/explainer/ca/TableCAResult.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageBuilder.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageColumnGenerator.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageTable.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageTableGenerator.java
  dinky-core/src/main/java/org/dinky/explainer/trans/AbstractTrans.java
  dinky-core/src/main/java/org/dinky/explainer/trans/Field.java
  dinky-core/src/main/java/org/dinky/explainer/trans/OperatorTrans.java
  dinky-core/src/main/java/org/dinky/explainer/trans/Predecessor.java
  dinky-core/src/main/java/org/dinky/explainer/trans/SinkTrans.java
  dinky-core/src/main/java/org/dinky/explainer/trans/SourceTrans.java
  dinky-core/src/main/java/org/dinky/explainer/trans/Trans.java
  dinky-core/src/main/java/org/dinky/explainer/trans/TransGenerator.java
  dinky-core/src/main/java/org/dinky/plus/FlinkSqlPlus.java
  dinky-core/src/test/java/org/dinky/core/FlinkSqlPlusTest.java
  dlink-web/src/components/Studio/StudioTree/components/SimpleTaskForm.tsx
  dlink-web/src/components/Studio/StudioTree/components/UpdateCatalogueForm.tsx
  dlink-web/src/components/Studio/StudioTree/components/UploadModal.tsx
Labels: optimization

#1767 [FIX]: maybe have empty primary key statement when no primary key
  dinky-common/src/main/java/org/dinky/model/Table.java
  dinky-common/src/test/java/org/dinky/model/TableTest.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
Labels: bug

#1775 [Fix][metadata] Fix postgres schema error
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java
Labels: bug

#1777 [Optimization-1776][core,metadata] Fix typo
  dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
  dlink-core/src/test/java/com/dlink/core/FlinkRestAPITest.java
  dlink-metadata/dlink-metadata-doris/src/main/java/com/dlink/metadata/driver/DorisDriver.java
  dlink-metadata/dlink-metadata-hive/src/main/java/com/dlink/metadata/driver/HiveDriver.java
  dlink-metadata/dlink-metadata-presto/src/main/java/com/dlink/metadata/driver/PrestoDriver.java
  dlink-metadata/dlink-metadata-starrocks/src/main/java/com/dlink/metadata/driver/StarRocksDriver.java
Labels: optimization

#1778 [Optimization-1657][client] Optimize MysqlJsonDebeziumDeserializationSchema use shaded lib in flink 1.13
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlJsonDebeziumDeserializationSchema.java
  dlink-flink/dlink-flink-1.13/pom.xml
Labels: optimization

#1762 [Optimization-1761][admin,core,web] Remove shared session
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/service/StudioService.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/session/ExecutorEntity.java
  dinky-core/src/main/java/org/dinky/session/SessionConfig.java
  dinky-core/src/main/java/org/dinky/session/SessionInfo.java
  dinky-core/src/main/java/org/dinky/session/SessionPool.java
  dinky-executor/src/main/java/org/dinky/executor/Executor.java
  dinky-executor/src/main/java/org/dinky/executor/ExecutorSetting.java
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/components/SessionForm.tsx
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/data.d.ts
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/index.less
  dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/index.tsx
  dlink-web/src/components/Studio/StudioLeftTool/index.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
Labels: optimization

#1779 [Fix-1731][gateway] Fix deploy flink k8s session error
  dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesSessionGateway.java
Labels: bug

#1780 [sql]Fix spelling error
  script/sql/upgrade/0.8.0_schema/mysql/dinky_dml.sql
Labels: bug

#1746 feat: watch every table data for debug
  .idea/icon.svg
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/WebSocketConfiguration.java
  dinky-admin/src/main/java/org/dinky/controller/WatchTableController.java
  dinky-admin/src/main/java/org/dinky/service/WatchTableService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/WatchTableServiceImpl.java
  dinky-admin/src/test/java/org/dinky/service/impl/WatchTableServiceImplTest.java
  dinky-executor/src/main/java/org/dinky/connector/printnet/sink/PrintNetDynamicTableSink.java
  dinky-executor/src/main/java/org/dinky/connector/printnet/sink/PrintNetDynamicTableSinkFactory.java
  dinky-executor/src/main/java/org/dinky/connector/printnet/sink/PrintNetSinkFunction.java
  dinky-executor/src/main/java/org/dinky/trans/Operations.java
  dinky-executor/src/main/java/org/dinky/trans/ddl/PrintTableOperation.java
  dinky-executor/src/main/java/org/dinky/trans/ddl/WatchTableOperation.java
  dinky-executor/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dlink-web/package.json
  dlink-web/src/app.tsx
  dlink-web/src/components/Studio/StudioConsole/StudioData/index.tsx
  dlink-web/src/components/Studio/StudioConsole/index.tsx
  dlink-web/src/components/Studio/StudioEdit/data.d.ts
  dlink-web/src/components/Studio/StudioTabs/index.tsx
  dlink-web/src/locales/en-US/pages.ts
  dlink-web/src/locales/zh-CN/pages.ts
  dlink-web/src/pages/DataStudio/service.ts
  dlink-web/src/utils/stompClient.ts
  pom.xml
Labels: new feature

#1782 [Fix-1781][admin] NPE occurred when HttpServletRequest is null
  dinky-admin/src/main/java/org/dinky/interceptor/TenantInterceptor.java
Labels: bug

#1783 [Fix-1638] [core] Fix dlink web could not correct display Boolean type data
  dinky-core/src/main/java/org/dinky/result/ResultRunnable.java
Labels: bug

#1785 feat: append receive data
  dlink-web/src/components/Studio/StudioConsole/StudioData/index.tsx
  dlink-web/src/utils/stompClient.ts
  dlink-web/src/utils/stompClientUtil.ts
  pom.xml
Labels: new feature

#1786 [Bug] [Admin] Task is deleted. Task instances and history are not del…
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
Labels: bug

#1795 [Feature-1709][core] Support use FlinkSQL CTE to preview data
  dlink-core/src/main/java/com/dlink/explainer/Explainer.java
  dlink-core/src/main/java/com/dlink/result/ResultBuilder.java
  dlink-executor/src/main/java/com/dlink/parser/SqlType.java
Labels: new feature

#1799 [Feature][web] added role list for dinky-web
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/model/Role.java
  dinky-admin/src/main/java/org/dinky/model/RoleNamespace.java
  dinky-admin/src/main/java/org/dinky/service/RoleService.java
  dinky-admin/src/main/java/org/dinky/service/impl/RoleNamespaceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/RoleServiceImpl.java
  dinky-admin/src/main/resources/i18n/messages.properties
  dinky-admin/src/main/resources/i18n/messages_en_US.properties
  dinky-admin/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/config/routes.ts
  dinky-web/package.json
  dinky-web/src/components/TableTransfer/TableTransfer.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Role/components/RoleForm.tsx
  dinky-web/src/pages/AuthCenter/Role/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/TableTransfer.tsx
  dinky-web/src/services/constants.ts
  dinky-web/src/types/User/data.d.ts
Labels: new feature

#1800 [Optimization][client] Support `scan.incremental.snapshot.chunk.size`…
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
Labels: optimization

#1802 fix watch sql key not support local webui statementSet
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/watchTable/WatchStatementExplainer.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
Labels: bug

#1806 [Fix-1805][admin] Fix NPE occurred when publishing the job
  dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Labels: bug

#1808 [Fix][Optimize][cdcsource] 多源表，多个Sink时，修复优化sink数据发送接收问题 (#1801)
  dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-1.16/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
  dlink-client/dlink-client-base/src/main/java/com/dlink/model/FlinkCDCConfig.java
  dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
Labels: bug

#1804 [Optimize-1803][docker] Optimize docker build
  docker/README.md
  docker/README_zh_CN.md
  docker/server/Dockerfile
  docker/web/Dockerfile
  docker/web/default.conf
  docker/web/dinky.conf.template
  docker/web/nginx.conf
Labels: optimization

#1815 [Feature][dinky-web] added global var list for dinky-web
  dinky-admin/src/main/java/org/dinky/controller/FragmentVariableController.java
  dinky-admin/src/main/java/org/dinky/service/FragmentVariableService.java
  dinky-admin/src/main/java/org/dinky/service/impl/FragmentVariableServiceImpl.java
  dinky-web/.gitignore
  dinky-web/config/routes.ts
  dinky-web/package.json
  dinky-web/src/app.tsx
  dinky-web/src/components/CustomMonacoEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomMonacoEditor/CodeShow/index.tsx
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Role/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/pages/RegCenter/GlobalVar/components/GlobalVarForm.tsx
  dinky-web/src/pages/RegCenter/GlobalVar/index.tsx
  dinky-web/src/pages/RegistrationCenter/.ignore
  dinky-web/src/services/constants.ts
  dinky-web/src/types/Public/data.ts
  dinky-web/src/types/RegCenter/data.d.ts
  dinky-web/src/utils/function.ts
Labels: new feature

#1810 feat: could watch table view
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/watchTable/WatchStatementExplainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-executor/src/main/java/org/dinky/parser/SqlType.java
Labels: new feature
