Repository DataLinkDC/dinky, pull requests merged in 2023-12, with the labels that each got.

#2592 Refactor database
  dinky-admin/src/main/java/org/dinky/data/dto/DataBaseDTO.java
  dinky-admin/src/main/java/org/dinky/data/model/DataBase.java
  dinky-admin/src/main/java/org/dinky/data/typehandler/JSONObjectHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-common/src/main/java/org/dinky/utils/JsonUtils.java
  dinky-core/src/main/java/org/dinky/explainer/sqllineage/SQLLineageBuilder.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/config/AbstractJdbcConfig.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/config/DriverConfig.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/config/IConnectConfig.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/convert/AbstractJdbcTypeConvert.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/convert/AbstractTypeConvert.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/convert/ITypeConvert.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-metadata/dinky-metadata-base/src/test/java/org/dinky/metadata/driver/AbstractDriverTest.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/convert/ClickHouseTypeConvert.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/driver/ClickHouseDriver.java
  dinky-metadata/dinky-metadata-clickhouse/src/test/java/org/dinky/metadata/ClickHouseTest.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/convert/DorisTypeConvert.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/driver/DorisDriver.java
  dinky-metadata/dinky-metadata-doris/src/test/java/org/dinky/metadata/DorisTest.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/convert/HiveTypeConvert.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/driver/HiveDriver.java
  dinky-metadata/dinky-metadata-hive/src/test/java/org/dinky/metadata/HiveTest.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/convert/MySqlTypeConvert.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
  dinky-metadata/dinky-metadata-mysql/src/test/java/org/dinky/metadata/MysqlTest.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/convert/OracleTypeConvert.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/driver/OracleDriver.java
  dinky-metadata/dinky-metadata-oracle/src/test/java/org/dinky/metadata/OracleTest.java
  dinky-metadata/dinky-metadata-phoenix/src/main/java/org/dinky/metadata/convert/PhoenixTypeConvert.java
  dinky-metadata/dinky-metadata-phoenix/src/main/java/org/dinky/metadata/driver/PhoenixDriver.java
  dinky-metadata/dinky-metadata-phoenix/src/test/java/org/dinky/metadata/PhoenixTest.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/driver/PostgreSqlDriver.java
  dinky-metadata/dinky-metadata-presto/src/main/java/org/dinky/metadata/driver/PrestoDriver.java
  dinky-metadata/dinky-metadata-presto/src/test/java/org/dinky/PrestoTest.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/convert/SqlServerTypeConvert.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/driver/SqlServerDriver.java
  dinky-metadata/dinky-metadata-sqlserver/src/test/java/org/dinky/metadata/SqlServerTest.java
  dinky-metadata/dinky-metadata-starrocks/src/main/java/org/dinky/metadata/convert/StarRocksTypeConvert.java
  dinky-metadata/dinky-metadata-starrocks/src/main/java/org/dinky/metadata/driver/StarRocksDriver.java
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SQLQuery/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_ddl.sql
Labels: Refactor

#2596 [Bug][web] Fixed issues with flickering and repeated rendering when editor size changes
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/function.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
Labels: bug

#2606 feat: forbidden empty dropdown item
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
Labels: Optimization

#2609 fix http bug
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
Labels: bug

#2602 Fallback app hook implementation
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/mybatis/handler/DateMetaObjectHandler.java
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.18/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
Labels: Fixing

#2601 [Feature][alert] support tencent sms alert
  dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsConstants.java
  dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsSender.java
  dinky-web/src/components/FormSingleColumnList/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/DingTalk/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/constants.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/constans.ts
  dinky-web/src/types/RegCenter/init.d.ts
Labels: New Feature

#2605 [Optimization-2604][cdc] CDCSOURCE support #{schemaName} and #{tableName}
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/SinkBuilderFactory.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/utils/FlinkStatementUtil.java
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
  dinky-common/src/test/java/org/dinky/data/model/TableTest.java
  dinky-gateway/src/main/java/org/dinky/gateway/enums/GatewayType.java
Labels: Optimization

#2610 [Bug][web] fix theme bug
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/types/Public/data.ts
  dinky-web/src/utils/function.tsx
Labels: bug

#2613 [Bug] fix datasource detail bug
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/index.tsx
  dinky-web/src/utils/function.tsx
Labels: bug

#2615 optimize flink option
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/controller/FlinkController.java
  dinky-admin/src/main/java/org/dinky/data/vo/CascaderVO.java
  dinky-admin/src/main/java/org/dinky/service/FlinkService.java
  dinky-admin/src/main/java/org/dinky/service/impl/FlinkServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/SuggestionServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/FlinkConfigOptionsUtils.java
  dinky-admin/src/main/resources/FlinkConfClass
  dinky-assembly/src/main/assembly/package.xml
  dinky-common/src/main/java/org/dinky/data/flink/config/FlinkConfigOption.java
Labels: Optimization, Fixing

#2623 [Feature-2622][core] Local task supports cancel
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/IpUtils.java
  dinky-common/src/main/java/org/dinky/utils/URLUtils.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
Labels: New Feature

#2619 improve datastudio's menu tag logical & modify some layout
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/LineageGraph/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/StatementInfo.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/data.d.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/AlertHistory/components/AlertHistoryList/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/AlertHistory/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CheckpointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/SavePointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/ExceptionTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/TaskManagerLogsTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/JobChart/JobChart.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/Home/DevOverView/index.tsx
  dinky-web/src/pages/Home/index.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/ResourcesConfig/index.tsx
Labels: Optimization

#2625 refactor globalvar
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/FlinkConfigOptionsUtils.java
  dinky-admin/src/main/resources/dinky-loader/ExpressionVariableClass
  dinky-admin/src/main/resources/dinky-loader/FlinkConfClass
  dinky-assembly/src/main/assembly/package.xml
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
  dinky-core/src/main/java/org/dinky/utils/StringUtil.java
  docs/docs/administrator_guide/register_center/global_var.md
  docs/docs/extend/function_expansion/global_var_ext.md
Labels: Refactor

#2629 [Fix-2628] [core] Fix set config is not effective
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ddl/CustomSetOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/SetSqlParseStrategy.java
Labels: bug

#2632 fix: ClassLoader empty
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
Labels: bug

#2630 improve web finish button type to submit && modify layout
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/components/CallBackButton/PopconfirmDeleteBtn.tsx
  dinky-web/src/components/Icons/AlertIcon.tsx
  dinky-web/src/components/Modal/ErrorModalShow/index.tsx
  dinky-web/src/global.less
  dinky-web/src/pages/AuthCenter/Role/components/RoleModalForm/index.tsx
  dinky-web/src/pages/AuthCenter/RowPermissions/components/PermissionsModal/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantModalForm/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantModalTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/PasswordModal/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/RoleModalTransfer/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/UserModalForm/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/JobRunningModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/FolderModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsForm/MetricsConfigForm.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobVersion/JobVersionTab.tsx
  dinky-web/src/pages/Other/Login/ChooseModal/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/components/AlertGroupForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/constans.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertTemplate/components/AlertTemplateForm.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertTemplate/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/JarShow/JarList/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectProTable/index.tsx
  dinky-web/src/pages/RegCenter/GlobalVar/components/GlobalVarModal/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceModal/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourcesUploadModal/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/UDFRegisterModal/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFTemplate/TemplateModal/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/compontents/TestLogin.tsx
Labels: Optimization

#2646 [Web] Fix web layout
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2648 delete unuse code
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: Optimization

#2647 fix: CTAS not execute
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Alert/AlertTemplate/index.tsx
Labels: bug

#2652 [Optimization-2651][core] Remove statement set
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/FlinkSqlTask.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
Labels: Optimization

#2653 fix: h2 json sql problem
  dinky-admin/src/main/java/org/dinky/service/impl/PrintTableServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
Labels: bug

#2660 fix k8s template bug
  dinky-gateway/src/main/java/org/dinky/gateway/config/K8sConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetsOperatorGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/HighPriorityConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/data.d.ts
  dinky-web/src/types/Studio/data.d.ts
Labels: bug

#2661 footer use sse get jvm
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/controller/SseController.java
  dinky-admin/src/main/java/org/dinky/service/MonitorService.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/FlinkConfigOptionsUtils.java
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: Fixing

#2668 Support push ds modify process
  dinky-admin/src/main/java/org/dinky/service/impl/SchedulerServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProcessClient.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/DagNodeLocation.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/ProcessDefinition.java
  dinky-web/src/pages/DataStudio/HeaderContainer/Explain/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/PushDolphin/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
Labels: New Feature

#2669 Fix that manual registration of history jobs is deleted
  dinky-admin/src/main/java/org/dinky/job/ClearJobHistoryTask.java
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: bug

#2673 [Fix-2672] [core] Fix the issue of cluster configuration deploy session cluster
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/enums/GatewayType.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
Labels: bug

#2674 [Optimize][Web]optimize table data
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-common/src/main/java/org/dinky/utils/RunTimeUtil.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProjectClient.java
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/TabRoute.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: Optimization

#2676 [Doc] updated the docs of Datasource Management to 1.0
  docs/docs/administrator_guide/register_center/datasource_manage.md
Labels: Doc

#2678 [Optimize][Web]optimize right top button for container
  dinky-web/src/pages/DataStudio/LeftContainer/BtnContext/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
Labels: Optimization

#2680 Support wechat custom url
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatConstants.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatSender.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/params/WechatParams.java
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/TableData/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/BtnContext/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/TabRoute.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/WeChat/index.tsx
Labels: New Feature

#2682 Fix clusterinstancelist bug
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
Labels: bug

#2685 fix user admin delete bug
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/pages/AuthCenter/User/components/UserProTable/index.tsx
Labels: bug

#2686 refactor: implement print with create table like
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/print_table/PrintStatementExplainer.java
  dinky-core/src/test/java/org/dinky/explainer/print_table/PrintStatementExplainerTest.java
Labels: Optimization

#2687 Delete useless pom configuration
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/aop/exception/UnKnownExceptionHandler.java
  dinky-gateway/pom.xml
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/contants.tsx
  pom.xml
Labels: Optimization

#2695 [Optimization-2694][flink] Upgrade Flink and Flink CDC
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sqlserver/SqlServerCDCBuilder.java
  dinky-cdc/pom.xml
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  pom.xml
  script/bin/auto.sh
Labels: Optimization

#2693 support enable or disable model error
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/requestErrorConfig.ts
  dinky-web/src/services/constants.tsx
  dinky-web/src/utils/function.tsx
Labels: New Feature

#2696 Fix exception
  dinky-admin/src/main/java/org/dinky/aop/exception/UnKnownExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/aop/exception/WebExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/data/result/Result.java
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: bug

#2700 [Fix][Flink] Fix extended syntax support for Flink 1.14-1.15
  dinky-client/dinky-client-1.14/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
Labels: bug

#2701 [Fix][Web]fix monaco use cdn,but should use local
  dinky-web/src/components/CustomEditor/CodeEdit/function.tsx
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/DiffModal.tsx
Labels: bug

#2704 [Optimization-2703][studio] Optimize online debug task
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/FlinkSqlTask.java
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DataStudio/route.tsx
Labels: Optimization

#2702 Support devops card checkstyle
  dinky-web/src/components/CustomEditor/CodeEdit/function.tsx
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/DiffModal.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/StatisticsCard.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: Optimization

#2706 [Feature][Web] Add down log feature
  dinky-web/src/components/CallBackButton/CircleBtn.tsx
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/StatisticsCard.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
Labels: New Feature

#2708 Added the method of adding a quick alarm template
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
Labels: Optimization

#2707 [Optimize] [Web] Optimize breadcrumbs
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
Labels: Optimization

#2688 support http alert
  dinky-admin/src/main/java/org/dinky/data/model/ext/TaskExtConfig.java
  dinky-alert/dinky-alert-feishu/src/test/java/org/dinky/alert/feishu/FeiShuSenderTest.java
  dinky-alert/dinky-alert-http/pom.xml
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpAlert.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpConstants.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpSender.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/params/HttpParams.java
  dinky-alert/dinky-alert-http/src/main/resources/Http.ftl
  dinky-alert/dinky-alert-http/src/main/resources/META-INF/services/org.dinky.alert.Alert
  dinky-alert/dinky-alert-http/src/test/java/org/dinky/alert/http/HttpSenderTest.java
  dinky-alert/pom.xml
  dinky-common/src/main/java/org/dinky/data/ext/ConfigItem.java
  dinky-web/src/components/Icons/AlertIcon.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Http/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/constans.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/function.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: New Feature

#2709 [Optimize][Web] optimize DataStudio jumps Devops jobid is not the latest
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
Labels: Optimization

#2711 Complete HTTP alert
  dinky-admin/src/main/java/org/dinky/controller/AlertInstanceController.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/AlertBaseConstant.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpAlert.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpConstants.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/HttpSender.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/params/HttpParams.java
  dinky-alert/dinky-alert-http/src/test/java/org/dinky/alert/http/HttpSenderTest.java
  dinky-assembly/src/main/assembly/package.xml
  dinky-core/pom.xml
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Http/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/service.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/types/RegCenter/data.d.ts
  pom.xml
Labels: New Feature

#2698 Update Dinky 1.0 job and environment documents, and optimize related documents
  docs/docs/administrator_guide/studio/env_config.md
  docs/docs/administrator_guide/studio/job_config.md
  docs/docs/administrator_guide/studio/job_config_submit.md
  docs/docs/administrator_guide/studio/job_hosting.md
  docs/docs/administrator_guide/studio/job_submit.md
  docs/versioned_docs/version-0.7/k8s_guide/Dinky_integrated_Flink_on_K8s.md
  docs/versioned_docs/version-0.7/k8s_guide/dinky_k8s_quick_install.md
Labels: Doc

#2720 [Fix] [Web] Fix debug
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/services/endpoints.tsx
Labels: bug

#2710 Fix delete task bug
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/services/endpoints.tsx
Labels: bug

#2721 fix cluster config i18n error
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
Labels: bug

#2714 Add a normal task to debug and return multiple query results, and a debugging task to save the script state
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/BaseTask.java
  dinky-admin/src/main/java/org/dinky/service/task/CommonSqlTask.java
  dinky-core/src/main/java/org/dinky/job/JobResult.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-metadata/dinky-metadata-base/src/test/java/org/dinky/metadata/driver/AbstractDriverTest.java
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: New Feature

#2725 Optimized the Flink configuration form
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/components/Flink/OptionsSelect/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
Labels: Optimization

#2726 Fix added flinksqlenv after show bug
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: bug

#2727 Add normal stop
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#2730 Added job information remapping
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/components/EditJobInstanceForm.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/Metrics/Job/service.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#2732 [Fix-2731] [scheduler] Fix push task to dolphinscheduler
  dinky-admin/src/main/java/org/dinky/controller/SchedulerController.java
  dinky-admin/src/main/java/org/dinky/service/impl/SchedulerServiceImpl.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProcessClient.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/TaskClient.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/DagNodeLocation.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/ProcessTaskRelation.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/TaskDefinition.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/TaskRequest.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/utils/ReadFileUtil.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/HeaderContainer/PushDolphin/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/PushDolphin/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/types/Studio/data.d.ts
  dinky-web/src/types/Studio/init.d.ts
Labels: bug

#2733 Optimize data development initialization data calling method
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/function.ts
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/index.tsx
Labels: Optimization

#2738 [Feature-2736][*] Release v1.0.0-rc1
  .github/ISSUE_TEMPLATE/bug-report.yml
  dinky-web/src/services/constants.tsx
  pom.xml
Labels: New Feature

#2742 [Fix-#2740] Fixed issue of re-rendering task list after publishing offline
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
Labels: bug, Optimization

#2745 redactor register center of cluster
  docs/docs/administrator_guide/register_center/cluster_manage.md
Labels: Doc, Refactor

#2741 [Fix-#2739] Fix bug that complete the missing path in auto.sh's CLASS_PATH
  script/bin/auto.sh
Labels: bug

#2765 redactor register center of alert
  docs/docs/administrator_guide/register_center/alert/_category_.json
  docs/docs/administrator_guide/register_center/alert/alert_group.md
  docs/docs/administrator_guide/register_center/alert/alert_instance.md
  docs/docs/administrator_guide/register_center/alert/alert_overview.md
  docs/docs/administrator_guide/register_center/alert/alert_template.md
  docs/docs/administrator_guide/register_center/cluster_manage.md
  docs/docs/administrator_guide/register_center/datasource_manage.md
  docs/docs/administrator_guide/register_center/document_manager.md
  docs/docs/administrator_guide/register_center/global_var.md
  docs/docs/administrator_guide/register_center/warning.md
  docs/docs/administrator_guide/studio/job_config_submit.md
  docs/docs/administrator_guide/studio/job_monitoring.md
  docs/docs/get_started/operation_guide.md
Labels: Doc

#2769 Fix save_point_strategy of history bug
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2775 support git doc
  docs/docs/administrator_guide/register_center/git_project.md
  docs/docs/administrator_guide/register_center/udf.md
Labels: Doc

#2764 fix: flink 1.18 set operator not work and configure null error
  dinky-admin/src/main/java/org/dinky/data/model/ext/TaskExtConfig.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
Labels: bug

#2763 feat: add key width for job configure item
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
Labels: Optimization

#2780 fix: print like problem
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/print_table/PrintStatementExplainer.java
Labels: bug

#2786 fix: create view to ddl catalog
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/SqlType.java
Labels: bug

#2785 add k8s doc
  docs/docs/administrator_guide/studio/k8s_guide/_category_.json
  docs/docs/administrator_guide/studio/k8s_guide/dinky_k8s_quick_start.mdx
  docs/docs/administrator_guide/studio/k8s_guide/img/add_k8s_conf_001.jpg
  docs/docs/administrator_guide/studio/k8s_guide/img/add_k8s_conf_002.jpg
  docs/docs/administrator_guide/studio/k8s_guide/img/add_k8s_conf_003.jpg
  docs/docs/administrator_guide/studio/k8s_guide/img/add_k8s_conf_004.jpg
  docs/docs/administrator_guide/studio/k8s_guide/remote_link_k8s.md
  docs/docs/data_integration_guide/dinky_k8s_quick_start.mdx
Labels: Doc

#2751 refactor: improve extract yaml from execute pipeline command
  dinky-core/src/main/java/org/dinky/trans/pipeline/FlinkCDCPipelineOperation.java
  dinky-core/src/test/java/org/dinky/trans/pipeline/FlinkCDCPipelineOperationTest.java
Labels: Optimization

#2787 Optimize some docs
  docs/docs/administrator_guide/devops_center/_category_.json
  docs/docs/administrator_guide/hotkey.md
  docs/docs/administrator_guide/metrics_overview.md
  docs/docs/administrator_guide/register_center/git_project.md
  docs/docs/administrator_guide/register_center/resource.md
  docs/docs/administrator_guide/system_setting/global_settings/dinky_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/dolphinscheduler_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/flink_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/ldap.md
  docs/docs/administrator_guide/system_setting/global_settings/maven_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/metrics_setting.md
  docs/docs/administrator_guide/system_setting/global_settings/resource_setting.md
  docs/docs/administrator_guide/system_setting/system_log.md
  docs/docs/administrator_guide/system_setting/system_log/_category_.json
  docs/docs/administrator_guide/system_setting/system_log/system_log.md
  docs/docs/administrator_guide/udf_develop/_category_.json
Labels: Doc

#2791 Add dinky port configure
  dinky-admin/src/main/java/org/dinky/service/impl/PrintTableServiceImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/constant/CustomerConfigureOptions.java
  dinky-core/src/main/java/org/dinky/connector/printnet/sink/PrintNetSinkFunction.java
Labels: Optimization

#2797 Optimize register center some docs
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/function.tsx
  docs/docs/user_guide/auth_center/menu.md
  docs/docs/user_guide/auth_center/role.md
  docs/docs/user_guide/auth_center/row_limits.md
  docs/docs/user_guide/auth_center/tenant.md
  docs/docs/user_guide/auth_center/token.md
  docs/docs/user_guide/auth_center/user.md
  docs/docs/user_guide/register_center/alert/alert_instance.md
  docs/docs/user_guide/register_center/alert/alert_overview.md
  docs/docs/user_guide/register_center/cluster_manage.md
  docs/docs/user_guide/register_center/datasource_manage.md
  docs/docs/user_guide/register_center/resource.md
  docs/docs/user_guide/system_setting/alert_strategy.md
Labels: Doc

#2799 fix JobLifeCycle
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: bug

#2796 Fix app not throw exception
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.18/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/pom.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesSessionGateway.java
Labels: bug

#2798 Fix the alert option is incorrect
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/constants.ts
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/function.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/function.ts
Labels: bug

#2800 [Bug] [app]fix_app_bug
  dinky-client/dinky-client-1.14/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-common/src/main/java/org/dinky/utils/ClassPathUtils.java
  dinky-core/src/main/java/org/dinky/executor/AppBatchExecutor.java
  dinky-core/src/main/java/org/dinky/trans/Operations.java
  pom.xml
Labels: bug

#2801 [Fix-#2754] the YAML form of K8s form in the cluster is not displayed
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
Labels: Optimization

#2802 [Fix-#2756] Fix the Devops job list duration formate error
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList/JobHistoryList.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/function.tsx
Labels: bug

#2803 [fix-#2777]Fix flink dag tooltip
  dinky-web/src/components/Flink/FlinkDag/component/DagPlanNode.tsx
Labels: bug

#2805 [Improve][admin] improve query catalog tree
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
Labels: New Feature

#2804 [Fix-#2782]Fix Checkpoint path not found
  dinky-common/src/main/java/org/dinky/data/flink/checkpoint/CheckpointStatistics.java
Labels: bug

#2807 Fix push ds locations bug
  dinky-admin/src/main/java/org/dinky/service/impl/SchedulerServiceImpl.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProcessClient.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/DagNodeLocation.java
  dinky-scheduler/src/main/java/org/dinky/scheduler/model/ProcessDefinition.java
  dinky-web/src/components/Flink/FlinkDag/component/DagPlanNode.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/constants.ts
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/RuleEditForm/function.tsx
Labels: bug

#2808 [Fix-2806] [Flink] The job parameters are not effective when the set parameters key and value contain single quotes
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/SetSqlParseStrategy.java
  dinky-client/dinky-client-base/src/test/java/org/dinky/trans/ddl/CustomSetOperationTest.java
Labels: bug

#2810 [Bug] [App] Fix app start
  dinky-app/dinky-app-1.14/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.15/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.16/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.17/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-1.18/src/main/java/org/dinky/app/MainApp.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
Labels: bug

#2815 [Fix - #2814]Fix Checkpoint overview error
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/flink/checkpoint/CheckPointOverView.java
  dinky-web/src/components/Typography/EllipsisMiddle.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CheckpointTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CkDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/SavePointTable.tsx
Labels: bug

#2816 [Doc] improve some doc and added localdebug doc
  dinky-web/src/pages/RegCenter/Document/constans.ts
  docs/docs/developer_guide/contribution/commit_code.md
  docs/docs/developer_guide/contribution/commit_message.md
  docs/docs/developer_guide/contribution/document.md
  docs/docs/developer_guide/contribution/how_contribute.md
  docs/docs/developer_guide/contribution/issue.md
  docs/docs/developer_guide/contribution/pull_request.md
  docs/docs/developer_guide/local_debug.md
  docs/docs/user_guide/auth_center/menu.md
  docs/docs/user_guide/auth_center/role.md
  docs/docs/user_guide/auth_center/tenant.md
  docs/docs/user_guide/auth_center/token.md
  docs/docs/user_guide/auth_center/user.md
  docs/docs/user_guide/register_center/alert/alert_template.md
  docs/docs/user_guide/register_center/cluster_manage.md
  docs/docs/user_guide/register_center/datasource_manage.md
  docs/docs/user_guide/register_center/document_manager.md
  docs/docs/user_guide/register_center/resource.md
Labels: Doc

#2817 [Fix] fix-query-checkpoint-function
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: bug

#2821 [Optimization-2822] optimization metrics page tips
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
Labels: Optimization

#2820 [Optimization-2773] Optimization The data source directory tree has two scroll bars
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/SchemaTree/index.tsx
Labels: Optimization

#2819 [Improvement-2809] Improvement result not scroll
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
Labels: Optimization

#2825 [Bug][Flink] FLINK CATALOG does not take effect with add_jar
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: bug

#2834 refactor doc database
  dinky-admin/src/main/java/org/dinky/service/impl/FlinkServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/DocumentForm/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentProTable/index.tsx
  dinky-web/src/pages/RegCenter/Document/constans.ts
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: Optimization

#2831 [Fix-2832] Fix h2 driver no default packaging problem
  README.md
  README_zh_CN.md
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/Knife4jConfig.java
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/Other/About/components/UsingHelp.tsx
  docs/README.md
  docs/docs/get_started/quick_experience.md
  docs/docs/user_guide/studio/job_config_submit.md
  docs/docusaurus.config.js
  docs/versioned_docs/version-0.6/build_deploy/build.md
  docs/versioned_docs/version-0.7/k8s_guide/Dinky_integrated_Flink_on_K8s.md
  pom.xml
Labels: bug

#2835 [Fix] Fix sql bug and add some document
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-web/src/components/CustomEditor/languages/flinksql/keyword.ts
  dinky-web/src/pages/AuthCenter/RowPermissions/components/PermissionsProTable/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/DocumentForm/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentProTable/index.tsx
  dinky-web/src/pages/RegCenter/Document/constans.ts
  dinky-web/src/utils/function.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0-SNAPSHOT_schema/mysql/dinky_dml.sql
Labels: bug

#2839 [Fix] fix sql file bug
  dinky-admin/src/main/resources/db/db-h2-dml.sql
Labels: bug

#2824 [Optimize] [Gateway] optimize yarn app submit
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/utils/FlinkJsonUtil.java
  dinky-client/dinky-client-base/src/test/java/org/dinky/utils/FlinkJsonUtilTest.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
Labels: Optimization

#2840 Fixed that jobInstance was always in the running state
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
Labels: bug

#2844 [Fix-#2843]Yarn Application mode submission task failed, lack of log printing
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/exception/BusException.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesSessionGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnPerJobGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnSessionGateway.java
Labels: bug

#2845 feat: implement operator with SPI
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/DinkyExtendedParser.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ddl/PrintTableOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/AddJarSqlParseStrategy.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/CreateTemporalTableFunctionParseStrategy.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/ExecuteJarParseStrategy.java
  dinky-client/dinky-client-base/src/main/resources/META-INF/services/org.apache.flink.table.planner.parse.ExtendedParseStrategy
Labels: Enhancement

#2847 [Document-2830][doc] Update download
  docs/docusaurus.config.js
  docs/download/dinky-1.0.0.md
  docs/download/download.md
  docs/src/pages/index.js
Labels: Doc

#2850 fix: h2 udf problem
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/BaseTask.java
  dinky-admin/src/main/java/org/dinky/utils/UDFUtils.java
  dinky-common/src/main/java/org/dinky/config/Dialect.java
Labels: Fixed

#2848 [Fix] Fix h2 sql bug
  dinky-admin/src/main/resources/db/db-h2-dml.sql
Labels: bug

#2849 Improve document form layout
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/DocumentForm/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/index.tsx
Labels: Optimization

#2854 feat: add resource implement for DinkyClassLoader
  dinky-common/src/main/java/org/dinky/classloader/DinkyClassLoader.java
Labels: Enhancement

#2859 Fixed URL misspelling causing the request to fail
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
Labels: bug

#2860 [Fix-2855] Fix savepoint table params bug
  dinky-admin/src/main/java/org/dinky/controller/SavePointsController.java
  dinky-admin/src/main/java/org/dinky/service/impl/SavepointsServiceImpl.java
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/SavePointTable.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/DocumentForm/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentModal/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/Studio/data.d.ts
Labels: bug

#2864 [Doc] Modify doc i18n and Added some docs
  docs/docs/deploy_guide/_category_.json
  docs/docs/developer_guide/_category_.json
  docs/docs/developer_guide/contribution/_category_.json
  docs/docs/developer_guide/contribution/code_format.md
  docs/docs/developer_guide/contribution/commit_code.md
  docs/docs/developer_guide/contribution/commit_message.md
  docs/docs/developer_guide/contribution/how_contribute.md
  docs/docs/developer_guide/contribution/issue.md
  docs/docs/developer_guide/local_debug.md
  docs/docs/extend/_category_.json
  docs/docs/extend/expand_statements/_category_.json
  docs/docs/extend/function_expansion/_category_.json
  docs/docs/faq.md
  docs/docs/get_started/_category_.json
  docs/docs/get_started/quick_start/_category_.json
  docs/docs/platform_intro/_category_.json
  docs/docs/practical_guide/Integration_practice/_category_.json
  docs/docs/practical_guide/_category_.json
  docs/docs/practical_guide/cdcsource_practice/_category_.json
  docs/docs/practical_guide/run_mode_practice/_category_.json
  docs/docs/practical_guide/scenario_practice/_category_.json
  docs/docs/thanks.md
  docs/docs/user_guide/_category_.json
  docs/docs/user_guide/auth_center/_category_.json
  docs/docs/user_guide/devops_center/_category_.json
  docs/docs/user_guide/register_center/_category_.json
  docs/docs/user_guide/register_center/alert/_category_.json
  docs/docs/user_guide/studio/_category_.json
  docs/docs/user_guide/studio/development_control/_category_.json
  docs/docs/user_guide/system_setting/_category_.json
  docs/docs/user_guide/system_setting/global_settings/_category_.json
  docs/docs/user_guide/udf_develop/_category_.json
  docs/docs/user_guide/udf_develop/quick_use/Java&Scala.md
  docs/docs/user_guide/udf_develop/quick_use/Python.md
  docs/docs/user_guide/udf_develop/quick_use/_category_.json
  docs/docusaurus.config.js
  docs/i18n/en/code.json
  docs/i18n/en/docusaurus-plugin-content-docs-download/current.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-theme-classic/footer.json
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/i18n/zh/code.json
  docs/i18n/zh/docusaurus-plugin-content-docs-download/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-theme-classic/footer.json
  docs/i18n/zh/docusaurus-theme-classic/navbar.json
  docs/package.json
Labels: Doc
