Repository DataLinkDC/dinky, pull requests merged in 2024-10, with the labels that each got.

#3858 [Fix]fix menu mapper
  dinky-admin/src/main/resources/mapper/MenuMapper.xml
Labels: Bug

#3856 [Fix]fix job alert dinky address url
  dinky-admin/src/main/java/org/dinky/data/model/ext/JobAlertData.java
Labels: Bug

#3877 [Fix-3876] [cdc] Remove quotation marks when building FlinkSQL
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/utils/FlinkStatementUtil.java
Labels: Bug

#3878 upgrade cdc to 3.2.0
  dinky-core/src/main/java/org/dinky/trans/pipeline/DinkyFlinkPipelineComposer.java
  dinky-core/src/main/java/org/dinky/trans/pipeline/DinkyFlinkPipelineExecution.java
  dinky-core/src/main/java/org/dinky/trans/pipeline/FlinkCDCPipelineOperation.java
  dinky-core/src/main/java/org/dinky/trans/pipeline/YamlTextPipelineDefinitionParser.java
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-flink/dinky-flink-1.19/pom.xml
  dinky-flink/dinky-flink-1.20/pom.xml
Labels: DEVELOPING

#3880 [BugFix][DevOps]do not save job instance in query mode
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
Labels: Bug

#3882 [Doc] Add ws doc
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3881 [Bug][Web] Fix ws bug
  dinky-web/src/components/Modal/WsErrorShow/WsErrorShow.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/models/UseWebSocketModel.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
Labels: Bug

#3885 [Bug]Fix web package
  dinky-web/package.json
Labels: Bug

#3890 add package-lock.json
  dinky-web/package-lock.json
  dinky-web/package.json
  dinky-web/src/models/UseWebSocketModel.tsx
Labels: Bug

#3891 [hotfix][build] Fix Dinky backend CI workflow with Flink 1.20
  .github/workflows/backend.yaml
Labels: Bug
