Repository DataLinkDC/dinky, pull requests merged in 2024-06, with the labels that each got.

#3553 [BugFix] [UDF] Fix the issue where UDF cannot find classes in Flink SQL tasks
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-function/src/main/java/org/dinky/function/compiler/CustomStringScalaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/FunctionCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/JVMPackage.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/PythonFunction.java
  dinky-function/src/main/java/org/dinky/function/compiler/ScalaCompiler.java
  dinky-function/src/main/java/org/dinky/function/constant/PathConstant.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
Labels: Bug

#3547 [Improvement] Optimize paimon to store monitoring data, causing threads not to be released
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/SystemMetricsHandler.java
  dinky-web/README.md
  dinky-web/README_zh_CN.md
  dinky-web/src/components/Flink/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/Flink/OptionsSelect/index.tsx
  dinky-web/src/components/Flink/UdfSelect/index.tsx
  dinky-web/src/components/LineageGraph/lineage-dag-ext.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/JobConfigInfo.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/JobRunningModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/service.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/constans.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/types/Studio/data.d.ts
Labels: Bug

#3561 [Optimization][metrics]fix_metrics_web_page
  dinky-web/package.json
  dinky-web/src/components/Flink/FlinkChart/index.tsx
  dinky-web/src/components/Flink/ListPagination/index.tsx
  dinky-web/src/components/MarqueeAlert/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/JobChart/JobChart.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/MetricsForm/MetricsConfigTab.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/function.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/service.ts
  dinky-web/src/pages/Metrics/JobMetricsList/index.tsx
  dinky-web/src/pages/Metrics/Server/CPU/index.tsx
  dinky-web/src/pages/Metrics/Server/Heap/index.tsx
  dinky-web/src/pages/Metrics/Server/OutHeap/index.tsx
  dinky-web/src/pages/Metrics/Server/Thread/index.tsx
  dinky-web/src/pages/Metrics/Server/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/model.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/service.ts
  dinky-web/src/types/Public/data.ts
  dinky-web/src/utils/function.tsx
  pom.xml
Labels: Optimization

#3555 [Feature] Release-1.0.3
  docs/docs/deploy_guide/upgrade/upgrade_075to100.md
  docs/docs/deploy_guide/upgrade/upgrade_101to102.md
  docs/docs/deploy_guide/upgrade/upgrade_overview.md
  docs/docs/developer_guide/local_debug.md
  docs/download/dinky-1.0.3.md
  docs/download/download.md
Labels: New Feature

#3580 [Doc]Add docker doc
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/deploy_guide/kubernetes_deploy.md
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3581 [Doc]fix doc error
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3563 [Doc] Supplementary documents
  docs/docs/developer_guide/local_debug.md
  docs/docs/get_started/quick_experience.md
  docs/versioned_docs/version-1.0/deploy_guide/upgrade/upgrade_075to100.md
  docs/versioned_docs/version-1.0/deploy_guide/upgrade/upgrade_101to102.md
  docs/versioned_docs/version-1.0/deploy_guide/upgrade/upgrade_overview.md
  docs/versioned_docs/version-1.0/get_started/quick_experience.md
Labels: Doc

#3558 [Feature] remove scala profile
  dinky-flink/dinky-flink-1.14/pom.xml
  pom.xml
Labels: New Feature

#3590 [Fix] fix h2 config error
  dinky-admin/src/main/resources/application-h2.yml
Labels: Bug

#3591 Optimize some judgment logic and alert rule logic
  dinky-admin/src/main/java/org/dinky/controller/AlertRuleController.java
  dinky-admin/src/main/java/org/dinky/data/model/alert/AlertRule.java
  dinky-admin/src/main/java/org/dinky/data/model/alert/AlertTriggerRule.java
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/function.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/constants.ts
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/function.tsx
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: Optimization

#3594 [Fix] Fix compatibility issues with MySQL stored procedures
  dinky-admin/src/main/resources/db/migration/mysql/V1.1.0__release.sql
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/constants.ts
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/function.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/index.tsx
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: Bug

#3592 add feature cdcsource sink table name mapping, regular matching modification
  build-extr.sh
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/test/java/org/dinky/cdc/AbstractSinkBuilderTest.java
  dinky-common/src/main/java/org/dinky/data/model/FlinkCDCConfig.java
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2mysql_regex.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: New Feature

#3572 [Feature-2981][admin] Preview data in execution history
  dinky-admin/src/main/java/org/dinky/job/JobShutdownConfig.java
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/job/handler/JobReadMysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/resources/db/migration/h2/V1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V1.1.0__release.sql
  dinky-common/src/main/java/org/dinky/data/constant/MysqlConstant.java
  dinky-core/src/main/java/org/dinky/data/result/ResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/ResultPool.java
  dinky-core/src/main/java/org/dinky/data/result/ResultRunnable.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResult.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResultBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobHandler.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobReadHandler.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/test/java/org/dinky/data/result/SelectResultTest.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/PreViewData.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  script/sql/dinky-mysql.sql
Labels: New Feature

#3605 [Feature]support sql cli
  dinky-admin/src/main/java/org/dinky/configure/WebSocketConfiguration.java
  dinky-admin/src/main/java/org/dinky/context/SqlGatewayWsContext.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.19/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/gateway/ISqlClient.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/gateway/SqlCliMode.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/gateway/SqlClientOptions.java
  dinky-common/src/main/java/org/dinky/utils/CloseUtil.java
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-flink/dinky-flink-1.19/pom.xml
  dinky-gateway/src/main/java/org/dinky/gateway/sqlgateway/cli/SqlClientAdapter.java
  dinky-web/package.json
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Lineage/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Terminal/TerminalConfig.ts
  dinky-web/src/pages/DataStudio/MiddleContainer/Terminal/TerminalContent.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Terminal/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Terminal/xterm.css
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/Cluster/constants.tsx
  dinky-web/src/services/constants.tsx
Labels: New Feature
