Repository DataLinkDC/dinky, pull requests merged in 2024-04, with the labels that each got.

#3334 [Optimize][Sql] Optimize git demo address
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.2_schema/mysql/dinky_dml.sql
  script/sql/upgrade/1.0.2_schema/postgre/dinky_dml.sql
Labels: Optimization

#3348 [Fix] fix time type convert
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/convert/OracleTypeConvert.java
Labels: Bug

#3355 [Fix-3354][dinky-admin] Fix CodeGeneratorImpl load fail by spi
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
Labels: Bug

#3350 [Bug] Fix k8s pod template not decorate bug
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetsOperatorGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/utils/K8sClientHelper.java
Labels: Bug

#3351 [Optimization] [Flink Jar] Optimize flink jar task submission to support batch tasks
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/utils/FlinkStreamEnvironmentUtil.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
Labels: Bug, Optimization

#3358 Feat: Adapt to multiple rest svcTypes in KubernetsApplicationOperator mode and modify the JobId acquisition judgment logic
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubetnetsApplicationOperatorGateway.java
Labels: Optimization

#3357 [Optimization] Optimization table rowkey
  dinky-web/src/pages/DevOps/JobList/index.tsx
Labels: Optimization

#3356 [Optimization][web] optimization right click menu overflow unable to display
  dinky-web/src/components/RightContextMenu/index.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
Labels: Optimization

#3360 [Optimization][web] Modify task optimization to prevent template modification
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
Labels: Optimization

#3367 [Optimization] optimize display cluster configuration types
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/BaseConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/constants.tsx
Labels: Optimization

#3368 Optimize k8s delete cluster
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/utils/K8sClientHelper.java
Labels: Optimization

#3374 [Optimization]Fix the issue that clusters are not automatically deleted in app mode
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
Labels: Optimization

#3373 [Bug]Fix the issue that the status is unknown after the batch task is Finish
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
Labels: Bug

#3376 [Optimization] Remove datasource cache with Paimon
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/cache/CacheConfiguration.java
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCache.java
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCacheManager.java
  dinky-admin/src/main/resources/application.yml
Labels: Optimization

#3371 [Fix][metadata-mysql] Bugfix for the numeric column declared by UNSIGNED / ZEROFILL keyword would cause parsing mismatches
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
Labels: Bug

#3384 [Bug]Fix prejob status is UNKNOWN
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
Labels: Bug

#3385 [Optmization]Remove automatic Console popup when switching tasks
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
Labels: Optimization

#3386 [Fix][Admin] Fix the problem of duplicate Jid, which leads to retrieving multiple job instances
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
Labels: Bug

#3393 [Doc] fix resource doc problem
  docs/docs/user_guide/system_setting/global_settings/resource_setting.md
Labels: Doc

#3395 [Doc] remove flink setting config
  docs/docs/user_guide/system_setting/global_settings/flink_setting.md
Labels: Doc

#3397 [Optimization] optimizing the rendering logic of resource management
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/model.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/service.ts
Labels: Optimization

#3398 [Feature] add issue template of version
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: New Feature

#3401 [Fix-3396]fix cannot render query data button
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
Labels: Bug

#3404 [Doc] Add ads
  docs/docusaurus.config.js
  docs/src/plugin/wwads-plugin.ts
Labels: Doc

#3399 [Feature] support clear console log
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/services/api.ts
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#3403 [FIX-3402][dinky-core] edit: print statement query template
  dinky-core/src/main/java/org/dinky/explainer/print_table/PrintStatementExplainer.java
Labels: Bug

#3405 [Optimization] Optimize login detection
  dinky-admin/src/main/java/org/dinky/aop/exception/WebExceptionHandler.java
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertGroupController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertHistoryController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertRuleController.java
  dinky-admin/src/main/java/org/dinky/controller/AlertTemplateController.java
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterConfigurationController.java
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/DataSourceController.java
  dinky-admin/src/main/java/org/dinky/controller/DocumentController.java
  dinky-admin/src/main/java/org/dinky/controller/FlinkController.java
  dinky-admin/src/main/java/org/dinky/controller/FlinkProxyController.java
  dinky-admin/src/main/java/org/dinky/controller/FragmentController.java
  dinky-admin/src/main/java/org/dinky/controller/GitController.java
  dinky-admin/src/main/java/org/dinky/controller/HistoryController.java
  dinky-admin/src/main/java/org/dinky/controller/HomeController.java
  dinky-admin/src/main/java/org/dinky/controller/JarController.java
  dinky-admin/src/main/java/org/dinky/controller/JobInstanceController.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-admin/src/main/java/org/dinky/controller/LogController.java
  dinky-admin/src/main/java/org/dinky/controller/MenuController.java
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/controller/PrintTableController.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleController.java
  dinky-admin/src/main/java/org/dinky/controller/RoleMenuController.java
  dinky-admin/src/main/java/org/dinky/controller/RowPermissionsController.java
  dinky-admin/src/main/java/org/dinky/controller/SavePointsController.java
  dinky-admin/src/main/java/org/dinky/controller/SchedulerController.java
  dinky-admin/src/main/java/org/dinky/controller/StudioController.java
  dinky-admin/src/main/java/org/dinky/controller/SuggestionController.java
  dinky-admin/src/main/java/org/dinky/controller/SysConfigController.java
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskVersionController.java
  dinky-admin/src/main/java/org/dinky/controller/TenantController.java
  dinky-admin/src/main/java/org/dinky/controller/TokenController.java
  dinky-admin/src/main/java/org/dinky/controller/ToolsController.java
  dinky-admin/src/main/java/org/dinky/controller/UDFController.java
  dinky-admin/src/main/java/org/dinky/controller/UDFTemplateController.java
  dinky-admin/src/main/java/org/dinky/controller/UserController.java
  dinky-admin/src/main/java/org/dinky/service/UserService.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/pages/Other/PersonCenter/index.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: Optimization

#3406 [Fix] fix resource tree cannot refresh
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
Labels: Bug

#3392 [Feature] Add the functionality to automatically retrieve the latest highly available JobManager address
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
  dinky-common/src/main/java/org/dinky/data/enums/GatewayType.java
  dinky-common/src/main/java/org/dinky/data/enums/HaModeEnum.java
  dinky-gateway/src/main/java/org/dinky/gateway/AbstractGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/Gateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: New Feature

#3407 [Optimization][web] Optimize login page prompts
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: Optimization

#3412 [Bug]Fix openapi bug
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
Labels: Bug

#3413 [Optmize] Remove unuse log
  dinky-web/jest.config.ts
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/Metrics/JobMetricsList/index.tsx
  dinky-web/src/pages/Other/Redirect/index.tsx
Labels: Optimization

#3423 [Feature] Add gc startup parameters and Support configuration DINKY_HOME
  dinky-admin/src/main/resources/log4j2.xml
  dinky-web/src/pages/DataStudio/HeaderContainer/PushDolphin/function.tsx
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/types/Studio/data.d.ts
  script/bin/auto.sh
Labels: New Feature

#3429 [Fix]fix git bug
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/utils/GitRepository.java
  dinky-admin/src/main/resources/application.yml
  pom.xml
Labels: Bug

#3349 [Optimization] optimizing the construction of cdcsource out of order results in incorrect recovery from the savepoint
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/AbstractSqlSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/doris/DorisSchemaEvolutionSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/kafka/KafkaSinkJsonBuilder.java
  dinky-common/src/main/java/org/dinky/data/model/Schema.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
Labels: Optimization

#3433 [Optimization] Description of configuration items for optimizing resource allocation
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#3439 [Bug]fix flink cdc task lost sql in app mode
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
Labels: Bug

#3443 [Optimization] Optimizing replication types for resource paths
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/function.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/constants.tsx
Labels: Optimization

#3442 [Feature] Implementing Yarn mode cluster configuration supports configuring the rs protocol
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/ApplicationConfig/index.tsx
  docs/docs/user_guide/register_center/cluster_manage.md
Labels: New Feature
