Repository DataLinkDC/dinky, pull requests merged in 2024-07, with the labels that each got.

#3622 Fix Job error alert, remove sqlite unuse import
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/utils/SqliteUtil.java
Labels: Bug

#3626 [Bug][Core]Fix jar task bug
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: Bug

#3630 [Feature] New Home
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/data/typehandler/ListTypeHandler.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/metrics/MetricsTotal.java
  dinky-common/src/main/java/org/dinky/data/metrics/SystemInfo.java
  dinky-web/config/routes.ts
  dinky-web/package.json
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/MiddleContainer/function.tsx
  dinky-web/src/pages/DevOps/JobDetail/AlertHistory/components/AlertHistoryList/index.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/StatisticsCard.tsx
  dinky-web/src/pages/Home/DevOverView/DevHeatmap/index.tsx
  dinky-web/src/pages/Home/DevOverView/ResourceView/index.tsx
  dinky-web/src/pages/Home/DevOverView/TaskDialectRadar/index.tsx
  dinky-web/src/pages/Home/DevOverView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobErrorView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobFinishedView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobRecoveryView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobRunView/index.tsx
  dinky-web/src/pages/Home/JobOverView/JobStatusPie/index.tsx
  dinky-web/src/pages/Home/JobOverView/LoadScoreGauge/index.tsx
  dinky-web/src/pages/Home/JobOverView/index.tsx
  dinky-web/src/pages/Home/components/BatchStreamProportion/index.tsx
  dinky-web/src/pages/Home/components/FastLink/FastLink.tsx
  dinky-web/src/pages/Home/components/MyWorker/MyWorker.tsx
  dinky-web/src/pages/Home/components/OSMetrics/OSMetrics.tsx
  dinky-web/src/pages/Home/components/WorkerHeader/WorkHeader.tsx
  dinky-web/src/pages/Home/constants.tsx
  dinky-web/src/pages/Home/index.tsx
  dinky-web/src/pages/Home/service.ts
  dinky-web/src/pages/Home/util.ts
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/Studio/data.d.ts
  dinky-web/src/utils/function.tsx
  pom.xml
Labels: New Feature

#3632 [Doc]add nginx doc
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3634 [Feature] Fix Home Page Link
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-web/src/pages/Home/components/FastLink/FastLink.tsx
  dinky-web/src/pages/Home/components/MyWorker/MyWorker.tsx
  dinky-web/src/pages/Home/index.tsx
Labels: Fixed

#3643 [Feature]add metrics delete on write
  dinky-admin/src/main/java/org/dinky/context/MetricsContextHolder.java
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/utils/SqliteUtil.java
Labels: New Feature

#3641 [Feature] Support paimon Datasource
  dinky-admin/src/main/java/org/dinky/controller/DataSourceController.java
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/model/CustomConfig.java
  dinky-common/src/main/java/org/dinky/data/model/QueryData.java
  dinky-common/src/main/java/org/dinky/data/model/Table.java
  dinky-core/pom.xml
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/ClusterConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/config/FlinkConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-gateway/src/test/java/org/dinky/gateway/model/FlinkClusterConfigTest.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/enums/DriverType.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
  dinky-metadata/dinky-metadata-paimon/pom.xml
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/config/CatalogType.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/config/FileSystemType.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/config/PaimonConfig.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/convert/PaimonTypeConvert.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/driver/PaimonDriver.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/query/PaimonQuery.java
  dinky-metadata/dinky-metadata-paimon/src/main/resources/META-INF/services/org.dinky.metadata.driver.Driver
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/driver/PostgreSqlDriver.java
  dinky-metadata/pom.xml
  dinky-web/src/components/Icons/DBIcons.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SQLQuery/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/ColumnInfo/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/GeneralJdbcDesc/GeneralJdbcDesc.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/PaimonDesc/PaimonDesc.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/TableInfo/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceView/GeneralJdbc/JdbcSourceForm.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceView/GeneralJdbc/PaimonSourceForm.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/constants.ts
  dinky-web/src/pages/RegCenter/DataSource/components/function.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/RegCenter/data.d.ts
  pom.xml
Labels: New Feature

#3661 [Bug] Fix fonted NPE on Upgrade
  dinky-web/config/routes.ts
  dinky-web/src/pages/Dashboard/DashboardLayout/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/JobConfigInfo.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
Labels: Bug

#3665 [Bug] Fix paimon metadata package
  dinky-app/dinky-app-base/pom.xml
  dinky-assembly/src/main/assembly/package.xml
Labels: Bug

#3666 [Fix] Fix the issue where Flink fails to fetch the latest high availability address when it is defined in custom configurations
  dinky-gateway/src/main/java/org/dinky/gateway/AbstractGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: Bug

#3671 [Fix] Fix the issue of 'Write end dead'
  dinky-admin/src/main/java/org/dinky/context/SqlGatewayWsContext.java
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/Terminal/TerminalContent.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
Labels: Bug

#3672 [BugFix] [Dashboard] Fix the bug displayed by dashboard
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-web/src/components/Flink/MetricsFilter/MetricsFilter.tsx
  dinky-web/src/pages/Dashboard/DashboardLayout/index.less
  dinky-web/src/pages/Dashboard/DashboardLayout/index.tsx
  dinky-web/src/pages/Dashboard/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/index.tsx
Labels: Bug

#3675 [Feature] add 1.1.0 upgrade sql file
  dinky-admin/src/main/resources/db/migration/h2/V20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/R20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/R20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V20240729.1.1.0__release.sql
Labels: New Feature

#3679 [Fix] Fix the permission issue of the Kanban board
  dinky-admin/src/main/resources/db/migration/h2/V20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/R20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/R20240729.1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V20240729.1.1.0__release.sql
  dinky-web/src/pages/Dashboard/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
Labels: Bug

#3677 [Fix] Fix the jumping and internationalization issues in the workbench
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/Home/components/MyWorker/MyWorker.tsx
  dinky-web/src/pages/Home/components/WorkerHeader/WorkHeader.tsx
  dinky-web/src/pages/Home/util.ts
Labels: Bug
