Repository DataLinkDC/dinky, pull requests merged in 2024-02, with the labels that each got.

#3121 Optimized jdbc get data exception throw
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/constant/DorisConstant.java
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
  dinky-web/src/services/constants.tsx
Labels: Optimization

#3124 [BugFix][Flink]fix some python bug
  dinky-admin/src/main/resources/dinky-loader/FlinkConfClass
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-base/src/main/java/org/apache/flink/python/PythonOptions.java
  dinky-common/pom.xml
  pom.xml
Labels: Bug

#3123 [Optimization]Cluster config restore Test Connection
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/index.tsx
Labels: Optimization

#3126 [Refactor][web] refactor devops overview list layout
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/index.tsx
Labels: Refactor

#3128 [Fix]Fix task err pop Model
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/constants.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
Labels: Bug

#3131 [Fix]Fix job list can not Scroll
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/index.tsx
Labels: Bug

#3130 [Improvement] Add graceful shutdown of services
  .github/workflows/add-assignees.yml
  .github/workflows/issue-check-inactive.yml
  dinky-admin/src/main/resources/application.yml
Labels: Optimization

#3129 [BugFix] fix resources
  dinky-client/dinky-client-base/src/main/java/org/dinky/url/ResourceFileSystemFactory.java
Labels: Bug

#3134 [Fix]Fix app mode Global Varible Exception
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
Labels: Bug

#3135 Fix k8s can not start up
  dinky-client/dinky-client-base/src/main/java/org/dinky/url/ResourceFileSystem.java
Labels: Bug

#3136 Fix openapi token bug
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
Labels: Bug

#3138 [BugFix][Web] Fix web page show
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-web/src/components/Sidebar/MovableSidebar/index.tsx
Labels: Bug

#3137 [Feature] [Resources] New resource center added, synchronization of HDFS information
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/HdfsResourceManager.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/LocalResourceManager.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/OssResourceManager.java
  pom.xml
Labels: New Feature

#3139 [Feature][UDF] udf develops modification logic
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  pom.xml
Labels: New Feature

#3141 [Fix-2101] Fix SqlServer timestamp convert into String
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/convert/SqlServerTypeConvert.java
Labels: Bug

#3142 [Optimization-3090] CDCSOURCE supports earliest-offset and timestamp scanStartupMode
  .github/workflows/docker_build.yaml
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
  dinky-flink/dinky-flink-1.18/pom.xml
  pom.xml
Labels: Optimization

#3143 [Optmization]Removed the save point path uniqueness restriction from the task table
  script/sql/dinky-mysql.sql
Labels: Optimization

#3144 [Fix] Fix UDF task publish NPE
  dinky-admin/src/main/java/org/dinky/data/dto/TaskSaveDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/UDFUtils.java
Labels: Bug

#3154 [Optimization]optimization resource manager
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/HdfsResourceManager.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/LocalResourceManager.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/impl/OssResourceManager.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#3158 Dinky classpath add FLINK_HOME
  script/bin/auto.sh
Labels: Optimization

#3159 [Fix-3157] fix jar task have no history
  dinky-web/src/pages/DataStudio/route.tsx
Labels: Bug

#3161 [Feature-3160] Delete separator configuration item
  dinky-admin/src/test/java/org/dinky/utils/SqlUtilTest.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: New Feature

#3162 [BugFix] [CDC] Fix the problem of 1.18 CDC Plus introduced DORIS
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/doris/DorisSinkBuilder.java
  dinky-core/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
Labels: Bug

#3165 [BugFix][Jar] Fix Flink jar submission and set parallelism failure issue
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  docs/docs/extend/expand_statements/execute_jar.md
Labels: Bug

#3170 [Optimization] remove some menu
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: Optimization

#3175 [Fix-3174] [admin] Fix flink sql separator
  dinky-core/src/main/java/org/dinky/constant/FlinkSQLConstant.java
Labels: Bug

#3169 [Build] [pom] upgrade flink1.18 flink-connector-jdbc
  dinky-flink/dinky-flink-1.18/pom.xml
Labels: Optimization

#3178 [Optimization] optimize some image addresses as relative paths
  dinky-admin/src/main/resources/application-h2.yml
  dinky-web/config/config.ts
  dinky-web/config/defaultSettings.ts
  dinky-web/src/app.tsx
  dinky-web/src/components/Footer/index.tsx
  dinky-web/src/models/Sse.tsx
  dinky-web/src/pages/Other/Login/LoginForm/MainWithStyle/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#3183 [Optimization] modify default password
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/docs/deploy_guide/upgrade/upgrade_075to100.md
  docs/docs/developer_guide/local_debug.md
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: Optimization

#3181 [Fix] fix doris datasource get sql ddl and sql query maybe npe
  dinky-admin/src/main/java/org/dinky/data/model/SqlGeneration.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/driver/DorisDriver.java
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/GenSQL/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SQLQuery/index.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: Bug

#3180 [Fix] fix bool maybe NPE
  dinky-admin/src/main/java/org/dinky/data/dto/APIExecuteSqlDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/APIExplainSqlDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/AbstractStatementDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/StudioMetaStoreDTO.java
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: Bug

#3187 [Fix] fix mybatis fill value error
  dinky-admin/src/main/java/org/dinky/data/model/ClusterInstance.java
  dinky-admin/src/main/java/org/dinky/data/model/DataBase.java
  dinky-admin/src/main/java/org/dinky/data/model/TaskVersion.java
  dinky-admin/src/main/java/org/dinky/data/model/job/JobHistory.java
  dinky-admin/src/main/java/org/dinky/data/model/job/JobInstance.java
  dinky-admin/src/main/java/org/dinky/mybatis/handler/DateMetaObjectHandler.java
  dinky-admin/src/main/java/org/dinky/mybatis/properties/MybatisPlusFillProperties.java
Labels: Bug

#3186 [Fix] fix h2 alert_instance table filed type json error
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
Labels: Bug

#3184 [Fix] fix route can not render
  dinky-web/config/routes.ts
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/zh-CN/menu.ts
Labels: Bug

#3185 [Fix] fix ds doc error
  docs/docs/practical_guide/Integration_practice/dinky_integration_ds.md
Labels: Bug

#3188 [Featue] support resource file copy path
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/function.tsx
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_ddl.sql
Labels: New Feature

#3191 [Doc]Optimized deployment documentation
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3192 [Feature] support import ldap user search
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/compontents/LoadUser.tsx
Labels: New Feature

#3193 [Optimized ]Optimized sse connect
  dinky-admin/src/main/java/org/dinky/context/SseSessionContextHolder.java
Labels: Optimization

#3198 [BugFix] [Metadata] fix metadata cache And add an expiration date
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCache.java
  dinky-admin/src/main/java/org/dinky/controller/DataSourceController.java
  dinky-common/src/main/java/org/dinky/data/paimon/CacheData.java
Labels: Bug

#3197 [Optimization] move web some url to constants
  dinky-web/src/pages/DataStudio/BottomContainer/Tools/JsonToSql/service.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/service.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/service.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/service.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/function.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#3202 [Fix] Fix k8s application type can not render
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/components/EditJobInstanceForm.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/BaseConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/InstanceForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/constants.ts
Labels: Bug

#3203 [Fix]Fix offline task NPE
  dinky-admin/src/main/java/org/dinky/data/model/ext/JobAlertData.java
Labels: Bug
