Repository DataLinkDC/dinky, pull requests merged in 2024-11, with the labels that each got.

#3897 [Feature-3893][core][admin][web] Flink SQL task Support insert result preview
  dinky-admin/src/main/java/org/dinky/data/dto/TaskDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/SqlType.java
  dinky-core/src/main/java/org/dinky/connector/mock/sink/MockDynamicTableSink.java
  dinky-core/src/main/java/org/dinky/connector/mock/sink/MockDynamicTableSinkFactory.java
  dinky-core/src/main/java/org/dinky/connector/mock/sink/MockSinkFunction.java
  dinky-core/src/main/java/org/dinky/data/result/MockResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/MockSinkResult.java
  dinky-core/src/main/java/org/dinky/data/result/ResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResult.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/PreViewConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/function.tsx
  dinky-web/src/pages/DataStudioNew/CenterTabContent/TaskConfig/index.tsx
  dinky-web/src/pages/DataStudioNew/Toolbar/Service/Result/index.tsx
Labels: New Feature

#3907 [Optimization-3906][web] Optimize debug task to preview data
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/SqlType.java
  dinky-core/src/main/java/org/dinky/data/result/ResultBuilder.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
  dinky-core/src/main/java/org/dinky/job/Job.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobResult.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-web/src/pages/DataStudioNew/CenterTabContent/SqlTask.tsx
  dinky-web/src/pages/DataStudioNew/Toolbar/Service/Result/index.tsx
Labels: Optimization

#3904 [Web]Optimized the new UI
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/PreViewConfig/FlinkSql/index.tsx
  dinky-web/src/pages/DataStudio/function.tsx
  dinky-web/src/pages/DataStudioNew/CenterTabContent/TaskConfig/index.tsx
  dinky-web/src/pages/DataStudioNew/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudioNew/Toolbar/index.less
  dinky-web/src/pages/DataStudioNew/Toolbar/index.tsx
  dinky-web/src/pages/DataStudioNew/css/index.less
  dinky-web/src/pages/DataStudioNew/index.less
  dinky-web/src/pages/DataStudioNew/model.tsx
Labels: Optimization

#3875 [BugFix][FlinkSQL] V1.1.0 version Keberos bug related repair, SQL SET value does not take effect, etc
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/kafka/KafkaSinkJsonBuilder.java
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
  dinky-core/src/main/java/org/dinky/constant/FlinkConstant.java
  dinky-core/src/main/java/org/dinky/executor/ExecutorConfig.java
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/JobOperator.tsx
Labels: Bug

#3910 [Optimization-3909][core] Optimize FlinkDDL execution sequence
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/AbstractOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ExtendOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ddl/CustomSetOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-common/src/main/java/org/dinky/data/result/SqlExplainResult.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobParam.java
  dinky-core/src/main/java/org/dinky/job/builder/JobDDLBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
Labels: Optimization

#3915 [doc] Doc of debug data preview update
  docs/docs/user_guide/studio/flink_sql_task_devlop.md
Labels: Doc

#3920 [Refactor][Web]Refactor result query
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/TaskConfig/index.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/index.less
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/index.tsx
  dinky-web/src/pages/DataStudio/type.ts
Labels: Refactor

#3922 [Optimize][Web]Add footer last update time
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/FooterContainer/function.ts
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
Labels: Optimization

#3926 [Optimization-3925][web] Optimize the style of IDE
  README.md
  README_zh_CN.md
  dinky-web/src/components/Icons/CodeLanguageIcon.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/TaskConfig/ProFormFlinkUdfConfig.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Project/JobModal/components/TemplateSelect.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Project/function.tsx
  dinky-web/src/pages/DataStudio/css/index.less
  dinky-web/src/pages/DataStudio/index.tsx
  docs/src/pages/index.tsx
Labels: Optimization

#3921 [admin] Add websocket PING PONG
  dinky-admin/src/main/java/org/dinky/data/vo/SseDataVo.java
  dinky-admin/src/main/java/org/dinky/ws/GlobalWebSocket.java
  dinky-web/src/models/UseWebSocketModel.tsx
Labels: Optimization

#3930 [BugFIx][Docs] Fix the issue of incomplete dependencies in the docs module
  docs/package.json
Labels: Bug, Doc

#3931 [Optimize][Web]Optimize datastudio theme
  dinky-web/src/pages/DataStudio/CenterTabContent/index.less
  dinky-web/src/pages/DataStudio/css/index.less
Labels: Optimization

#3934 [BugFix][Web]Close the data development page, floating button
  dinky-web/src/pages/DataStudio/ContentLayout.tsx
Labels: Bug

#3933 [Optimization-3932][cdc] Optimize CDCSOURCE and support sink print and mock
  dinky-admin/src/main/java/org/dinky/service/task/FlinkSqlTask.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/SinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/convert/DataTypeConverter.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/kafka/KafkaSinkJsonBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/print/PrintSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/AbstractSqlSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/catalog/SQLCatalogSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/resources/META-INF/services/org.dinky.cdc.SinkBuilder
  dinky-cdc/dinky-cdc-core/src/test/java/org/dinky/cdc/SinkBuilderTest.java
  dinky-cdc/dinky-cdc-core/src/test/java/org/dinky/cdc/convert/DataTypeConverterTest.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/doris/DorisSchemaEvolutionSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/doris/DorisSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/java/org/dinky/cdc/kafka/KafkaSinkBuilder.java
  dinky-cdc/dinky-cdc-plus/src/main/resources/META-INF/services/org.dinky.cdc.SinkBuilder
  dinky-common/src/main/java/org/dinky/data/model/FlinkCDCConfig.java
  dinky-core/src/main/java/org/dinky/connector/mock/sink/MockSinkFunction.java
  dinky-core/src/main/java/org/dinky/constant/FlinkConstant.java
  dinky-core/src/main/java/org/dinky/data/result/AbstractResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/MockResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/MockResultRunnable.java
  dinky-core/src/main/java/org/dinky/data/result/ResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResult.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResultBuilder.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/main/java/org/dinky/job/runner/JobPipelineRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSqlRunner.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-flink/dinky-flink-1.19/pom.xml
  dinky-flink/dinky-flink-1.20/pom.xml
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/components/JobDetailInfoModel/ErrorMsgInfo.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/components/JobDetailInfoModel/PreViewData.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/components/JobDetailInfoModel/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
Labels: Optimization

#3937 [Optimization][Web] Optimized offline button icon
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/components/JobDetailInfoModel/PreViewData.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/components/JobDetailInfoModel/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/ExecutionHistory/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
Labels: Optimization

#3940 [Optimize][Doc] Update images in Quick Start documentation
  docs/docs/get_started/quick_experience.md
Labels: Optimization

#3943 [Optimization-3942][web] Optimize web icon
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Project/function.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
Labels: Optimization

#3947 [Optimization-3946][core] Optimize the status of runing task and beautify UI
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/ws/topic/TaskRunInstance.java
  dinky-common/src/main/java/org/dinky/data/job/JobStatement.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobStatementPlan.java
  dinky-core/src/test/java/org/dinky/job/JobStatementPlanTest.java
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/BaseConfig/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/index.tsx
Labels: Optimization

#3949 [Feature][Web]Flink jar add form
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/data/vo/FlinkJarSqlConvertVO.java
  dinky-admin/src/main/resources/templates/executeJar.sql
  dinky-client/dinky-client-base/src/main/java/org/dinky/data/model/JarSubmitParam.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ExecuteJarParseStrategyUtil.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/ExecuteJarParseStrategy.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-core/src/main/java/org/dinky/job/runner/JobJarRunner.java
  dinky-web/package-lock.json
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/GlobalVariable/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/TableData/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
  dinky-web/src/pages/DataStudio/components/RunToolBarButton/index.tsx
  dinky-web/src/pages/DataStudio/service.tsx
  dinky-web/src/pages/DataStudio/type.ts
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#3948 [Feature-3751][*] Release 1.2.0 (LTS)
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
  README_zh_CN.md
  dinky-web/src/pages/Other/Welcome/WelcomeItem/WelcomItem.tsx
  docs/download/dinky-1.2.0.md
  docs/download/download.md
  docs/src/pages/index.tsx
  images/v1-2/data-debug.png
  images/v1-2/datastudio.png
  images/v1-2/devops.png
  images/v1-2/metrics.png
  pom.xml
Labels: New Feature

#3952 [Improve] Optimize the logic for constructing role menus.
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
Labels: Optimization

#3956 [bug]fix k8s form ingresss bug
  dinky-gateway/src/main/java/org/dinky/gateway/config/K8sConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
Labels: Bug

#3955 [Optimize][Flink]Optimize DInky without Flink dependency, unable to start, etc
  dinky-admin/src/main/java/org/dinky/controller/FlinkController.java
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
Labels: Optimization

#3965 [Optimize][Web]Click the Tasks tab to switch to Service Synchronization
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/data.d.tsx
  dinky-web/src/pages/DataStudio/index.tsx
Labels: Optimization

#3966 [Bug] Fix the route redirection error on the welcome page
  dinky-web/src/pages/Other/Welcome/WelcomeItem/FinishPage.tsx
Labels: Bug

#3967 [BugFix][Flink]Fix the Flink task to submit the session mode.
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/job/runner/JobDDLRunner.java
Labels: Bug

#3970 [Bug][Web]Fix web npe
  dinky-web/package-lock.json
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
Labels: Bug

#3960 [Optimization-3959][core] Optimize submit task print error log
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/factory/CatalogueTreeSortFactory.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UDFServiceImpl.java
  dinky-app/dinky-app-1.20/pom.xml
  dinky-app/dinky-app-base/pom.xml
  dinky-assembly/src/main/assembly/package.xml
  dinky-core/pom.xml
  dinky-core/src/main/java/org/dinky/data/result/MockResultRunnable.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/runner/JobDDLRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobPipelineRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSetRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSqlRunner.java
  dinky-core/src/main/java/org/dinky/trans/Operations.java
  dinky-function/pom.xml
  dinky-function/src/main/java/org/dinky/function/FlinkUDFDiscover.java
  dinky-gateway/pom.xml
  dinky-metadata/dinky-metadata-paimon/pom.xml
  pom.xml
Labels: Optimization

#3972 []Optimize][Web]Optimize flink jar form select
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: Optimization

#3978 [Optimize][Pom]Optimize app package size
  dinky-app/dinky-app-1.15/pom.xml
  dinky-app/dinky-app-1.16/pom.xml
  dinky-app/dinky-app-1.17/pom.xml
  dinky-app/dinky-app-1.18/pom.xml
  dinky-app/dinky-app-1.19/pom.xml
  dinky-app/dinky-app-1.20/pom.xml
  dinky-common/src/main/java/org/dinky/serializer/LocalDateTimeDeserializer.java
  dinky-common/src/main/java/org/dinky/serializer/LocalDateTimeSerializer.java
  dinky-common/src/main/java/org/dinky/utils/JsonUtils.java
  dinky-core/src/main/java/org/dinky/job/runner/JobDDLRunner.java
  pom.xml
Labels: Optimization

#3980 [BugFix][web] Fixed an error when using the copy button in the Resource Center
  dinky-web/src/utils/function.tsx
Labels: Bug

#3981 [Feature-3973][*] Release 1.2.0-rc4
  .gitignore
  dinky-admin/src/main/java/org/dinky/init/FlinkHistoryServer.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/convert/DataTypeConverter.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/resource/BaseResourceManager.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/runner/JobPipelineRunner.java
  dinky-function/src/main/java/org/dinky/function/FlinkUDFDiscover.java
  dinky-function/src/main/java/org/dinky/function/util/Reflections.java
  docs/download/dinky-1.2.0.md
  pom.xml
Labels: New Feature

#3982 [Optimization][Data Development] variable suggestion optimization
  dinky-admin/src/main/java/org/dinky/service/impl/SuggestionServiceImpl.java
Labels: Optimization
