Repository DataLinkDC/dinky, pull requests merged in 2024-03, with the labels that each got.

#3205 [Feature] [Flink SQL] Added ADD FILE syntax not only submits JAR to Java ClassPath
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCache.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/SqlType.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/ddl/AddFilerOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/AddFileSqlParseStrategy.java
  dinky-common/src/main/java/org/dinky/context/FlinkUdfPathContextHolder.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-core/src/main/java/org/dinky/utils/DinkyClassLoaderUtil.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: New Feature

#3210 [Fix] fix h2 ddl job_history table filed length error
  dinky-admin/src/main/resources/db/db-h2-ddl.sql
Labels: Bug

#3211 [Feature] Add addfile syntax document
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  docs/docs/extend/expand_statements/add_file_statement.md
  docs/docs/extend/expand_statements/add_jar_statement.md
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: Doc, New Feature

#3213 [Doc] added demo env doc
  docs/docs/get_started/quick_experience.md
  docs/src/pages/index.js
Labels: Doc

#3214 [Feature] Realease-1.0.0
  docs/download/dinky-1.0.0.md
  pom.xml
Labels: New Feature

#3219 fix-download-doc
  docs/download/download.md
Labels: Bug

#3226 [Fix] fix create task form render error
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
Labels: Bug

#3227 [Optimizing] Optimizing URLs to Constants
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#3232 [Doc]fix doc pv
  docs/docusaurus.config.js
  docs/src/pages/index.js
Labels: Doc

#3229 [Fix] fix catalog page npe
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
Labels: Bug

#3230 [Optimization] optimize startup scripts
  script/bin/auto.sh
Labels: Optimization

#3231 [Optimization] Prompt for optimizing password errors
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
Labels: Optimization

#3238 [Doc] Add built-in variable document for cdcsource
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: Doc

#3239 [Doc]Optimize document version
  docs/docs/get_started/overview.md
  docs/docusaurus.config.js
  docs/download/download.md
  docs/i18n/en/docusaurus-plugin-content-docs-download/current.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs-download/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
Labels: Doc

#3256 [BugFix]fix some udf bug
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: Bug

#3251 [Doc] Update flink_sql_task_devlop.md
  docs/docs/user_guide/studio/flink_sql_task_devlop.md
Labels: Doc

#3245 [Optimization] Optimizing tag icon rendering spacing for data development
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
Labels: Optimization

#3252 [Optimization] Turn off automatic sentence preview
  dinky-web/src/components/CustomEditor/CodeEdit/function.tsx
  dinky-web/src/components/CustomEditor/CodeEdit/index.tsx
Labels: Optimization

#3253 [Fix] Fix quick navigation routing error
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/MiddleContainer/QuickGuide/constant.tsx
Labels: Bug

#3233 [Bug]fix "ADD JAR" at s3 can not config ak&sk
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  docs/docs/faq.md
Labels: Bug

#3254 [Fix] Fix token may get empty and cause page crash
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
Labels: Bug

#3259 [Improvement] Optimize expression variable replacement methods
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/SysConfigService.java
  dinky-admin/src/main/java/org/dinky/service/impl/SysConfigServiceImpl.java
  dinky-admin/src/main/resources/dinky-loader/ExpressionVariableClass
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-common/src/main/java/org/dinky/context/EngineContextHolder.java
  dinky-common/src/main/java/org/dinky/data/constant/CommonConstant.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/java/org/dinky/utils/StringUtil.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: Optimization

#3260 [Improvement] Optimize selection prompt information when querying in yarn application mode; Added Run button to check select execute
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: Optimization

#3263 [Fix] fix the decimal precision of postgres transform
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/utils/FlinkStatementUtil.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
Labels: Bug

#3264 [Fix] fix modal cannot close
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/function.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/index.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFTemplate/TemplateModal/index.tsx
Labels: Bug

#3265 [Optimization]Optimize the environment check of git project build
  dinky-admin/src/main/java/org/dinky/sse/git/HeadStepSse.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#3266 [Fix] Fix unrecognized global variables defined by registry in application mode
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/db/DBUtil.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-common/src/main/java/org/dinky/data/app/AppGlobalVariable.java
Labels: Bug

#3270 [Fix] fix proxy url is error
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
Labels: Bug

#3271 [Optimization] [web] move url to constants
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/service.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#3275 [Optimization][admin] NULL may be used when optimizing heartbeat detection of cluster instances
  dinky-admin/src/main/java/org/dinky/assertion/DinkyAssert.java
Labels: Optimization

#3276 [Document]Fix cdcsource practice documents for Mysql and PostgreSQL
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2mysql.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2pg.md
Labels: Doc

#3279 [Fix] fix array out of bounds
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: Bug

#3283 [Doc]Overview of entire library synchronization: update dinky-client-${version}.jar path
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: Doc

#3287 [Feature] Release-1.0.1
  docs/download/dinky-1.0.1.md
  docs/download/download.md
  pom.xml
Labels: New Feature

#3289 [HotFix] hotfix auto.sh
  script/bin/auto.sh
Labels: Optimization

#3291 [Fix] Fix the global variable recognition order issue in the application mode
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
Labels: Bug

#3296 [Optimization] Optimization start scripts
  script/bin/auto.sh
Labels: Optimization

#3297 [Optimization] Optimization setting page overflow
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
Labels: Optimization

#3295 [Optimization] Optimization udf manage tips
  dinky-web/src/pages/RegCenter/UDF/components/UDFRegister/index.tsx
  dinky-web/src/pages/RegCenter/UDF/index.tsx
Labels: Optimization

#3303 [Fix] fix possible 404 in redirect routing
  dinky-web/src/pages/Other/Login/function.tsx
Labels: Bug

#3302 [Doc] modify expression variable extension document
  docs/docs/extend/function_expansion/global_var_ext.md
Labels: Doc

#3298 [Fix] fix datasource heartbeat error
  dinky-admin/src/main/java/org/dinky/controller/DataSourceController.java
  dinky-admin/src/main/java/org/dinky/service/DataBaseService.java
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Bug

#3272 [Fix] fix some component cannot render
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.1.0_schema/mysql/dinky_dml.sql
  script/sql/upgrade/1.1.0_schema/postgre/dinky_dml.sql
Labels: Bug

#3277 [Optimization] optimization execute jar params parse
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-client/dinky-client-base/src/test/java/org/dinky/trans/dml/ExecuteJarOperationTest.java
Labels: Optimization

#3313 [Doc][faq] add JDBC tinyint type conversion failure log faqs
  docs/docs/faq.md
Labels: Doc

#3316 [Bug] Fix vaible parse err missing tips
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
Labels: Bug

#3321 [Fix] Fix cursor movement flicker in editor
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
Labels: Bug

#3328 [Doc] support doc home page Carousel component
  docs/package.json
  docs/src/components/Carousel/carousel.module.css
  docs/src/components/Carousel/index.tsx
  docs/src/components/CarouselList/index.tsx
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
Labels: Doc

#3327 [Fix][Admin] Fix the null pointer exception in the user list of the role
  dinky-admin/src/main/java/org/dinky/service/impl/RoleServiceImpl.java
Labels: Bug

#3338 [Bug] fix some k8s bug
  dinky-admin/src/main/resources/dinky-loader/FlinkConfClass
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#3339 [Improvement] Excluding high risk endpoints
  dinky-admin/src/main/resources/application-jmx.yml
Labels: Optimization
