Repository DataLinkDC/dinky, pull requests merged in 2024-01, with the labels that each got.

#2863 [Fix-2776] [admin] fix multi user login with the same token value insert error
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
Labels: bug

#2871 [Document-2870][doc] update download
  docs/download/dinky-1.0.0.md
  docs/download/download.md
Labels: Doc

#2875 [Improve][docs] Upgrade doc's dependencies
  docs/package.json
Labels: Optimization

#2873 [Feature] Support delete metrics layout
  dinky-admin/src/main/java/org/dinky/controller/MonitorController.java
  dinky-admin/src/main/java/org/dinky/service/MonitorService.java
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-web/src/components/CallBackButton/PopconfirmDeleteBtn.tsx
  dinky-web/src/components/Flink/FlinkChart/index.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/JobDetail/JobMetrics/JobChart/JobChart.tsx
  dinky-web/src/pages/Metrics/Job/data.tsx
  dinky-web/src/pages/Metrics/Job/function.tsx
  dinky-web/src/pages/Metrics/Job/index.tsx
  dinky-web/src/pages/Metrics/JobMetricsList/data.tsx
  dinky-web/src/pages/Metrics/JobMetricsList/index.tsx
  dinky-web/src/pages/Metrics/index.tsx
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#2886 [Optimization-2885][web] Automatically switch console and result tags
  dinky-web/src/components/Flink/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/LineageGraph/lineage-dag-ext.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenModalForm/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/JobExecHistory/components/JobDetailInfoModel/JobConfigInfo.tsx
  dinky-web/src/pages/DataStudio/FooterContainer/JobRunningModal/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/RegCenter/GitProject/constans.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
Labels: Optimization

#2889 [Doc] Delete docs and added some docs and modify docs struct
  docs/docs/deploy_guide/upgrade.md
  docs/docs/developer_guide/contribution/code_format.md
  docs/docs/developer_guide/openapi.md
  docs/docs/extend/expand_statements/add_jar_statement.md
  docs/docs/extend/expand_statements/create_temporal_function.md
  docs/docs/extend/expand_statements/execute_jar.md
  docs/docs/extend/expand_statements/print_table.md
  docs/docs/extend/expand_statements/variable_statement.md
  docs/docs/practical_guide/Integration_practice/dinky_integration_ds.md
  docs/docs/user_guide/register_center/datasource_manage.md
  docs/docs/user_guide/register_center/document_manager.md
  docs/docs/user_guide/register_center/udf.md
  docs/docs/user_guide/studio/catalog_manage.md
  docs/docs/user_guide/studio/development_control/_category_.json
  docs/docs/user_guide/studio/development_control/component_introduce.md
  docs/docs/user_guide/studio/development_control/function_introduce.md
  docs/docs/user_guide/studio/job_config_submit.md
  docs/docs/user_guide/studio/job_import_export.md
  docs/docs/user_guide/studio/job_log.md
  docs/docs/user_guide/studio/job_monitoring.md
  docs/docs/user_guide/studio/metadata.md
  docs/docs/user_guide/studio/studio_overview.md
  docs/docs/user_guide/studio/udf_develop/_category_.json
  docs/docs/user_guide/studio/udf_develop/intro.md
  docs/docs/user_guide/studio/udf_develop/quick_use/Java&Scala.md
  docs/docs/user_guide/studio/udf_develop/quick_use/Python.md
  docs/docs/user_guide/studio/udf_develop/quick_use/_category_.json
  docs/docs/user_guide/studio/udf_develop/template_intro.md
  docs/docs/user_guide/system_setting/global_settings/resource_setting.md
  docs/package.json
  docs/versioned_sidebars/version-0.6-sidebars.json
Labels: Doc

#2888 [Feature-2880][admin,web] Support autoregister cluster stop function and Clusters with jobs in progress cannot be deleted
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/components/CallBackButton/PopconfirmDeleteBtn.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/services/endpoints.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
Labels: New Feature

#2896 [Fix-2895]Fix Presto Password is required
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceModal/DataSourceProForm/index.tsx
Labels: bug

#2901 [Optimization] [web] Improve translation and fix typo
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
Labels: Optimization

#2904 [Bug] [App] Fix Flinkjar's operations in the Application mode, Checkpoint does not take effect
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  pom.xml
Labels: bug

#2905 Fix [admin] get task checkpoint & checkpointConfigInfo parsed failed when task not configura checkpoint option
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
Labels: bug

#2906 fix: execute jar with no space follow
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/parse/ExecuteJarParseStrategy.java
  dinky-client/dinky-client-base/src/test/java/org/dinky/trans/parse/ExecuteJarParseStrategyTest.java
Labels: bug

#2909 [Doc]Add a Quick Start document
  docs/docs/get_started/quick_experience.md
Labels: Doc

#2910 [Fix] Fix dependency conflicts
  dinky-alert/dinky-alert-base/pom.xml
  dinky-alert/dinky-alert-email/pom.xml
  dinky-alert/dinky-alert-sms/pom.xml
Labels: bug

#2912 [Fix-#]Shaded paimon
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/dinky/configure/cache/PaimonCache.java
  dinky-admin/src/main/java/org/dinky/service/impl/MonitorServiceImpl.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonTypeUtil.java
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
Labels: bug

#2913 [Doc] added some docs and modify some doc struct
  docs/docs/deploy_guide/compile_deploy.md
  docs/docs/deploy_guide/compile_deploy.mdx
  docs/docs/deploy_guide/upgrade.md
  docs/docs/deploy_guide/upgrade/_category_.json
  docs/docs/deploy_guide/upgrade/upgrade_075to100.md
  docs/docs/deploy_guide/upgrade/upgrade_overview.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_faq.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2ck.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2dinkycatalog.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2doris.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2hivecatalog.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2hudi.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2kafka.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2multiplesink.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2mysql.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2oracle.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2paimon.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2pg.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2print.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2starrocks.md
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
  docs/docs/user_guide/devops_center/job_overview.md
  docs/docs/user_guide/studio/studio_overview.md
  docs/download/dinky-1.0.0.md
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-theme-classic/navbar.json
  script/sql/upgrade/1.0.0_schema/mysql/dinky_ddl.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: Doc

#2916 [Doc]Optimize document structure and content
  docs/docs/comminicate.md
  docs/docs/deploy_guide/compile_deploy.md
  docs/docs/faq.md
  docs/docs/get_started/quick_start/_category_.json
  docs/docs/get_started/quick_start/dbql_quick_start.md
  docs/docs/get_started/quick_start/flinksql_quick_start.md
  docs/docs/openapi.md
  docs/docs/platform_intro/feature.md
  docs/docs/platform_intro/intro.md
  docs/docs/platform_intro/overview.md
  docs/docs/platform_intro/roadmap.md
  docs/docs/roadmap.md
  docs/docs/thanks.md
  docs/docusaurus.config.js
  docs/i18n/en/docusaurus-theme-classic/footer.json
  docs/i18n/zh/docusaurus-theme-classic/footer.json
Labels: Doc

#2917 [Optimization][admin] optimize task delete logical
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#2920 [Doc] delete error docs
  docs/docs/user_guide/studio/job_config_submit.md
  docs/docs/user_guide/studio/studio_overview.md
  docs/docs/user_guide/studio/udf_develop/_category_.json
  docs/docs/user_guide/studio/udf_develop/intro.md
  docs/docs/user_guide/studio/udf_develop/quick_use/Java&Scala.md
  docs/docs/user_guide/studio/udf_develop/quick_use/Python.md
  docs/docs/user_guide/studio/udf_develop/quick_use/_category_.json
  docs/docs/user_guide/studio/udf_develop/template_intro.md
Labels: Doc

#2918 [Bug]Fix execute jar prejob
  dinky-admin/src/main/java/org/dinky/service/task/FlinkJarSqlTask.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnApplicationGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnPerJobGateway.java
  docs/docs/extend/expand_statements/execute_jar.md
Labels: bug

#2921 [Fix-2919] Fixed the issue where flink configuration is empty when adding/modifying cluster configuration
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
Labels: bug

#2923 [Fix-2898] fix finishtime render error
  dinky-web/src/pages/DevOps/JobList/components/JobHistoryList/JobHistoryList.tsx
  dinky-web/src/types/DevOps/data.d.ts
Labels: bug

#2924 [Feature]support codeshow wrap-button
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
Labels: New Feature

#2922 [Doc] Add Studio doc
  docs/docs/extend/expand_statements/execute_jar.md
  docs/docs/get_started/operation_guide.md
  docs/docs/get_started/overview.md
  docs/docs/platform_intro/_category_.json
  docs/docs/platform_intro/overview.md
  docs/docs/user_guide/studio/catalog.md
  docs/docs/user_guide/studio/execute_env_config.md
  docs/docs/user_guide/studio/flink_env_task_devlop.md
  docs/docs/user_guide/studio/flink_sql_task_devlop.md
  docs/docs/user_guide/studio/jdbc_task_devlop.md
  docs/docs/user_guide/studio/studio_overview.md
Labels: Doc

#2928 [Fix] fix savepoint interface 404
  dinky-admin/src/main/java/org/dinky/controller/SavePointsController.java
  dinky-admin/src/main/java/org/dinky/interceptor/TenantInterceptor.java
  dinky-admin/src/main/resources/mapper/SavepointsMapper.xml
  dinky-web/src/pages/DataStudio/RightContainer/SavePoints/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/SavePointTable.tsx
  dinky-web/src/services/endpoints.tsx
Labels: bug

#2930 [Optimization] optimize restart task tips
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/functions.tsx
Labels: Optimization

#2929 [Optimization] When the cluster instance status is healthy, it needs to be stopped first and then deleted.
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#2931 [Fix]the registered session cluster cannot be selected
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: bug

#2933 [Fix] fix submit status bug
  dinky-admin/src/main/java/org/dinky/controller/APIController.java
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-web/src/components/CallBackButton/LoadingBtn.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/FooterContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/function.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/HeaderContainer/service.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DevOps/function.tsx
  dinky-web/src/types/Studio/data.d.ts
Labels: bug

#2940 [Optimized ]Optimized job creation and added template functionality
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/components/TemplateSelect.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/YarnConfig/index.tsx
Labels: Optimization

#2943 [Optimization] optimization the way to obtain versions
  dinky-admin/src/main/java/org/dinky/controller/AdminController.java
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/services/endpoints.tsx
Labels: Optimization

#2941 refactor: CustomEnvironmentImpl
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
Labels: Refactor

#2946 [Doc] Fix bug in cdcsource overview document
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: bug, Doc

#2948 [Doc] correction table-name is a required parameter
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: Doc

#2950 [Fix-2949][web] fix bug of alert instance form change
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/index.tsx
Labels: bug

#2952 [Optimized] Optimized SQL execution
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
Labels: Optimization

#2955 [Feature-2951][*] Release v1.0.0-rc3
  pom.xml
Labels: New Feature

#2954 [Fix] fix added rootmenu can not open form
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
Labels: bug

#2957 Update rc3 download documentation, update contributors
  docs/download/dinky-1.0.0.md
  docs/download/download.md
Labels: Doc

#2958 [Doc] optimize openapi docs
  docs/docs/openapi/CancelFlinkJob.md
  docs/docs/openapi/ExplainSql.md
  docs/docs/openapi/ExportSql.md
  docs/docs/openapi/GetJobInstance.md
  docs/docs/openapi/GetJobInstanceByTaskId.md
  docs/docs/openapi/GetJobPlan.md
  docs/docs/openapi/GetStreamGraph.md
  docs/docs/openapi/GetTaskLineage.md
  docs/docs/openapi/RestartTask.md
  docs/docs/openapi/SavepointTrigger.md
  docs/docs/openapi/SubmitTaskById.md
  docs/docs/openapi/SubmitTaskJob.md
  docs/docs/openapi/_category_.json
  docs/docs/openapi/openapi_overview.md
  docs/docusaurus.config.js
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-theme-classic/footer.json
  docs/i18n/zh/docusaurus-plugin-content-docs/current.json
  docs/i18n/zh/docusaurus-theme-classic/footer.json
Labels: Doc

#2964 [Fix]Fix prejob status is obtained
  dinky-admin/src/main/java/org/dinky/job/handler/JobRefreshHandler.java
Labels: bug

#2965 [Improvement] [dinky-admin] Improve warning message
  dinky-admin/src/main/java/org/dinky/utils/FlinkConfigOptionsUtils.java
Labels: Optimization

#2959 [Fix] fix datasource form state bug
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
  dinky-web/src/services/BusinessCrud.ts
  dinky-web/src/types/RegCenter/init.d.ts
  dinky-web/src/types/RegCenter/state.d.ts
Labels: bug

#2963 [fix-2962][gateway] fix kubernetesClient
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: bug

#2975 [Fix-2972]Fix jar task not be moniter in Standalone mode
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: bug

#2978 [Fix-2939]Fix some Web UI NPE
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/components/Typography/EllipsisMiddle.tsx
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CkDesc.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
Labels: bug

#2979 [Fix]Fix Email smtpSslTrust NPE
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/params/EmailParams.java
  dinky-common/src/main/java/org/dinky/utils/URLUtils.java
  dinky-web/src/components/FormSingleColumnList/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Email/index.tsx
Labels: bug

#2987 [Doc]add normal_deploy doc some things to note
  docs/docs/deploy_guide/normal_deploy.mdx
Labels: Doc

#2984 [Optimize ]Optimize log printing that can cause ambiguity
  dinky-core/src/main/java/org/dinky/trans/Operations.java
Labels: Optimization

#2986 [Optimize ]Optimize Paimon log printing that can cause ambiguity
  dinky-admin/src/main/java/org/dinky/utils/PaimonUtil.java
Labels: Optimization

#3001 [Fix-2947] Fix the issue of missing single quotes in the default value of MySQL table building statements
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java
Labels: bug

#3003 [Fix-#2990]fix yarn port is 0
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: bug

#3004 [Fix-2793] Fix Catalog NPE
  dinky-admin/src/main/java/org/dinky/data/dto/AbstractStatementDTO.java
  dinky-web/src/pages/DataStudio/HeaderContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/ColumnInfo/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/index.tsx
Labels: bug

#3012 [Fix-3006] Fix CDCSOURCE does not supports delete event after optimize code
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/catalog/SQLCatalogSinkBuilder.java
Labels: bug

#3014 feat: add path-to-regexp package
  dinky-web/package.json
Labels: bug

#3018 [Fix] fix gitlab auth error
  dinky-admin/src/main/java/org/dinky/utils/GitRepository.java
  dinky-web/src/global.less
  dinky-web/src/pages/RegCenter/GitProject/components/CodeTree/CodeTreeShow/SiderTree/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/ProjectForm/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectModal/index.tsx
  dinky-web/src/services/constants.tsx
Labels: bug

#3022 [Fix-3021] fix jobmanager log render logical error
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
Labels: bug

#3020 [Doc] added dinky setting description
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/docs/user_guide/system_setting/global_settings/dinky_setting.md
Labels: Doc

#3027 [Bug] [Flink] Optimize flink yarn submission
  dinky-admin/pom.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/util/FlinkAppUtil.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  pom.xml
Labels: bug

#3028 [Optimize] [App] Optimize app package
  dinky-app/dinky-app-base/pom.xml
Labels: Optimization

#3030 [Bug] [CDCSOURCE] fix cdcsource split
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/utils/FlinkStatementUtil.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
Labels: bug

#3032 [Optimize] [Web] fix web show
  dinky-web/src/global.less
  dinky-web/src/pages/DataStudio/MiddleContainer/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: Optimization

#3031 Fix comment split2
  dinky-admin/src/test/java/org/dinky/utils/SqlUtilTest.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/sql/FlinkQuery.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
  dinky-core/src/main/java/org/dinky/constant/FlinkSQLConstant.java
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/JobManagerLogsTab.tsx
Labels: bug

#3040 [Optimization]optimize some permission and optimize some logical
  dinky-admin/src/main/java/org/dinky/controller/DataSourceController.java
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-common/src/main/java/org/dinky/data/constant/PermissionConstants.java
  dinky-web/config/routes.ts
  dinky-web/src/app.tsx
  dinky-web/src/locales/en-US/menu.ts
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/menu.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/constants.tsx
  dinky-web/src/pages/AuthCenter/Menu/components/MenuList/index.tsx
  dinky-web/src/pages/AuthCenter/Role/components/AssignMenu/index.tsx
  dinky-web/src/pages/AuthCenter/Role/components/RoleProTable/index.tsx
  dinky-web/src/pages/AuthCenter/RowPermissions/components/PermissionsProTable/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantProTable/index.tsx
  dinky-web/src/pages/AuthCenter/Tenant/components/TenantUserList/index.tsx
  dinky-web/src/pages/AuthCenter/Token/component/TokenList/index.tsx
  dinky-web/src/pages/AuthCenter/User/components/UserProTable/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/HistoryVersion/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobInfo/index.tsx
  dinky-web/src/pages/DataStudio/route.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/components/RestartForm.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertInstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertTemplate/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
  dinky-web/src/pages/RegCenter/Document/components/DocumentProTable/index.tsx
  dinky-web/src/pages/RegCenter/GitProject/components/ProjectProTable/index.tsx
  dinky-web/src/pages/RegCenter/GlobalVar/components/GlobalVarProTable/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/constants.tsx
  dinky-web/src/pages/RegCenter/UDF/components/UDFTemplate/TemplateTable/index.tsx
  dinky-web/src/pages/SettingCenter/AlertRule/AlertRuleList/index.tsx
  dinky-web/src/pages/SettingCenter/SystemLogs/TagInfo/index.tsx
  dinky-web/src/types/Public/constants.tsx
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: Optimization

#3041 Update normal_deploy.mdx
  docs/docs/deploy_guide/normal_deploy.mdx
Labels: Doc

#3047 Fix menu selection
  dinky-web/src/pages/AuthCenter/Role/components/AssignMenu/index.tsx
Labels: bug

#3050 [Optimized ] Optimized the logic for obtaining users from LDAP
  dinky-admin/src/main/java/org/dinky/context/LdapContext.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-admin/src/main/java/org/dinky/service/impl/LdapServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
Labels: Optimization

#3045 [Bug] [UDF] fix udf some bug
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-function/src/main/java/org/dinky/function/pool/UdfCodePool.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#3052 [Fix-2877] Fix postgre type converter
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java
Labels: Bug

#3049 [Feature] support setting center permission control
  dinky-admin/src/main/resources/db/db-h2-dml.sql
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/components/CallBackButton/EditBtn.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/DSConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/EnvConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/FlinkConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/MavenConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/MetricsConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/ResourcesConfig/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/constants.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/index.tsx
  dinky-web/src/types/Public/constants.tsx
  docs/docs/user_guide/system_setting/global_settings/resource_setting.md
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.0.0_schema/mysql/dinky_dml.sql
Labels: New Feature

#3055 [Doc] Optimize cdcsource split table
  dinky-common/src/main/java/org/dinky/utils/SplitUtil.java
  dinky-web/src/pages/Metrics/Server/index.tsx
  docs/docs/practical_guide/cdcsource_practice/cdcsource_overview.md
Labels: Doc

#3056 [Feature] [Resource] Add resource hdfs ha
  dinky-admin/src/main/java/org/dinky/init/SystemInit.java
  dinky-admin/src/main/java/org/dinky/service/resource/BaseResourceManager.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/resource/BaseResourceManager.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
Labels: New Feature

#3062 [Doc] added resource hdfs ha doc
  docs/docs/user_guide/system_setting/global_settings/resource_setting.md
Labels: Doc

#3063 fix: double slop
  .idea/vcs.xml
  dinky-admin/src/test/java/org/dinky/utils/SqlUtilTest.java
  dinky-common/src/main/java/org/dinky/utils/SqlUtil.java
Labels: Bug

#3057 [Fix]Fixed the JAR task could not use set
  dinky-admin/src/main/java/org/dinky/aop/exception/WebExceptionHandler.java
  dinky-common/src/main/java/org/dinky/data/exception/BusException.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  docs/docs/user_guide/studio/flink_sql_task_devlop.md
Labels: Bug

#3068 [Optimize] Optimize k8s udf download
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
Labels: Bug

#3064 [Optimize] [CDC] Optimize cdc3.0 code
  dinky-core/src/main/java/org/dinky/trans/pipeline/DinkyFlinkPipelineComposer.java
  dinky-core/src/main/java/org/dinky/trans/pipeline/DinkyFlinkPipelineExecution.java
  dinky-core/src/main/java/org/dinky/trans/pipeline/FlinkCDCPipelineOperation.java
Labels: Optimization

#3072 [Feature-3071][CDCSOURCE] CDCSOURCE supports ensuring data order in multiple degrees of parallelism
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/AbstractSqlSinkBuilder.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CDCSource.java
  dinky-core/src/main/java/org/dinky/trans/ddl/CreateCDCSourceOperation.java
Labels: Optimization

#3066 [Optimize][Action]optimization actions
  .github/workflows/add-assignees.yml
  .github/workflows/code-review.yml
  .github/workflows/docs.yml
  .github/workflows/format_code.yaml
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-rebot.yml
  .github/workflows/issue-reply.yml
  .github/workflows/pr-reviewer-assign.yml
Labels: Optimization

#3073 [BugFix] [cdcsource] fix_split_bug
  dinky-common/src/main/java/org/dinky/utils/SplitUtil.java
Labels: Bug

#3074 [Optimize] common change hutool
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
Labels: Optimization

#3077 [Optimization][script] Optimizing the classpath in the Dinky startup …
  script/bin/auto.sh
Labels: Optimization

#3075 Added resource center synchronization
  dinky-admin/src/main/java/org/dinky/controller/ResourceController.java
  dinky-admin/src/main/java/org/dinky/data/model/Resources.java
  dinky-admin/src/main/java/org/dinky/service/resource/BaseResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/ResourcesService.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/HdfsResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/LocalResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/OssResourceManager.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-common/src/main/java/org/dinky/oss/OssTemplate.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/FileTree/index.tsx
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/services/endpoints.tsx
  dinky-web/src/types/Studio/data.d.ts
Labels: Optimization

#3080 [Doc] optimization some docs
  docs/docs/deploy_guide/compile_deploy.md
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/developer_guide/local_debug.md
Labels: Doc

#3083 [Refactor] modify package name
  dinky-assembly/pom.xml
Labels: Refactor

#3084 [Doc] added dinky-1.0.0-rc4 download docs
  docs/docs/deploy_guide/normal_deploy.mdx
  docs/download/dinky-1.0.0.md
  docs/download/download.md
Labels: Doc

#3093 [Optimization] Optimizing the background color of table data labels in data development
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
Labels: Optimization

#3092 [Optimize] [Web] add jar group
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
  dinky-admin/src/main/java/org/dinky/service/SystemService.java
  dinky-admin/src/main/java/org/dinky/service/impl/SystemServiceImpl.java
  dinky-web/src/pages/SettingCenter/ClassLoaderJars/index.tsx
  dinky-web/src/pages/SettingCenter/ClassLoaderJars/service.ts
Labels: Optimization

#3100 [Doc] fix doc indent
  docs/docs/developer_guide/local_debug.md
Labels: Doc

#3106 [Fix] fix devops status render bug
  dinky-web/src/components/JobTags/StatusTag.tsx
Labels: Bug

#3107 [Fix]Fix deletion task failed when the job instance does not exist
  dinky-admin/src/main/java/org/dinky/service/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
Labels: Bug

#3105 [Refactor][Admin] Change dependency implementation to dependency interface
  dinky-admin/src/main/java/org/dinky/service/TaskService.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/FlinkSqlEnvTask.java
  dinky-admin/src/main/java/org/dinky/service/task/FlinkSqlTask.java
Labels: Optimization

#3113 [Doc] modify ldap doc
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  docs/docs/user_guide/system_setting/global_settings/ldap.md
Labels: Doc

#3118 [Fix] fix `enableModelTip` state error
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/requestErrorConfig.ts
Labels: Bug

#3117 [Fix]fix ldap config not update at change
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/LdapConfig/index.tsx
Labels: Bug

#3116 [Optimize ]optimize exception throw
  dinky-admin/src/main/java/org/dinky/assertion/DinkyAssert.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/LdapServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-web/src/models/Sse.tsx
Labels: Optimization

#3112 [optimize]optimize task diff model
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
Labels: Optimization

#3109 [Fix] Fix duplicate exception alert
  dinky-admin/src/main/java/org/dinky/data/model/ext/JobAlertData.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/rules/CheckpointsRule.java
  dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/rules/ExceptionRule.java
Labels: Bug

#3119 [Optimized ]Optimized the heartbeat of the cluster
  dinky-admin/src/main/java/org/dinky/controller/ClusterInstanceController.java
  dinky-admin/src/main/java/org/dinky/service/ClusterInstanceService.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
Labels: Optimization
