Repository DataLinkDC/dinky, pull requests merged in 2024-05, with the labels that each got.

#3431 [Feature] Release-1.0.2
  docs/docs/roadmap.md
  docs/download/dinky-1.0.2.md
  docs/download/download.md
  pom.xml
Labels: New Feature

#3446 [Fix] Fix classloader problems
  dinky-core/src/main/java/org/dinky/executor/Executor.java
Labels: Bug

#3447 [Fix] package static to root dir for nginx
  dinky-assembly/src/main/assembly/package.xml
Labels: Bug

#3330 [Optimization] [SQL] Increase dinky_udf_manage table's class_name column's length from 50 to 100
  script/sql/dinky-mysql.sql
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.1.0_schema/mysql/dinky_ddl.sql
  script/sql/upgrade/1.1.0_schema/postgre/dinky_ddl.sql
Labels: Optimization

#3306 [Fix] modify pgsql
  script/sql/dinky-pg.sql
Labels: Optimization

#3462 [Feature] added version for issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: New Feature

#3464 [Optimization] change loginfo to debug
  dinky-admin/src/main/java/org/dinky/service/catalogue/strategy/impl/CatalogueTreeSortCreateTimeStrategy.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/strategy/impl/CatalogueTreeSortDefaultStrategy.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/strategy/impl/CatalogueTreeSortFirstLetterStrategy.java
Labels: Optimization

#3467 [Optimization] Optimize the path generated by SQL execution
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
Labels: Optimization

#3473 【Doc】New home page
  docs/package.json
  docs/src/components/HomepageFeatures/index.js
  docs/src/pages/index.js
  docs/src/pages/index.less
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/styles.module.css
  docs/tsconfig.json
Labels: Doc

#3481 [Bug] fix job list search and positioning functions's problems
  dinky-web/src/global.less
  dinky-web/src/locales/en-US/global.ts
  dinky-web/src/locales/zh-CN/global.ts
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/function.tsx
  dinky-web/src/pages/DataStudio/model.ts
  dinky-web/src/pages/DevOps/JobList/index.tsx
Labels: Bug

#3487 [Bug][Alert] fix wechat'app mode send msg problems
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/WeChatSender.java
  dinky-common/src/main/java/org/dinky/context/FreeMarkerHolder.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/WeChat/index.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: Bug

#3490 [Bug]fix flink 1.19 app mode
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.19/src/main/java/org/dinky/executor/ClusterDescriptorAdapterImpl.java
  dinky-flink/dinky-flink-1.19/pom.xml
Labels: Bug

#3493 [Doc] Fix new doc home cannot build
  .github/workflows/docs.yml
  dinky-web/src/types/RegCenter/data.d.ts
  docs/package.json
Labels: Bug

#3497 [Bug]Fix jdk11 GC Bug
  script/bin/auto.sh
Labels: Bug

#3477 [Fix] Resolving issues where custom classes in user Jars fail to compile during the submission of Jar tasks
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
Labels: Bug

#3499 [Optimization] Optimizing SQL files for Flyway
  dinky-admin/src/main/assembly/package.xml
  dinky-admin/src/main/resources/db/migration/README.md
  dinky-admin/src/main/resources/db/migration/h2/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/h2/V1.0.2__baseline.sql
  dinky-admin/src/main/resources/db/migration/h2/V1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V1.0.2__baseline.sql
  dinky-admin/src/main/resources/db/migration/mysql/V1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V1.0.2__baseline.sql
Labels: Optimization

#3503 [Feature] When Add Tenant Automatically Add Admin User Association
  dinky-admin/src/main/java/org/dinky/service/impl/TenantServiceImpl.java
Labels: New Feature

#3501 [Optimization] Optimize application configuration
  dinky-admin/src/main/resources/application.yml
Labels: Optimization

#3500 [Optimization] Change h2 port
  dinky-admin/src/main/resources/application-h2.yml
Labels: Optimization

#3505 [Optimization] Add stored procedures to perform flyway operations
  dinky-admin/src/main/resources/application-h2.yml
  dinky-admin/src/main/resources/db/migration/h2/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/h2/V1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/R1.1.0__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V1.1.0__release.sql
Labels: Optimization

#3506 [Fix] Dealing with the issue of Postgre database being unable to execute Flyway
  dinky-admin/src/main/java/org/dinky/context/TenantContextHolder.java
  dinky-admin/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLDatabase.java
  dinky-admin/src/main/java/org/flywaydb/database/mysql/MySQLDatabase.java
  dinky-admin/src/main/resources/db/migration/pgsql/V1.0.2__baseline.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V1.1.0__release.sql
  dinky-admin/src/main/resources/log4j2.xml
Labels: Bug

#3511 [featrue]add backend kill process
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-common/src/main/java/org/dinky/data/model/ProcessEntity.java
  dinky-web/package.json
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#3509 [feature]add backend kill process
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/ProcessController.java
  dinky-common/src/main/java/org/dinky/data/model/ProcessEntity.java
  dinky-web/package.json
  dinky-web/src/components/CustomEditor/CodeShow/index.tsx
  dinky-web/src/components/CustomEditor/EditorFloatBtn/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
  dinky-web/src/services/endpoints.tsx
Labels: New Feature

#3516 [feature] add kubernetes deploy
  deploy/docker/.env
  deploy/docker/Dockerfile
  deploy/docker/DockerfileDinkyFlink
  deploy/docker/DockerfileMysql
  deploy/docker/DockerfileWeb
  deploy/docker/README.md
  deploy/docker/README_zh_CN.md
  deploy/docker/docker-compose.dev.yml
  deploy/docker/docker-compose.yml
  deploy/docker/web/default.conf
  deploy/docker/web/nginx.conf
  deploy/kubernetes/helm/dinky/.helmignore
  deploy/kubernetes/helm/dinky/Chart.yaml
  deploy/kubernetes/helm/dinky/conf/application-flyway.yml
  deploy/kubernetes/helm/dinky/conf/application-h2.yml
  deploy/kubernetes/helm/dinky/conf/application-jmx.yml
  deploy/kubernetes/helm/dinky/conf/application-mysql.yml
  deploy/kubernetes/helm/dinky/conf/application-pgsql.yml
  deploy/kubernetes/helm/dinky/conf/application.yml
  deploy/kubernetes/helm/dinky/conf/jmx/jmx_exporter_config.yaml
  deploy/kubernetes/helm/dinky/conf/log4j2.xml
  deploy/kubernetes/helm/dinky/templates/NOTES.txt
  deploy/kubernetes/helm/dinky/templates/_helpers.tpl
  deploy/kubernetes/helm/dinky/templates/configmap.yaml
  deploy/kubernetes/helm/dinky/templates/dinky.yaml
  deploy/kubernetes/helm/dinky/templates/ingress.yaml
  deploy/kubernetes/helm/dinky/templates/rbac.yaml
  deploy/kubernetes/helm/dinky/templates/secret-external-mysql-database.yaml
  deploy/kubernetes/helm/dinky/templates/secret-external-postgres-database.yaml
  deploy/kubernetes/helm/dinky/templates/secret-mysql-database.yaml
  deploy/kubernetes/helm/dinky/templates/secret-postgres-database.yaml
  deploy/kubernetes/helm/dinky/templates/service-external-database.yaml
  deploy/kubernetes/helm/dinky/templates/service.yaml
  deploy/kubernetes/helm/dinky/templates/serviceaccount.yaml
  deploy/kubernetes/helm/dinky/values.yaml
  dinky-assembly/src/main/assembly/package.xml
  docker/DockerfileDinkyFlink
  docs/docs/deploy_guide/kubernetes_deploy.md
Labels: New Feature

#3518 [BugFix]Fix udf compiler problem
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/data/model/UDF.java
Labels: Bug

#3523 [BugFix] [UDF] Fix the issue where UDF cannot find classes in Flink SQL tasks
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-function/src/main/java/org/dinky/function/compiler/FunctionCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
Labels: Bug

#3524 Optimize the prompt properties of the front-end dropdown menu and upgrade the front-end dependency version
  dinky-web/package.json
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
Labels: Optimization

#3521 [Fix] Fix the issue of cluster instances being unable to be deleted
  dinky-admin/src/main/java/org/dinky/data/model/ClusterInstance.java
  dinky-admin/src/main/java/org/dinky/job/handler/ClearJobHistoryHandler.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Bug

#3525 [BugFix] [UDF] Fix the issue where UDF cannot find classes in Flink SQL tasks
  dinky-function/src/main/java/org/dinky/function/compiler/CustomStringScalaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/JVMPackage.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/PythonFunction.java
  dinky-function/src/main/java/org/dinky/function/compiler/ScalaCompiler.java
  dinky-function/src/main/java/org/dinky/function/constant/PathConstant.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/function.tsx
Labels: Bug

#3526 [Feature] modify dev branch version to 1.1.0-SNAPSHOT
  pom.xml
Labels: New Feature

#3538 [Optimize] metrics add check
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/SystemMetricsTask.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  pom.xml
Labels: Optimization

#3537 [Optimize] metrics add check
  dinky-admin/src/main/java/org/dinky/job/FlinkJobTask.java
  dinky-admin/src/main/java/org/dinky/job/SystemMetricsTask.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  pom.xml
Labels: Optimization

#3546 [Feature]fix docker action
  .github/workflows/docker_build.yaml
  deploy/docker/.env
  deploy/docker/Dockerfile
  deploy/docker/DockerfileWeb
  deploy/docker/docker-compose.dev.yml
  deploy/docker/docker-compose.yml
  deploy/docker/web/default.conf
  deploy/docker/web/nginx.conf
  docker/.env
  docker/Dockerfile
  docker/DockerfileDinkyFlink
  docker/DockerfileMysql
  docker/README.md
  docker/README_zh_CN.md
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  script/bin/auto.sh
Labels: New Feature

#3545 [Feature] Fix docker push to docker.io
  .github/workflows/docker_build.yaml
  deploy/docker/.env
  deploy/docker/Dockerfile
  deploy/docker/DockerfileDinkyFlink
  deploy/docker/DockerfileMysql
  deploy/docker/README.md
  deploy/docker/README_zh_CN.md
  deploy/docker/docker-compose.dev.yml
  deploy/docker/docker-compose.yml
  dinky-admin/src/main/resources/application-h2.yml
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/get_started/quick_experience.md
  script/bin/auto.sh
Labels: New Feature

#3551 [Bug]Fix-3549
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#3550 [Bug]Fix-3549
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug
