Repository DataLinkDC/dinky, pull requests merged in 2024-08, with the labels that each got.

#3685 [Doc]upgrage docker doc
  deploy/docker/docker-compose.yml
  docs/docs/deploy_guide/docker_deploy.md
  docs/docs/get_started/quick_experience.md
Labels: Doc

#3686 [Bug]fix docker push
  .github/workflows/docker_build.yaml
Labels: Bug

#3693 Optimize version update logic to solve cache issues caused by upgrades
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-web/package.json
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
  dinky-web/src/components/RightContent/index.tsx
  dinky-web/src/pages/Other/Login/function.tsx
  dinky-web/src/pages/Other/Login/index.tsx
  dinky-web/src/services/constants.tsx
  dinky-web/src/utils/function.tsx
Labels: Optimization

#3716 [Fix] fix Json serialization and deserialization
  dinky-admin/src/main/java/org/dinky/data/model/LoginLog.java
  dinky-admin/src/main/java/org/dinky/data/model/SysToken.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/Menu.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/Role.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/RoleMenu.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/RowPermissions.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/Tenant.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/User.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/UserRole.java
  dinky-admin/src/main/java/org/dinky/data/model/rbac/UserTenant.java
  dinky-admin/src/main/java/org/dinky/mybatis/model/DateBaseEntity.java
Labels: Bug

#3708 Refactor the method of obtaining user.dir
  dinky-admin/src/main/java/org/dinky/context/ConsoleContextHolder.java
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
  dinky-admin/src/main/java/org/dinky/controller/SystemController.java
  dinky-admin/src/main/java/org/dinky/service/impl/SystemServiceImpl.java
  dinky-admin/src/test/java/org/dinky/utils/DirUtilTest.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-common/src/main/java/org/dinky/data/constant/DirConstant.java
  dinky-common/src/main/java/org/dinky/utils/DockerClientUtils.java
  dinky-common/src/main/java/org/dinky/utils/URLUtils.java
  dinky-function/src/main/java/org/dinky/function/constant/PathConstant.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  script/bin/auto.sh
Labels: Optimization, Refactor

#3718 [Doc]Add Cli Doc
  docs/docs/user_guide/studio/cli.md
Labels: Doc

#3738 [Fix][Web] Resolve the issue of "Exceeding storage quota" when too many job tabs are open
  dinky-web/package.json
  dinky-web/src/app.tsx
  dinky-web/src/components/RightContent/AvatarDropdown.tsx
Labels: Optimization

#3745 [Optimization] Delete the prompt message on the UDF registration management page
  dinky-web/src/pages/RegCenter/UDF/index.tsx
Labels: Optimization

#3746 [Feature]Add bug template version number
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: New Feature

#3744 [Optimization]Optimizing class attribute type issues
  dinky-admin/src/main/java/org/dinky/data/model/GitProject.java
Labels: Optimization

#3743 [Feature] change reversion to 1.1.1-SNAPSHOT
  pom.xml
Labels: New Feature

#3739 [Optimization] delete dinky_cluster index
  dinky-admin/src/main/resources/db/migration/h2/V20240827.1.1.1__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V20240827.1.1.1__release.sql
  dinky-admin/src/main/resources/db/migration/pgsql/V20240827.1.1.1__release.sql
Labels: Optimization

#3740 [Optimization]Optimize mapper queries
  dinky-admin/src/main/resources/mapper/AlertGroupMapper.xml
  dinky-admin/src/main/resources/mapper/AlertInstanceMapper.xml
  dinky-admin/src/main/resources/mapper/AlertRulesMapper.xml
  dinky-admin/src/main/resources/mapper/CatalogueMapper.xml
  dinky-admin/src/main/resources/mapper/ClusterConfigurationMapper.xml
  dinky-admin/src/main/resources/mapper/ClusterInstanceMapper.xml
  dinky-admin/src/main/resources/mapper/DataBaseMapper.xml
  dinky-admin/src/main/resources/mapper/DocumentMapper.xml
  dinky-admin/src/main/resources/mapper/FragmentVariableMapper.xml
  dinky-admin/src/main/resources/mapper/GitProjectMapper.xml
  dinky-admin/src/main/resources/mapper/HistoryMapper.xml
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-admin/src/main/resources/mapper/MenuMapper.xml
  dinky-admin/src/main/resources/mapper/OperateLogMapper.xml
  dinky-admin/src/main/resources/mapper/RoleMapper.xml
  dinky-admin/src/main/resources/mapper/RoleSelectPermissionsMapper.xml
  dinky-admin/src/main/resources/mapper/SysConfigMapper.xml
  dinky-admin/src/main/resources/mapper/TaskMapper.xml
  dinky-admin/src/main/resources/mapper/TenantMapper.xml
  dinky-admin/src/main/resources/mapper/UDFTemplateMapper.xml
  dinky-admin/src/main/resources/mapper/UserTenantMapper.xml
Labels: Optimization

#3741 [Feature][web] added npm profiles
  dinky-web/pom.xml
  docs/docs/deploy_guide/compile_deploy.md
  docs/docs/developer_guide/local_debug.md
  pom.xml
Labels: New Feature

#3749 [Optimize][Web]Optimize some web layouts to make them more user-friendly when displayed on small screens
  dinky-web/src/global.less
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/JobDesc.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertGroup/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertInstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceList/index.tsx
Labels: DEVELOPING

#3747 [Bugfix] [Git Build] fix git build some bug
  dinky-admin/src/main/java/org/dinky/sse/StepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/GetJarsStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/HeadStepSse.java
  dinky-admin/src/main/java/org/dinky/sse/git/MavenStepSse.java
  dinky-admin/src/main/java/org/dinky/utils/GitProjectStepSseFactory.java
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
  dinky-admin/src/test/java/org/dinky/utils/MavenUtilTests.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-common/src/main/java/org/dinky/utils/RunTimeUtil.java
  dinky-common/src/test/java/org/dinky/util/RunTimeUtilTest.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/GitProject/components/BuildSteps/index.tsx
Labels: Bug

#3754 [Optimization] Optimizing the virtual scrolling problem of data source detail list
  dinky-web/src/global.less
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/SchemaTree/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/index.tsx
Labels: Optimization

#3759 [Optimize] [Web ] Optimize login page
  dinky-web/config/config.ts
  dinky-web/package.json
  dinky-web/public/icons/footer-bg.svg
  dinky-web/public/imgs/login_background.jpg
  dinky-web/public/login_animation.json
  dinky-web/src/components/Footer/index.tsx
  dinky-web/src/pages/Other/Login/LangSwitch/index.tsx
  dinky-web/src/pages/Other/Login/LoginForm/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
Labels: Optimization

#3762 [BugFix][Flink] Fix some bugs that occurred when Flink was submitted in local mode
  dinky-admin/src/main/java/org/dinky/url/RsURLStreamHandlerFactory.java
  dinky-client/dinky-client-1.19/src/main/java/org/dinky/executor/ClusterDescriptorAdapterImpl.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-metadata/dinky-metadata-paimon/pom.xml
Labels: Bug
