Repository DataLinkDC/dinky, pull requests merged in 2024-09, with the labels that each got.

#3768 [Fix] Fix abnormal data in pg query
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: Bug

#3770 [Optimize][Github Action]Optimize doc action
  .github/workflows/docs.yml
Labels: Optimization

#3767 Fix the issue where flyway does not support mysql5.7
  dinky-admin/pom.xml
  dinky-admin/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLDatabase.java
  dinky-admin/src/main/java/org/flywaydb/database/mysql/MySQLDatabase.java
  dinky-admin/src/main/resources/application-flyway.yml
  pom.xml
  script/sql/dinky-pg.sql
  script/sql/upgrade/1.1.0_schema/mysql/dinky_dml.sql
  script/sql/upgrade/1.1.0_schema/postgre/dinky_dml.sql
Labels: Bug

#3777 [Optimization][Data Studio] Fix query oracle primary key column bug
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/query/OracleQuery.java
Labels: Bug

#3784 [Optimize][Admin]Optimize program start
  dinky-admin/src/main/java/org/dinky/Dinky.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/visitor/Clickhouse20ExportParameterVisitor.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/visitor/Clickhouse20OutputVisitor.java
  pom.xml
Labels: Optimization

#3786 [Feature][Flink] Added support for Flink 1.20 and updated dependencies on other Flink versions
  .github/workflows/auto-realease-ci.yml
  .github/workflows/backend.yaml
  dinky-app/dinky-app-1.20/pom.xml
  dinky-app/dinky-app-1.20/src/main/java/org/dinky/app/MainApp.java
  dinky-app/pom.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.20/pom.xml
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.20/src/main/java/org/dinky/flink/catalog/DinkyMysqlCatalog.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.20/src/main/java/org/dinky/flink/catalog/factory/DinkyMysqlCatalogFactory.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.20/src/main/java/org/dinky/flink/catalog/factory/DinkyMysqlCatalogFactoryOptions.java
  dinky-catalog/dinky-catalog-mysql/dinky-catalog-mysql-1.20/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
  dinky-catalog/dinky-catalog-mysql/pom.xml
  dinky-client/dinky-client-1.20/pom.xml
  dinky-client/dinky-client-1.20/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/client/program/PackagedProgramUtils.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/yarn/Utils.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/ClusterDescriptorAdapterImpl.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/CustomTableResultImpl.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/DefaultStreamTableEnvironment.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/DefaultTableEnvironment.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/DefaultTableEnvironmentInternal.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/ExtendedParser.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/ParserWrapper.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/StaticResultProvider.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/TableSchemaField.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/gateway/FlinkSqlClient.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/operations/CustomNewParserImpl.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/operations/DinkyExecutableOperation.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/operations/DinkyOperationExecutor.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/operations/DinkyParser.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/utils/FunctionVisitor.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/utils/LineageContext.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/utils/ObjectConvertUtil.java
  dinky-client/pom.xml
  dinky-flink/dinky-flink-1.14/pom.xml
  dinky-flink/dinky-flink-1.15/pom.xml
  dinky-flink/dinky-flink-1.16/pom.xml
  dinky-flink/dinky-flink-1.17/pom.xml
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-flink/dinky-flink-1.19/pom.xml
  dinky-flink/dinky-flink-1.20/pom.xml
  dinky-flink/pom.xml
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  pom.xml
Labels: New Feature

#3701 refactor: metric request
  dinky-admin/src/main/java/org/dinky/job/handler/JobMetricsHandler.java
  dinky-common/src/main/java/org/dinky/utils/HttpUtils.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/FlinkJobThreadPool.java
  dinky-daemon/src/main/java/org/dinky/daemon/pool/ThreadPool.java
Labels: Refactor

#3787 [Fix] fix task tree can not sorting
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/index.tsx
  dinky-web/src/pages/DataStudio/model.ts
Labels: Bug

#3790 Tips for optimizing role permissions
  dinky-web/package.json
  dinky-web/src/components/Typography/ScrollInfo.tsx
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/AuthCenter/Role/components/RoleProTable/index.tsx
Labels: Optimization

#3789 perf: Introduction and layout of configuration items in the optimization configuration center
  dinky-web/src/components/Typography/MoreInfo.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/SettingOverView/GeneralConfig.tsx
Labels: Optimization

#3788 Optimize cluster configuration and start session cluster for manual registration
  dinky-admin/src/main/java/org/dinky/data/dto/ClusterInstanceDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
  dinky-admin/src/main/resources/mapper/ClusterInstanceMapper.xml
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/utils/function.tsx
Labels: Optimization

#3772 [Optimization] Improve get table info of the schema
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/AbstractJdbcDriver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/query/IDBQuery.java
  dinky-metadata/dinky-metadata-base/src/test/java/org/dinky/metadata/driver/AbstractDriverTest.java
  dinky-metadata/dinky-metadata-clickhouse/src/main/java/org/dinky/metadata/query/ClickHouseQuery.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/constant/DorisConstant.java
  dinky-metadata/dinky-metadata-doris/src/main/java/org/dinky/metadata/query/DorisQuery.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/constant/HiveConstant.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/driver/HiveDriver.java
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/query/HiveQuery.java
  dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/query/MySqlQuery.java
  dinky-metadata/dinky-metadata-oracle/src/main/java/org/dinky/metadata/query/OracleQuery.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/driver/PaimonDriver.java
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/query/PaimonQuery.java
  dinky-metadata/dinky-metadata-phoenix/src/main/java/org/dinky/metadata/constant/PhoenixConstant.java
  dinky-metadata/dinky-metadata-phoenix/src/main/java/org/dinky/metadata/query/PhoenixQuery.java
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java
  dinky-metadata/dinky-metadata-presto/src/main/java/org/dinky/metadata/constant/PrestoConstant.java
  dinky-metadata/dinky-metadata-presto/src/main/java/org/dinky/metadata/driver/PrestoDriver.java
  dinky-metadata/dinky-metadata-presto/src/main/java/org/dinky/metadata/query/PrestoQuery.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/constant/SqlServerConstant.java
  dinky-metadata/dinky-metadata-sqlserver/src/main/java/org/dinky/metadata/query/SqlServerQuery.java
  dinky-metadata/dinky-metadata-starrocks/src/main/java/org/dinky/metadata/constant/StarRocksConstant.java
  dinky-metadata/dinky-metadata-starrocks/src/main/java/org/dinky/metadata/query/StarRocksQuery.java
Labels: Optimization

#3791 [BugFix] [Git]Fix the issue of unlimited refresh of Git project pages
  dinky-admin/src/main/java/org/dinky/configure/DatabaseFlywayMigration.java
  dinky-web/package.json
Labels: Bug

#3804 [Bugfix][Flink]Fix some minor bugs
  dinky-admin/src/main/java/org/dinky/controller/FlinkProxyController.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/flink/checkpoint/base/BaseTypeCheckpointRead.java
Labels: Bug

#3809 [Optimize][Web]Optimize some page layouts, update web dependencies, and fix some bugs
  .idea/vcs.xml
  dinky-admin/src/main/resources/mapper/JobInstanceMapper.xml
  dinky-metadata/dinky-metadata-base/src/main/java/org/dinky/metadata/driver/Driver.java
  dinky-web/package.json
  dinky-web/src/components/Flink/FlinkDag/config.ts
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/components/JobTags/StatusTag.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/JobOverview.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobOverview/components/FlinkTable.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
Labels: Bug

#3812 [Document-3811][doc] update deploy guide reference
  README.md
  README_zh_CN.md
Labels: Doc

#3815 [Optimize][Web]Optimize dinky flink web UI
  dinky-web/src/components/Flink/FlinkDag/component/DagDataNode.tsx
  dinky-web/src/components/Flink/FlinkDag/component/DagPlanNode.tsx
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/srvice.ts
Labels: Optimization

#3817 [BugFix][Admin] Fix SQL injection error caused by upgrading Druid version, where 1=1
  dinky-admin/src/main/resources/application.properties
  dinky-web/src/components/Flink/FlinkDag/component/DagPlanNode.tsx
  dinky-web/src/components/Flink/FlinkDag/index.tsx
Labels: Bug

#3818 [BugFix][Web] Fix the catalog display field bug
  dinky-web/src/pages/DataStudio/LeftContainer/Catalog/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/DataSource/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/ProjectTitle/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/SchemaDesc/GeneralJdbcDesc/GeneralJdbcDesc.tsx
  dinky-web/src/types/RegCenter/data.d.ts
Labels: Bug

#3829 Fix deploy doc
  docs/docs/deploy_guide/normal_deploy.mdx
Labels: Doc

#3828 Fix null pointer exception occurs in alert
  dinky-admin/src/main/java/org/dinky/job/handler/JobAlertHandler.java
Labels: Bug

#3831 [Optimize]Optimize some code
  dinky-admin/src/main/java/org/dinky/aop/LogAspect.java
  dinky-common/src/main/java/org/dinky/context/FlinkUdfPathContextHolder.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResult.java
  dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/components/Flink/OptionsSelect/index.tsx
  dinky-web/src/components/Icons/HomeIcon.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/Result/index.tsx
  dinky-web/src/pages/DataStudio/BottomContainer/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/JobConfig/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/index.tsx
  dinky-web/src/pages/DataStudio/data.d.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertInstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationList/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/contants.tsx
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceList/index.tsx
  dinky-web/src/pages/RegCenter/Document/constans.ts
Labels: Optimization

#3830 [Optimize][Web]Optimize task list layout
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobTree/index.tsx
  dinky-web/src/pages/DataStudio/MiddleContainer/StudioEditor/index.tsx
Labels: Optimization

#3832 [Feature][Admin]Add global token
  dinky-admin/src/main/java/org/dinky/controller/DownloadController.java
  dinky-app/dinky-app-base/src/main/java/org/dinky/resource/impl/HttpFsDataOutputStream.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-flink/dinky-flink-1.20/pom.xml
Labels: New Feature

#3834 [Feature] support resource of physical deletion
  dinky-admin/src/main/java/org/dinky/service/resource/impl/ResourceServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/RegCenter/Resource/components/ResourceOverView/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/model.ts
  dinky-web/src/types/SettingCenter/data.d.ts
Labels: New Feature

#3833 [Fix] Fix the issue where the table name has a middle line that prevents task execution
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/AbstractSqlSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/SQLSinkBuilder.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/sql/catalog/SQLCatalogSinkBuilder.java
Labels: Bug

#3836 [Optimize]Add repeat import task
  dinky-admin/src/main/java/org/dinky/service/catalogue/impl/CatalogueServiceImpl.java
  dinky-admin/src/main/resources/dinky-loader/FlinkConfClass
  dinky-app/dinky-app-base/pom.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/trans/dml/ExecuteJarOperation.java
  dinky-web/package.json
  dinky-web/src/components/Flink/FlinkDag/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/FolderModal/FolderForm/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/FolderModal/index.tsx
  dinky-web/src/pages/DataStudio/LeftContainer/Project/JobModal/index.tsx
  dinky-web/src/pages/DataStudio/RightContainer/index.tsx
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
  dinky-web/src/pages/DevOps/JobList/index.tsx
  dinky-web/src/pages/DevOps/index.tsx
Labels: Optimization

#3842 Optimized the printing of K8S logs
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesApplicationGateway.java
Labels: Optimization

#3844 [Fix] fix configuration key error
  dinky-common/src/main/java/org/dinky/data/model/SystemConfiguration.java
Labels: Bug
