Repository DataLinkDC/dinky, pull requests merged in 2024-12, with the labels that each got.

#3986 [Feature][web] Add resource management to the datastudio page
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/DvaFunction.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Resource/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/ToolbarRoute.tsx
  dinky-web/src/pages/DataStudio/index.tsx
  dinky-web/src/pages/Other/Login/LoginForm/index.tsx
  dinky-web/src/pages/SettingCenter/GlobalSetting/model.ts
  dinky-web/src/pages/SettingCenter/GlobalSetting/service.ts
Labels: New Feature

#3985 [Optimize][Admin] Optimized the package size of the App and the rs protocol
  dinky-admin/src/main/java/org/dinky/url/RsURLStreamHandlerFactory.java
  dinky-app/dinky-app-1.14/pom.xml
  dinky-app/dinky-app-1.15/pom.xml
  dinky-app/dinky-app-1.16/pom.xml
  dinky-app/dinky-app-1.17/pom.xml
  dinky-app/dinky-app-1.18/pom.xml
  dinky-app/dinky-app-1.19/pom.xml
  dinky-app/dinky-app-1.20/pom.xml
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/url/RsURLStreamHandlerFactory.java
  dinky-metadata/dinky-metadata-paimon/pom.xml
Labels: Optimization

#3993 [Bug] [dinky-web] Issue with creating a new task with a subdirectory of the same name
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/CatalogueService.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/impl/CatalogueServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
Labels: Bug

#3997 [Bug] Fix k8s test bug
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#4001 [BugFix][Web]Fix data development and introduce LESS to cause the global CSS style confusion
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/index.less
  dinky-web/src/pages/DataStudio/Toolbar/FlinkSqlClient/index.less
  dinky-web/src/pages/DataStudio/Toolbar/FlinkSqlClient/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/Result/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.less
  dinky-web/src/pages/DataStudio/Toolbar/Service/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Tool/index.less
  dinky-web/src/pages/DataStudio/Toolbar/Tool/index.tsx
  dinky-web/src/pages/DataStudio/css/index.less
Labels: Bug

#3999 [Feature] Provide init tools
  deploy/docker/Dockerfile
  dinky-admin/src/main/assembly/package.xml
  dinky-assembly/src/main/assembly/package.xml
  script/bin/auto.sh
  script/bin/init_check_network.sh
  script/bin/init_db.sh
  script/bin/init_flink_dependences.sh
  script/bin/init_hadoop_dependences.sh
  script/bin/init_tools_main.sh
Labels: New Feature

#4002 [BugFix][Web]Fix data development, Flink jar task toolbar display
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: Bug

#4009 [Bug] Fix pg bug
  dinky-admin/src/main/java/org/dinky/configure/MybatisPlusConfig.java
  dinky-admin/src/main/resources/db/migration/postgresql/V20241205.1.2.0__release.sql
  dinky-web/src/pages/Home/components/MyWorker/MyWorker.tsx
  dinky-web/src/pages/Home/index.tsx
  dinky-web/src/pages/RegCenter/Alert/AlertRule/AlertRuleList/RuleEditForm/index.tsx
Labels: Bug

#4006 [Optimization] Optimize some script
  script/bin/auto.sh
  script/bin/init_check_network.sh
  script/bin/init_db.sh
  script/bin/init_env.sh
  script/bin/init_flink_dependences.sh
  script/bin/init_hadoop_dependences.sh
  script/bin/init_jdbc_driver.sh
  script/bin/init_tools_main.sh
Labels: Optimization

#4011 [Optimization] Optimization scheduler request error assert method
  dinky-scheduler/src/main/java/org/dinky/scheduler/client/ProjectClient.java
Labels: Optimization

#4008 [Optimize] [dinky-gateway] Add default jobmanager.memory.process.size parameter
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
Labels: Optimization

#4010 [BugFix][Admin]Fix dolphinscheduler calls dinky tasks and concurrent …
  dinky-admin/src/main/java/org/dinky/service/task/BaseTask.java
Labels: Bug

#4017 [Refactor][UDF]Refactor udf execute
  dinky-admin/src/main/java/org/dinky/data/model/ext/TaskExtConfig.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/task/FlinkJarSqlTask.java
  dinky-admin/src/main/java/org/dinky/service/task/UdfTask.java
  dinky-admin/src/main/java/org/dinky/utils/UDFUtils.java
  dinky-admin/src/main/resources/DinkyFlinkDockerfile
  dinky-common/src/main/java/org/dinky/context/FlinkUdfPathContextHolder.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/job/JobBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/builder/JobDDLBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobJarStreamGraphBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobTransBuilder.java
  dinky-core/src/main/java/org/dinky/job/builder/JobUDFBuilder.java
  dinky-core/src/main/java/org/dinky/job/runner/FlinkJarUtil.java
  dinky-core/src/main/java/org/dinky/job/runner/JobDDLRunner.java
  dinky-function/src/main/java/org/dinky/function/FunctionFactory.java
  dinky-function/src/main/java/org/dinky/function/compiler/FunctionCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/FunctionPackage.java
  dinky-function/src/main/java/org/dinky/function/compiler/JVMPackage.java
  dinky-function/src/main/java/org/dinky/function/compiler/JavaCompiler.java
  dinky-function/src/main/java/org/dinky/function/compiler/PythonFunction.java
  dinky-function/src/main/java/org/dinky/function/compiler/ScalaCompiler.java
  dinky-function/src/main/java/org/dinky/function/constant/PathConstant.java
  dinky-function/src/main/java/org/dinky/function/data/model/UDF.java
  dinky-function/src/main/java/org/dinky/function/util/UDFUtil.java
Labels: Refactor

#4023 [BugFix] [Alert]Fix alert serializable
  dinky-alert/dinky-alert-dingtalk/src/main/java/org/dinky/alert/dingtalk/params/DingTalkParams.java
  dinky-alert/dinky-alert-email/src/main/java/org/dinky/alert/email/params/EmailParams.java
  dinky-alert/dinky-alert-feishu/src/main/java/org/dinky/alert/feishu/params/FeiShuParams.java
  dinky-alert/dinky-alert-http/src/main/java/org/dinky/alert/http/params/HttpParams.java
  dinky-alert/dinky-alert-wechat/src/main/java/org/dinky/alert/wechat/params/WechatParams.java
Labels: Bug

#4024 [Optimize][Web] Optimize blood relationship acquisition, add Savepoint, optimize udf class name display
  dinky-admin/src/main/java/org/dinky/data/dto/StudioLineageDTO.java
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/SavePoint.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/TaskInfo.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/DataStudio/Toolbar/Resource/index.tsx
  dinky-web/src/pages/DataStudio/type.ts
Labels: Optimization

#4026 [Bug] Fix login bug
  dinky-admin/src/main/java/org/dinky/configure/AppConfig.java
  dinky-admin/src/main/java/org/dinky/controller/LdapController.java
  dinky-web/src/pages/Other/Welcome/WelcomeItem/FinishPage.tsx
Labels: Bug

#4027 [Optimization] Optimization devops page ui
  dinky-web/src/pages/DevOps/JobList/components/Overview/index.tsx
Labels: Optimization

#4028 [BugFix] [Flink] Fix flink jar submit
  dinky-client/dinky-client-base/src/main/java/org/dinky/executor/CustomTableEnvironment.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/utils/FlinkStreamEnvironmentUtil.java
  dinky-common/src/main/java/org/dinky/data/job/JobStatementType.java
  dinky-common/src/main/java/org/dinky/data/job/SqlType.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobRunnerFactory.java
  dinky-core/src/main/java/org/dinky/job/JobStatementPlan.java
  dinky-core/src/main/java/org/dinky/job/runner/JobJarRunner.java
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: Bug

#4031 [Feature-4025][*] Release 1.2.0-rc5
  docs/download/dinky-1.2.0.md
  pom.xml
Labels: New Feature

#4030 [Bug] Fix automation script path issue
  script/bin/auto.sh
  script/bin/init_check_network.sh
  script/bin/init_cleanup.sh
  script/bin/init_db.sh
  script/bin/init_env.sh
  script/bin/init_flink_dependences.sh
  script/bin/init_hadoop_dependences.sh
  script/bin/init_jdbc_driver.sh
  script/bin/init_tools_main.sh
  script/bin/parse_yml.sh
Labels: Bug

#4032 [Optimization] modify sqllite data position
  dinky-admin/src/main/java/org/dinky/utils/SqliteUtil.java
  dinky-common/src/main/java/org/dinky/data/constant/MonitorTableConstant.java
Labels: Optimization

#4041 [Optmization]Add welcome page auto width
  dinky-web/src/pages/Other/Welcome/WelcomeItem/BaseConfigItem.tsx
  dinky-web/src/pages/Other/Welcome/WelcomeItem/FlinkConfigItem.tsx
  dinky-web/src/pages/Other/Welcome/WelcomeItem/WelcomItem.tsx
  dinky-web/src/pages/Other/Welcome/index.tsx
Labels: Optimization

#4040 [Fix][Admin] Fix the situation where the "args" parameter is not pass…
  dinky-admin/src/main/java/org/dinky/utils/MavenUtil.java
Labels: Bug

#4042 [BugFix]Fix yarn parallel submit
  dinky-admin/src/main/java/org/dinky/init/EnvInit.java
  dinky-client/dinky-client-1.14/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Labels: Bug

#4036 [Feature][Test]Add E2E Test Programing process
  .github/workflows/e2e_test.yml
  deploy/docker/Dockerfile
  dinky-admin/src/main/java/org/dinky/Dinky.java
  e2e_test/docker-compose-env/dinky/docker-compose.yml
  e2e_test/docker-compose-env/flink/conf/core-site.xml
  e2e_test/docker-compose-env/flink/conf/flink-conf.yaml
  e2e_test/docker-compose-env/flink/conf/hdfs-site.xml
  e2e_test/docker-compose-env/flink/conf/log4j-console.properties
  e2e_test/docker-compose-env/flink/conf/yarn-site.xml
  e2e_test/docker-compose-env/flink/docker-compose.yml
  e2e_test/docker-compose-env/hadoop/core-site.xml
  e2e_test/docker-compose-env/hadoop/docker-compose.yml
  e2e_test/docker-compose-env/hadoop/hadoop.env
  e2e_test/docker-compose-env/hadoop/hdfs-site.xml
  e2e_test/docker-compose-env/hadoop/yarn-site.xml
  e2e_test/docker-compose-env/mysql/conf/conf.d/my.cnf
  e2e_test/docker-compose-env/mysql/conf/conf.d/my.conf
  e2e_test/docker-compose-env/mysql/docker-compose.yml
  e2e_test/tools/docker-compose.yml
  e2e_test/tools/env.py
  e2e_test/tools/logger.py
  e2e_test/tools/login.py
  e2e_test/tools/main.py
  e2e_test/tools/requirements.txt
  e2e_test/tools/task.py
Labels: New Feature

#4044 [Document][4043][docs]Modify README.md
  README.md
  README_zh_CN.md
Labels: Doc

#4046 [Fix-3964] [metadata] Fix NPE when executing a query statement on the PG table
  dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/convert/PostgreSqlTypeConvert.java
Labels: Bug

#4048 [Optimization-4047][web] Add push task into DolphinScheduler
  dinky-admin/src/main/java/org/dinky/controller/SchedulerController.java
  dinky-admin/src/main/java/org/dinky/service/impl/SchedulerServiceImpl.java
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/PushDolphin/constants.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/PushDolphin/function.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/PushDolphin/index.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: New Feature

#4052 [BugFix][FlinkJar]Fix the issue where FlinkJar cannot use global variables
  dinky-client/dinky-client-base/src/main/java/org/dinky/data/model/JarSubmitParam.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
Labels: Bug

#4059 [FixBug] Fix pg batch insert error
  dinky-admin/src/main/java/org/dinky/mapper/RoleMenuMapper.java
  dinky-admin/src/main/resources/db/migration/postgresql/V20241217.1.2.0__release.sql
  dinky-admin/src/main/resources/mapper/RoleMenuMapper.xml
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/PushDolphin/index.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: Bug

#4069 [Doc] Fix normal deploy doc error
  docs/docs/deploy_guide/normal_deploy.mdx
Labels: Doc

#4068 [Optimization] Optimize the execution logic of the script.
  script/bin/auto.sh
  script/bin/init_flink_dependences.sh
  script/bin/init_jdbc_driver.sh
  script/bin/init_tools_main.sh
Labels: Optimization

#4076 [Optimize][Doc]quick experience doc update
  docs/docs/get_started/quick_experience.md
Labels: Doc, Optimization

#4073 [BugFix][Flink Jar]Fix FLINK JAR submission
  dinky-admin/src/main/java/org/dinky/service/impl/StudioServiceImpl.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
Labels: Bug

#4081 [Bug]Change k8s StringUtils import
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#4079 [BugFix][FlinkJar]Fix flink jar
  dinky-core/src/main/java/org/dinky/executor/Executor.java
Labels: Bug

#4077 [Bug] [dinky-common] Fix deserialization exceptions caused by incorrect get methods in enum fields.
  dinky-common/src/main/java/org/dinky/data/enums/GatewayType.java
Labels: Bug

#4082 [Bug] [dinky-common] Fix deserialization exceptions caused by incorrect get methods in enum fields.
  dinky-common/src/main/java/org/dinky/data/enums/GatewayType.java
Labels: Bug

#4093 [E2E] Add k8s native test environment, and use k3s for the basic image
  .github/workflows/backend.yaml
  dinky-core/src/main/java/org/dinky/job/runner/JobPipelineRunner.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-web/src/pages/RegCenter/Document/constans.ts
  e2e_test/docker-compose-env/FlinkDockerfile
  e2e_test/docker-compose-env/dinky/docker-compose.yml
  e2e_test/docker-compose-env/flink/docker-compose.yml
  e2e_test/docker-compose-env/hadoop/hadoop.env
  e2e_test/tools/config.py
  e2e_test/tools/env.py
  e2e_test/tools/httpUtil.py
  e2e_test/tools/main.py
  e2e_test/tools/task.py
  e2e_test/view_k8s_all_pod_logs.sh
Labels: New Feature

#4103 [Bug-4102][admin]Bug fix for task lock strategy condition
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
Labels: Bug

#4100 [Bug-4084][Web]Bug fix 4 flinkJar task lost info
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
Labels: Bug
