Repository DataLinkDC/dinky, pull requests merged in 2025-01, with the labels that each got.

#4108 [Bug] [dinky-core] Click to trigger savepoint error (#4107)
  dinky-core/src/main/java/org/dinky/api/FlinkAPI.java
Labels: Bug

#4113 [Bugfix][FlinkJar]Fix FlinkJar args global variable parsing
  dinky-core/src/main/java/org/dinky/executor/Executor.java
Labels: Bug

#4109 [Optimize][Docker] Optimize docker image construction, support multiple warehouses, multiple platforms, and integration of dinky and flink images
  .github/workflows/docker_build.yaml
  deploy/docker/Dockerfile
Labels: Optimization

#4114 [Bug]Fix variable can`t throw error
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
Labels: Bug

#4115 [Bug]Fix variable can`t throw error
  dinky-core/src/main/java/org/dinky/executor/VariableManager.java
Labels: Bug

#4120 [Bug-4099][admin]bug fix 4 task with variable lineage
  dinky-admin/src/main/java/org/dinky/service/impl/JobInstanceServiceImpl.java
Labels: Bug

#4119 [Bug-4117][core]Bug fix for debug task when target table contains '.'
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
Labels: Bug

#4118 [Bug-4117][core]Bug fix for debug task when target table contains '.'
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
Labels: Bug

#4127 [Optimize][dinky-gateway] The user-defined flink conf path overrides the flink conf path parameter.
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#4130 [Optimize][E2E] Optimize e2e code structure
  .github/workflows/backend.yaml
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/exception/BusException.java
  dinky-core/src/main/java/org/dinky/executor/Executor.java
  e2e_test/docker-compose-env/dinky/docker-compose.yml
  e2e_test/docker-compose-env/doris/docker-compose.yml
  e2e_test/tools/dinky_task/flink_jar_sql/mysql2doris.sql
  e2e_test/tools/dinky_task/flink_sql/flink-sql-datagen-test.sql
  e2e_test/tools/dinky_task/flink_sql/flink-sql-lineage-test.sql
  e2e_test/tools/dinky_task/udf/JAVA_UDF.java
  e2e_test/tools/dinky_task/udf/PYTHON_UDF.py
  e2e_test/tools/dinky_task/udf/SCALA_UDF.scala
  e2e_test/tools/login.py
  e2e_test/tools/main.py
  e2e_test/tools/task.py
Labels: Optimization

#4135 [Optimization-4134][Web] Optimization home page icon and job detail lineage under dark theme
  dinky-web/src/components/Icons/HomeIcon.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLineage/index.tsx
Labels: Optimization

#4142 [Doc-4138]Document for task submit approval
  docs/docs/user_guide/auth_center/approval.md
  docs/docs/user_guide/system_setting/global_settings/approval_setting.md
Labels: Doc

#4141 [Feature-4139] Support data studio catalog tree list scroll interaction and search
  dinky-web/src/pages/DataStudio/Toolbar/Catalog/index.tsx
Labels: New Feature

#4145 [Feature][flink] Support CALL statement
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-common/src/main/java/org/dinky/data/job/SqlType.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobStatementPlan.java
  dinky-core/src/test/java/org/dinky/job/JobStatementPlanTest.java
Labels: New Feature

#4146 [Optimize] Optimize lineage relationship chart display
  dinky-web/package-lock.json
  dinky-web/package.json
  dinky-web/src/pages/DataStudio/Toolbar/Service/Lineage/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLineage/index.tsx
  dinky-web/src/pages/DevOps/JobDetail/JobLogs/components/ExceptionTab.tsx
Labels: Optimization

#4140 [Feature] Flink Kubernetes opoerator supports ingress
  dinky-client/dinky-client-base/src/main/java/org/dinky/data/model/JarSubmitParam.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesApplicationOperatorGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesOperatorGateway.java
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
Labels: New Feature

#4147 [Optimize][E2E]Optimize e2e
  .github/workflows/backend.yaml
  e2e_test/docker-compose-env/Dockerfile
  e2e_test/docker-compose-env/FlinkDockerfile
  e2e_test/docker-compose-env/dinky/docker-compose.yml
  e2e_test/docker-compose-env/doris/docker-compose.yml
  e2e_test/docker-compose-env/flink/docker-compose.yml
  e2e_test/docker-compose-env/hadoop/hadoop.env
  e2e_test/tools/config.py
  e2e_test/tools/dinky_task/flink_jar_sql/mysql2doris.sql
  e2e_test/tools/dinky_task/flink_sql/flink-sql-datagen-test.sql
  e2e_test/tools/dinky_task/flink_sql/flink-sql-lineage-test.sql
  e2e_test/tools/dinky_task/udf/JAVA_UDF.java
  e2e_test/tools/dinky_task/udf/PYTHON_UDF.py
  e2e_test/tools/dinky_task/udf/SCALA_UDF.scala
  e2e_test/tools/env.py
  e2e_test/tools/httpUtil.py
  e2e_test/tools/login.py
  e2e_test/tools/main.py
  e2e_test/tools/task.py
  e2e_test/view_k8s_all_pod_logs.sh
Labels: Optimization

#4151 [Optimization-4116][cdc] Add source url param in CDCSOURCE
  dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
  dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/mysql/MysqlCDCBuilder.java
Labels: Optimization

#4156 [Optimize][Web] Update antd frontend dependencies
  dinky-web/package-lock.json
  dinky-web/package.json
  dinky-web/src/pages/DataStudio/Toolbar/Project/index.tsx
Labels: Optimization

#4159 [Fix-4158] [flink] Fix CALL statement can not be executed on standalone cluster
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSqlRunner.java
Labels: Bug

#4154 [Optimize-4127][gateway] The user-defined flink conf path overrides the flink conf path parameter
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Optimization

#4155 [Feature-4140][gateway] Flink Kubernetes opoerator supports ingress
  dinky-client/dinky-client-base/src/main/java/org/dinky/data/model/JarSubmitParam.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesApplicationOperatorGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesOperatorGateway.java
  dinky-web/src/pages/RegCenter/Cluster/Configuration/components/ConfigurationModal/ConfigurationForm/FlinkK8s/index.tsx
Labels: New Feature

#4160 [Bug-4149] Bug fix for web socket session do not closed correctly and page stuck caused by it
  dinky-admin/src/main/java/org/dinky/ws/GlobalWebSocket.java
  dinky-web/src/models/UseWebSocketModel.tsx
Labels: Bug

#4163 [Fix-4162][flink]Fix set statement is not effective in application mode
  dinky-app/dinky-app-base/src/main/java/org/dinky/app/flinksql/Submitter.java
  dinky-core/src/main/java/org/dinky/explainer/Explainer.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobConfig.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-core/src/main/java/org/dinky/job/JobRunner.java
  dinky-core/src/main/java/org/dinky/job/JobRunnerFactory.java
  dinky-core/src/main/java/org/dinky/job/JobStatementPlan.java
  dinky-core/src/main/java/org/dinky/job/runner/AbstractJobRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobDDLRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobJarRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobPipelineRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSetRunner.java
  dinky-core/src/main/java/org/dinky/job/runner/JobSqlRunner.java
Labels: Bug

#4167 [Bug] Fix error in h2 sql script
  dinky-admin/src/main/resources/db/migration/h2/V20241219.1.2.1__release.sql
Labels: Bug

#4165 [Optimization] Optimization udf saved placeholder
  .idea/encodings.xml
  .idea/sqldialects.xml
  dinky-admin/src/main/java/org/dinky/controller/TaskController.java
  dinky-common/src/main/java/org/dinky/data/enums/Status.java
  dinky-common/src/main/resources/i18n/messages_en_US.properties
  dinky-common/src/main/resources/i18n/messages_zh_CN.properties
Labels: Optimization

#4176 [Optimization-4175][Web] Optimization catalog table info
  dinky-client/dinky-client-base/src/main/java/org/dinky/utils/FlinkTableMetadataUtil.java
Labels: Optimization

#4164 [Optimization] Optimization sql file
  dinky-admin/src/main/resources/db/migration/h2/V20250301.1.3.0__release.sql
  dinky-admin/src/main/resources/db/migration/mysql/V20250301.1.3.0__release.sql
  dinky-admin/src/main/resources/db/migration/postgresql/V20250301.1.3.0__release.sql
Labels: Optimization
