Repository DataLinkDC/dinky, pull requests merged in 2025-04, with the labels that each got.

#4345 [Fix-4344] Fix dinky-release-1.20-1.2.3.jar lacks dinky-cdc-plus.jar
  dinky-cdc/pom.xml
  dinky-core/pom.xml
Labels: Bug

#4324 [Bugfix] [k8s deployment] Modify the k8s deploy command
  deploy/kubernetes/helm/dinky/templates/dinky.yaml
Labels: Bug

#4358 [Doc] Optimize doc ad show
  docs/sidebars.js
  docs/src/pages/index.less
  docs/src/plugin/wwads-plugin.ts
  docs/static/img/ads.txt
Labels: Doc

#4277 [Optimization-4053] Support flink table planner loader
  dinky-client/dinky-client-1.14/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.15/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.16/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.17/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/AbstractCustomTableEnvironment.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.18/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.19/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.19/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/calcite/sql/SqlSelect.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/executor/PlannerTableEnvironmentImpl.java
  dinky-client/dinky-client-base/src/main/java/org/dinky/parser/CustomParserImpl.java
  dinky-core/src/main/java/org/dinky/executor/ExecutorConfig.java
  dinky-core/src/main/java/org/dinky/executor/LocalBatchExecutor.java
  dinky-core/src/main/java/org/dinky/executor/LocalStreamExecutor.java
  dinky-core/src/main/java/org/dinky/explainer/lineage/LineageBuilder.java
  dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
Labels: Optimization
