Repository DataLinkDC/dinky, pull requests merged in 2025-03, with the labels that each got.

#4269 [Bug] [dinky-admin] The flinksql multi-version switch button does not take effect
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskVersionServiceImpl.java
Labels: Bug

#4270 [Optimization][dinky-admin] Check if the cluster is disabled before starting the flink session.
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
Labels: Optimization

#4272 [Document] add Dinky 1.2.2 download document
  .github/ISSUE_TEMPLATE/bug-report.yml
  docs/download/dinky-1.2.2.md
  docs/download/download.md
Labels: Doc

#4284 [bug][dinky-gateway] Fix the issue where two Flink configuration items with the same prefix cause errors in Flink configuration parsing.
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#4285 [bug][dinky-gateway] Fix the issue where two Flink configuration items with the same prefix cause errors in Flink configuration parsing.
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
Labels: Bug

#4290 fix: Sync the configuration with src/main/resources directory
  deploy/kubernetes/helm/dinky/conf/application-flyway.yml
  deploy/kubernetes/helm/dinky/conf/application-h2.yml
  deploy/kubernetes/helm/dinky/conf/application-postgresql.yml
  deploy/kubernetes/helm/dinky/conf/application.yml
Labels: Bug

#4295 [bug][dinky-gateway] Fix the issue where two Flink configuration items with the same prefix cause errors in Flink configuration parsing.
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java
Labels: Bug

#4298 [bug][dinky-gateway] Fix the issue where two Flink configuration items with the same prefix cause errors in Flink configuration parsing.
  dinky-client/dinky-client-1.19/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java
  dinky-client/dinky-client-1.20/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java
Labels: Bug

#4313 [Fix-4308] Fix Array type in paimon query did not show the value
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/convert/PaimonTypeConvert.java
Labels: Bug

#4315 [Optimization-4314][admin] Optimize WebSocket for asynchronous sending
  dinky-admin/src/main/java/org/dinky/ws/GlobalWebSocket.java
Labels: Optimization

#4317 fix metadata-hive MissingFormatArgumentException #4316
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/query/HiveQuery.java
Labels: Bug

#4299 [Bug] [dinky-gateway] Fix import errors in utility classes and Fix configuration issues related to frontend display
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/watcher/DeploymentStatusWatcher.java
Labels: Bug

#4323 [Bug] [dinky-gateway] Fix import errors in utility classes and Fix configuration issues related to frontend display
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/KubernetesGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/watcher/DeploymentStatusWatcher.java
Labels: Bug

#4327 [Bug] Fix comparison expression issue
  script/bin/auto.sh
Labels: Bug

#4326 [Feature-4325][sandbox] Add Sandbox to debug data
  dinky-admin/src/main/java/org/dinky/job/JobShutdownConfig.java
  dinky-admin/src/main/java/org/dinky/job/handler/Job2MysqlHandler.java
  dinky-client/dinky-client-1.14/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.15/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.16/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.17/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.18/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.19/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-client/dinky-client-1.20/src/main/java/org/dinky/utils/FlinkUtil.java
  dinky-core/pom.xml
  dinky-core/src/main/java/org/dinky/data/result/ResultPool.java
  dinky-core/src/main/java/org/dinky/data/result/ResultRunnable.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResult.java
  dinky-core/src/main/java/org/dinky/data/result/SelectResultBuilder.java
  dinky-core/src/main/java/org/dinky/data/result/ShowResultBuilder.java
  dinky-core/src/main/java/org/dinky/job/JobManager.java
  dinky-flink/dinky-flink-1.18/pom.xml
  dinky-sandbox/dinky-sandbox-base/pom.xml
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/AbstractSandbox.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/Sandbox.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/SandboxFactory.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/metadata/ColumnInfo.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/metadata/TableId.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/metadata/TableInfo.java
  dinky-sandbox/dinky-sandbox-base/src/main/java/org/dinky/sandbox/metadata/TableType.java
  dinky-sandbox/dinky-sandbox-memory/pom.xml
  dinky-sandbox/dinky-sandbox-memory/src/main/java/org/dinky/sandbox/MemorySandbox.java
  dinky-sandbox/dinky-sandbox-memory/src/main/resources/META-INF/services/org.dinky.sandbox.Sandbox
  dinky-sandbox/pom.xml
  pom.xml
Labels: New Feature

#4329 [Fix-4269] Fix the flinksql multi-version switch button does not take effect
  dinky-admin/src/main/java/org/dinky/service/impl/TaskServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/TaskVersionServiceImpl.java
Labels: Bug

#4330 [Optimization-4270] Check if the cluster is disabled before starting the flink session
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterConfigurationServiceImpl.java
  dinky-admin/src/main/java/org/dinky/service/impl/ClusterInstanceServiceImpl.java
Labels: Optimization

#4331 [Fix-4271] Fix the issue of the page constantly refreshing
  dinky-web/src/pages/DataStudio/Toolbar/Project/JobModal/index.tsx
Labels: Bug

#4334 [Fix-4317] Fix metadata-hive MissingFormatArgumentException
  dinky-metadata/dinky-metadata-hive/src/main/java/org/dinky/metadata/query/HiveQuery.java
Labels: Bug

#4333 [Fix-4287] Fix the issue where the form is cleared on the frontend when creating a new task
  dinky-web/src/pages/DataStudio/Toolbar/Project/JobModal/index.tsx
Labels: Bug

#4332 [Fix-4290] Sync the helm configuration with src/main/resources directory
  deploy/kubernetes/helm/dinky/conf/application-flyway.yml
  deploy/kubernetes/helm/dinky/conf/application-h2.yml
  deploy/kubernetes/helm/dinky/conf/application-postgresql.yml
  deploy/kubernetes/helm/dinky/conf/application.yml
Labels: Bug

#4335 [Fix-4327] Fix comparison expression issue
  script/bin/auto.sh
Labels: Bug

#4339 [Fix-4338] Optimize the page rendering logic
  dinky-web/src/components/Modal/WsErrorShow/WsErrorShow.tsx
  dinky-web/src/models/UseWebSocketModel.tsx
  dinky-web/src/pages/DataStudio/CenterTabContent/SqlTask/index.tsx
  dinky-web/src/pages/Other/Login/index.tsx
Labels: Bug

#4340 [Optimization-4303] Support recover from the latest completed CheckPoint
  dinky-web/src/pages/DevOps/JobDetail/CheckPointsTab/components/CkDesc.tsx
Labels: New Feature
