Repository DataLinkDC/dinky, pull requests merged in 2025-07, with the labels that each got.

#4406 [Fix-4405][CICD] Fix cicd k3d bug
  .github/workflows/backend.yaml
Labels: Fixed

#4402 [Bug] Fix operator submit bug
  dinky-gateway/src/main/java/org/dinky/gateway/AbstractGateway.java
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesOperatorGateway.java
Labels: Bug

#4403 [Bug] Fix the token cannot be refreshed properly.
  dinky-admin/src/main/java/org/dinky/controller/TokenController.java
  dinky-admin/src/main/java/org/dinky/service/impl/TokenService.java
Labels: Bug

#4414 [Bug][dinky-web] Remove slash checks for jm url
  dinky-web/src/locales/en-US/pages.ts
  dinky-web/src/locales/zh-CN/pages.ts
  dinky-web/src/pages/DevOps/JobDetail/JobOperator/components/EditJobInstanceForm.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/InstanceModal/InstanceForm/index.tsx
  dinky-web/src/pages/RegCenter/Cluster/Instance/components/function.tsx
Labels: Optimization

#4422 [Optimize-3599][admin] CatalogueService add a new method findByTaskId
  dinky-admin/src/main/java/org/dinky/controller/CatalogueController.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/CatalogueService.java
  dinky-admin/src/main/java/org/dinky/service/catalogue/impl/CatalogueServiceImpl.java
  dinky-admin/src/test/java/org/dinky/service/catalogue/impl/CatalogueServiceImplTest.java
Labels: Optimization, Powered By AI

#4420 [Fix-4384][web] Fix the problem of task positioning error
  .github/workflows/format_code.yaml
  dinky-web/src/pages/DataStudio/Toolbar/Project/index.tsx
  dinky-web/src/pages/RegCenter/DataSource/components/DataSourceDetail/RightTagsRouter/index.tsx
Labels: Bug, Powered By AI

#4424 [Fix-4419] Remove CONF_DIR from FlinkConfiguration
  dinky-gateway/src/main/java/org/dinky/gateway/kubernetes/operator/KubernetesOperatorGateway.java
Labels: Bug, Powered By AI

#4429 [Fix-4313] Fix Array type in paimon query did not show the value
  dinky-metadata/dinky-metadata-paimon/src/main/java/org/dinky/metadata/convert/PaimonTypeConvert.java
Labels: Bug
